*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.70e-03[uF]/100[V]
* Murata P/N :GCM3195C2A272JA16
* Property : C = 2.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM3195C2A272JA16 Port1 Port2
C01 Port1 N01 2.68e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 1.13e-10
R03 N02 N03 1.50e-02
L04 N03 N04 8.65e-11
R04 N03 N04 3.96e-01
L05 N04 N05 7.49e-11
R05 N04 N05 1.37e-02
C06 N05 N06 1.06e-08
L06 N05 N06 3.10e-11
R06 N05 N06 3.29e-01
C07 N06 N07 2.60e-09
L07 N06 N07 4.40e-11
R07 N06 N07 5.66e-01
C08 N07 Port2 9.09e-13
L08 N07 Port2 4.98e-10
R08 N07 Port2 8.18e+02
.ENDS GCM3195C2A272JA16
