*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.00e-05[uF]/630[V]
* Murata P/N :GCM31A5C2J100GX01
* Property : C = 1.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C2J100GX01 Port1 Port2
C01 Port1 N01 1.00e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 4.37e-15
R03 N02 N03 3.27e-01
C04 N03 N04 1.60e-10
R04 N03 N04 9.26e+03
L05 N04 N05 4.92e-11
R05 N04 N05 1.27e+00
C06 N05 Port2 7.45e-13
L06 N05 Port2 9.11e-10
R06 N05 Port2 6.05e+02
.ENDS GCM31A5C2J100GX01
