*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/1.80e-02[uF]/50[V]
* Murata P/N :GCM3192C1H183JA01
* Property : C = 1.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM3192C1H183JA01 Port1 Port2
C01 Port1 N01 1.86e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 3.17e-11
R03 N02 N03 6.90e-03
L04 N03 N04 9.88e-11
R04 N03 N04 1.54e-01
L05 N04 N05 2.11e-11
R05 N04 N05 7.27e-02
L06 N05 N06 7.74e-11
R06 N05 N06 7.91e-03
C07 N06 N07 8.85e-08
L07 N06 N07 3.07e-11
R07 N06 N07 1.63e-01
C08 N07 N08 2.43e-08
L08 N07 N08 4.27e-11
R08 N07 N08 2.23e-01
C09 N08 Port2 9.68e-13
L09 N08 Port2 5.06e-10
R09 N08 Port2 5.99e+02
.ENDS GCM3192C1H183JA01
