*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.80e-04[uF]/1000[V]
* Murata P/N :GCM31A5C3A181GX01
* Property : C = 1.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C3A181GX01 Port1 Port2
C01 Port1 N01 1.80e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 3.63e-13
R03 N02 N03 8.66e-02
C04 N03 N04 1.91e-07
R04 N03 N04 7.79e-02
C05 N04 N05 7.78e-10
L05 N04 N05 2.04e-11
R05 N04 N05 8.81e-01
C06 N05 N06 8.06e-11
L06 N05 N06 5.81e-11
R06 N05 N06 2.46e+00
C07 N06 Port2 7.65e-13
L07 N06 Port2 8.66e-10
R07 N06 Port2 5.11e+02
.ENDS GCM31A5C3A181GX01
