*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.20e-03[uF]/630[V]
* Murata P/N :GCM31B5C2J222FX01
* Property : C = 2.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31B5C2J222FX01 Port1 Port2
C01 Port1 N01 2.20e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 2.08e-15
R03 N02 N03 7.79e-03
C04 N03 N04 4.93e-08
R04 N03 N04 1.25e+02
L05 N04 N05 1.02e-10
R05 N04 N05 2.33e-02
C06 N05 N06 8.15e-09
L06 N05 N06 4.57e-11
R06 N05 N06 6.08e-01
C07 N06 N07 2.96e-09
L07 N06 N07 5.03e-11
R07 N06 N07 8.77e-01
C08 N07 N08 1.42e-09
L08 N07 N08 3.14e-11
R08 N07 N08 3.12e-01
C09 N08 N09 6.25e-11
L09 N08 N09 1.56e-11
R09 N08 N09 2.56e+00
C10 N09 N10 5.80e-12
L10 N09 N10 1.11e-10
R10 N09 N10 1.33e+00
C11 N10 Port2 8.40e-13
L11 N10 Port2 6.39e-10
R11 N10 Port2 9.42e+02
.ENDS GCM31B5C2J222FX01
