*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/8.20e-02[uF]/50[V]
* Murata P/N :GCM31C5C1H823JA16
* Property : C = 8.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31C5C1H823JA16 Port1 Port2
C01 Port1 N01 8.30e-08
R01 Port1 N01 1.22e+10
L02 N01 N02 1.64e-10
R03 N02 N03 2.72e-03
L04 N03 N04 1.48e-11
R04 N03 N04 1.54e-01
L05 N04 N05 2.09e-10
R05 N04 N05 1.30e-01
L06 N05 N06 1.89e-10
R06 N05 N06 2.58e-03
C07 N06 N07 2.46e-07
L07 N06 N07 8.93e-11
R07 N06 N07 2.28e-01
C08 N07 N08 1.52e-07
L08 N07 N08 6.79e-11
R08 N07 N08 1.98e-01
C09 N08 N09 2.41e-07
L09 N08 N09 2.27e-11
R09 N08 N09 6.63e-02
C10 N09 N10 1.29e-07
L10 N09 N10 2.73e-11
R10 N09 N10 6.90e-02
C11 N10 Port2 1.11e-12
L11 N10 Port2 2.89e-10
R11 N10 Port2 4.50e+02
.ENDS GCM31C5C1H823JA16
