*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/3.90e-02[uF]/50[V]
* Murata P/N :GCM3192C1H393JA01
* Property : C = 3.90e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM3192C1H393JA01 Port1 Port2
C01 Port1 N01 3.89e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 8.20e-11
R03 N02 N03 5.00e-03
L04 N03 N04 1.45e-10
R04 N03 N04 1.67e-01
L05 N04 N05 3.72e-11
R05 N04 N05 3.66e-03
C06 N05 N06 1.37e-07
L06 N05 N06 4.66e-11
R06 N05 N06 1.48e-01
C07 N06 N07 4.34e-08
L07 N06 N07 6.48e-11
R07 N06 N07 2.21e-01
C08 N07 Port2 9.88e-13
L08 N07 Port2 3.79e-10
R08 N07 Port2 3.25e+02
.ENDS GCM3192C1H393JA01
