*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.50e-04[uF]/630[V]
* Murata P/N :GCM31A5C2J151JX01
* Property : C = 1.50e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C2J151JX01 Port1 Port2
C01 Port1 N01 1.50e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 8.10e-11
R03 N02 N03 7.55e-02
L04 N03 N04 1.07e-10
R04 N03 N04 7.77e-02
C05 N04 N05 1.50e-07
L05 N04 N05 2.90e-11
R05 N04 N05 2.05e-02
C06 N05 N06 8.68e-10
L06 N05 N06 8.66e-12
R06 N05 N06 3.78e-01
C07 N06 N07 1.11e-10
L07 N06 N07 1.88e-11
R07 N06 N07 1.89e+00
C08 N07 Port2 9.49e-13
L08 N07 Port2 7.82e-10
R08 N07 Port2 1.44e+02
.ENDS GCM31A5C2J151JX01
