*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/1.20e-03[uF]/630[V]
* Murata P/N :GCM31A7U2J122JX01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A7U2J122JX01 Port1 Port2
C01 Port1 N01 1.23e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 8.37e-11
R03 N02 N03 1.81e-02
L04 N03 N04 1.06e-10
R04 N03 N04 7.98e-01
C05 N04 N05 2.90e-08
L05 N04 N05 5.88e-11
R05 N04 N05 2.31e-02
C06 N05 N06 5.36e-09
L06 N05 N06 2.48e-11
R06 N05 N06 5.07e-01
C07 N06 N07 1.57e-09
L07 N06 N07 2.88e-11
R07 N06 N07 6.76e-01
C08 N07 Port2 7.91e-13
L08 N07 Port2 5.40e-10
R08 N07 Port2 3.18e+02
.ENDS GCM31A7U2J122JX01
