*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/5.60e-05[uF]/1000[V]
* Murata P/N :GCM31A5C3A560FX01
* Property : C = 5.60e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C3A560FX01 Port1 Port2
C01 Port1 N01 5.60e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 3.03e-12
R03 N02 N03 1.30e-01
C04 N03 N04 1.73e-10
L04 N03 N04 2.66e-11
R04 N03 N04 2.49e+00
C05 N04 N05 1.98e-11
L05 N04 N05 6.89e-11
R05 N04 N05 1.31e+01
C06 N05 N06 3.22e-11
L06 N05 N06 3.33e-11
R06 N05 N06 8.86e+00
C07 N06 Port2 1.05e-12
L07 N06 Port2 6.81e-10
R07 N06 Port2 3.87e+02
.ENDS GCM31A5C3A560FX01
