*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.00e-03[uF]/1000[V]
* Murata P/N :GCM31C5C3A102JX03
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31C5C3A102JX03 Port1 Port2
C01 Port1 N01 1.00e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 1.53e-10
R03 N02 N03 5.50e-04
C04 N03 N04 2.83e-08
R04 N03 N04 9.06e+01
L05 N04 N05 1.15e-10
R05 N04 N05 3.01e-02
C06 N05 N06 2.68e-09
L06 N05 N06 8.93e-11
R06 N05 N06 2.18e+00
C07 N06 N07 1.57e-09
L07 N06 N07 6.84e-11
R07 N06 N07 1.97e+00
C08 N07 N08 3.09e-09
L08 N07 N08 1.75e-11
R08 N07 N08 5.90e-01
C09 N08 N09 1.64e-09
L09 N08 N09 2.09e-11
R09 N08 N09 7.18e-01
C10 N09 N10 5.44e-10
L10 N09 N10 3.06e-11
R10 N09 N10 4.99e-01
C11 N10 N11 6.36e-11
L11 N10 N11 6.40e-11
R11 N10 N11 8.19e-01
C12 N11 N12 1.30e-11
L12 N11 N12 4.92e-11
R12 N11 N12 6.85e+00
C13 N12 Port2 1.18e-12
L13 N12 Port2 3.85e-10
R13 N12 Port2 5.69e+02
.ENDS GCM31C5C3A102JX03
