*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.70e-05[uF]/1000[V]
* Murata P/N :GCM31A5C3A270JX01
* Property : C = 2.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C3A270JX01 Port1 Port2
C01 Port1 N01 2.70e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 1.37e-13
R03 N02 N03 2.15e-01
C04 N03 N04 6.45e-06
R04 N03 N04 2.90e+00
C05 N04 N05 5.64e-12
L05 N04 N05 1.73e-10
R05 N04 N05 3.23e+01
C06 N05 Port2 9.70e-13
L06 N05 Port2 7.64e-10
R06 N05 Port2 4.73e+02
.ENDS GCM31A5C3A270JX01
