*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/5.60e-05[uF]/630[V]
* Murata P/N :GCM31A7U2J560JX01
* Property : C = 5.60e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A7U2J560JX01 Port1 Port2
C01 Port1 N01 5.60e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 8.98e-11
R03 N02 N03 1.49e-01
C04 N03 N04 1.87e-10
L04 N03 N04 2.92e-11
R04 N03 N04 1.96e+00
C05 N04 N05 2.52e-11
L05 N04 N05 6.67e-11
R05 N04 N05 7.53e+00
C06 N05 Port2 1.09e-12
L06 N05 Port2 5.80e-10
R06 N05 Port2 6.19e+02
.ENDS GCM31A7U2J560JX01
