*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/1.20e-04[uF]/630[V]
* Murata P/N :GCM31A7U2J121JX01
* Property : C = 1.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A7U2J121JX01 Port1 Port2
C01 Port1 N01 1.20e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 2.74e-11
R03 N02 N03 1.23e-01
C04 N03 N04 5.14e-10
L04 N03 N04 1.74e-11
R04 N03 N04 7.88e-01
C05 N04 N05 5.15e-11
L05 N04 N05 5.27e-11
R05 N04 N05 3.23e+00
C06 N05 Port2 8.68e-13
L06 N05 Port2 7.34e-10
R06 N05 Port2 4.52e+02
.ENDS GCM31A7U2J121JX01
