*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.20e-04[uF]/630[V]
* Murata P/N :GCM31A5C2J121JX01
* Property : C = 1.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C2J121JX01 Port1 Port2
C01 Port1 N01 1.20e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 1.69e-14
R03 N02 N03 1.65e-01
C04 N03 N04 8.93e-05
R04 N03 N04 1.66e-01
C05 N04 N05 1.28e-12
L05 N04 N05 5.03e-10
R05 N04 N05 8.53e+01
C06 N05 N06 4.01e-12
L06 N05 N06 1.27e-10
R06 N05 N06 5.10e+01
C07 N06 Port2 1.39e-12
L07 N06 Port2 3.17e-10
R07 N06 Port2 1.86e+02
.ENDS GCM31A5C2J121JX01
