*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/6.80e-03[uF]/630[V]
* Murata P/N :GCM31C5C2J682GX03
* Property : C = 6.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31C5C2J682GX03 Port1 Port2
C01 Port1 N01 6.71e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 5.65e-10
R03 N02 N03 1.55e-02
C04 N03 N04 9.33e-07
R04 N03 N04 1.63e+02
L05 N04 N05 7.95e-11
R05 N04 N05 3.97e-01
L06 N05 N06 2.33e-11
R06 N05 N06 1.34e-02
C07 N06 N07 2.11e-08
L07 N06 N07 6.62e-11
R07 N06 N07 5.01e-01
C08 N07 N08 8.82e-09
L08 N07 N08 6.59e-11
R08 N07 N08 6.44e-01
C09 N08 N09 2.64e-08
L09 N08 N09 1.05e-11
R09 N08 N09 1.15e-01
C10 N09 N10 1.43e-08
L10 N09 N10 1.22e-11
R10 N09 N10 2.32e-01
C11 N10 N11 4.34e-09
L11 N10 N11 1.98e-11
R11 N10 N11 1.42e-01
C12 N11 Port2 3.32e-12
L12 N11 Port2 1.94e-10
R12 N11 Port2 1.29e+02
.ENDS GCM31C5C2J682GX03
