*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/5.60e-05[uF]/630[V]
* Murata P/N :GCM31A5C2J560JX01
* Property : C = 5.60e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C2J560JX01 Port1 Port2
C01 Port1 N01 5.60e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 4.78e-12
R03 N02 N03 1.26e-01
C04 N03 N04 1.41e-10
L04 N03 N04 3.03e-11
R04 N03 N04 2.64e+00
C05 N04 N05 1.48e-11
L05 N04 N05 8.79e-11
R05 N04 N05 1.77e+01
C06 N05 N06 2.71e-11
L06 N05 N06 3.82e-11
R06 N05 N06 9.49e+00
C07 N06 Port2 9.95e-13
L07 N06 Port2 6.41e-10
R07 N06 Port2 3.27e+02
.ENDS GCM31A5C2J560JX01
