*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/3.30e-02[uF]/50[V]
* Murata P/N :GCM3192C1H333JA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM3192C1H333JA01 Port1 Port2
C01 Port1 N01 3.30e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.14e-13
R03 N02 N03 5.02e-03
L04 N03 N04 1.55e-10
R04 N03 N04 2.07e-01
L05 N04 N05 1.59e-10
R05 N04 N05 9.13e-04
C06 N05 N06 7.59e-08
L06 N05 N06 7.12e-11
R06 N05 N06 1.75e-01
C07 N06 N07 5.05e-08
L07 N06 N07 4.62e-11
R07 N06 N07 2.17e-01
C08 N07 N08 6.71e-08
L08 N07 N08 1.59e-11
R08 N07 N08 3.65e-02
C09 N08 N09 7.49e-08
L09 N08 N09 9.07e-12
R09 N08 N09 4.37e-02
C10 N09 Port2 8.82e-13
L10 N09 Port2 4.48e-10
R10 N09 Port2 1.25e+03
.ENDS GCM3192C1H333JA01
