*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.70e-03[uF]/630[V]
* Murata P/N :GCM31B5C2J272GX01
* Property : C = 2.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31B5C2J272GX01 Port1 Port2
C01 Port1 N01 2.70e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 6.10e-11
R03 N02 N03 1.01e-02
C04 N03 N04 1.43e-07
R04 N03 N04 2.51e+01
L05 N04 N05 7.84e-11
R05 N04 N05 1.66e-02
C06 N05 N06 9.04e-09
L06 N05 N06 5.42e-11
R06 N05 N06 7.97e-01
C07 N06 N07 3.68e-09
L07 N06 N07 5.55e-11
R07 N06 N07 9.15e-01
C08 N07 N08 1.57e-08
L08 N07 N08 5.94e-12
R08 N07 N08 1.39e-01
C09 N08 N09 5.58e-09
L09 N08 N09 1.06e-11
R09 N08 N09 2.35e-01
C10 N09 N10 3.86e-10
L10 N09 N10 5.81e-11
R10 N09 N10 2.83e-01
C11 N10 N11 1.02e-12
L11 N10 N11 5.33e-10
R11 N10 N11 4.78e+02
C12 N11 Port2 8.25e-12
L12 N11 Port2 6.52e-11
R12 N11 Port2 1.03e+00
.ENDS GCM31B5C2J272GX01
