*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/5.60e-03[uF]/100[V]
* Murata P/N :GCM3192C2A562JA01
* Property : C = 5.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM3192C2A562JA01 Port1 Port2
C01 Port1 N01 5.56e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.30e-10
R03 N02 N03 7.71e-03
L04 N03 N04 1.30e-10
R04 N03 N04 4.34e-01
L05 N04 N05 6.86e-11
R05 N04 N05 1.28e-02
C06 N05 N06 2.26e-08
L06 N05 N06 4.97e-11
R06 N05 N06 4.11e-01
C07 N06 N07 8.10e-09
L07 N06 N07 5.27e-11
R07 N06 N07 5.12e-01
C08 N07 N08 4.02e-08
L08 N07 N08 5.75e-12
R08 N07 N08 8.21e-02
C09 N08 N09 7.72e-09
L09 N08 N09 1.65e-11
R09 N08 N09 1.60e-01
C10 N09 Port2 1.47e-12
L10 N09 Port2 2.83e-10
R10 N09 Port2 1.32e+02
.ENDS GCM3192C2A562JA01
