*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.50e-05[uF]/630[V]
* Murata P/N :GCM31A5C2J150FX01
* Property : C = 1.50e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31A5C2J150FX01 Port1 Port2
C01 Port1 N01 1.50e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 1.37e-11
R03 N02 N03 2.77e-01
L04 N03 N04 6.05e-11
R04 N03 N04 2.80e+00
C05 N04 N05 1.28e-10
L05 N04 N05 9.67e-12
R05 N04 N05 5.06e+00
C06 N05 N06 2.41e-11
L06 N05 N06 4.43e-11
R06 N05 N06 1.00e+01
C07 N06 Port2 8.53e-13
L07 N06 Port2 7.69e-10
R07 N06 Port2 5.49e+02
.ENDS GCM31A5C2J150FX01
