*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN30NJ8Z
* Property : L = 30[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN30NJ8Z port1 port2
C1 port1 port2 2.64e-14
L2 port1 1 3.16e-8
R2 1 port2 2.57e-1
R3 port1 port2 1.42e+4
L4 port1 2 4.14e-7
R4 2 port2 81.5
L5 port1 3 1.03e-6
R5 3 port2 1.62e+3
L6 port1 4 2.28e-6
C6 4 5 1.20e-16
R6 5 port2 7.03e+3
.ENDS LQW15AN30NJ8Z
*----------------------------------------------------------------------
