*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN5N5C8Z
* Property : L = 5.5[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN5N5C8Z port1 port2
C1 port1 port2 4.38e-14
L2 port1 1 5.56e-9
R2 1 port2 3.30e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.45e-7
R4 2 port2 36.2
L5 port1 3 2.24e-7
R5 3 port2 632
.ENDS LQW15AN5N5C8Z
*----------------------------------------------------------------------
