*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN9N1J8Z
* Property : L = 9.1[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN9N1J8Z port1 port2
C1 port1 port2 5.02e-14
L2 port1 1 9.48e-9
R2 1 port2 6.60e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.20e-7
R4 2 port2 32.4
L5 port1 3 3.41e-7
R5 3 port2 984
L6 port1 4 2.23e-6
C6 4 5 2.94e-17
R6 5 port2 7.03e+3
.ENDS LQW15AN9N1J8Z
*----------------------------------------------------------------------
