*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN4N2B8Z
* Property : L = 4.2[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN4N2B8Z port1 port2
C1 port1 port2 3.55e-14
L2 port1 1 4.11e-9
R2 1 port2 3.60e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.17e-7
R4 2 port2 30.8
L5 port1 3 1.49e-7
R5 3 port2 382
.ENDS LQW15AN4N2B8Z
*----------------------------------------------------------------------
