*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN4N6D8Z
* Property : L = 4.6[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN4N6D8Z port1 port2
C1 port1 port2 2.76e-14
L2 port1 1 4.62e-9
R2 1 port2 5.00e-2
R3 port1 port2 1.42e+4
L4 port1 2 7.61e-8
R4 2 port2 9.50
L5 port1 3 1.49e-7
R5 3 port2 409
.ENDS LQW15AN4N6D8Z
*----------------------------------------------------------------------
