*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/B(-25to85[deg])/6.80e-04[uF]/50[V]
* Murata P/N :GRM15XB11H681MA86
* Property : C = 6.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM15XB11H681MA86 Port1 Port2
C01 Port1 N01 6.60e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.81e-10
R03 N02 N03 3.39e-01
C04 N03 N04 6.19e-08
R04 N03 N04 1.96e+04
C05 N04 N05 8.99e-08
R05 N04 N05 9.15e+02
C06 N05 N06 1.08e-07
R06 N05 N06 6.63e+01
C07 N06 N07 1.05e-07
R07 N06 N07 1.55e+01
C08 N07 N08 4.84e-08
R08 N07 N08 3.85e+00
C09 N08 N09 2.02e-08
R09 N08 N09 7.52e-01
C10 N09 N10 6.00e-09
R10 N09 N10 2.51e-01
L11 N10 N11 2.12e-11
R11 N10 N11 1.70e-01
C12 N11 Port2 9.18e-13
L12 N11 Port2 1.37e-10
R12 N11 Port2 1.23e+01
.ENDS GRM15XB11H681MA86
