*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/B(-25to85[deg])/4.70e-03[uF]/16[V]
* Murata P/N :GRM15XB11C472MA86
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM15XB11C472MA86 Port1 Port2
C01 Port1 N01 4.62e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.30e-10
R03 N02 N03 1.15e-01
C04 N03 N04 7.85e-07
R04 N03 N04 3.77e+03
C05 N04 N05 1.49e-06
R05 N04 N05 6.86e+02
C06 N05 N06 7.58e-07
R06 N05 N06 2.38e+02
C07 N06 N07 6.91e-07
R07 N06 N07 2.99e+01
C08 N07 N08 5.48e-07
R08 N07 N08 4.04e+00
C09 N08 N09 3.90e-07
R09 N08 N09 6.06e-01
C10 N09 N10 7.78e-07
R10 N09 N10 8.39e-02
C11 N10 N11 1.98e-07
R11 N10 N11 8.04e-02
L12 N11 N12 4.84e-11
R12 N11 N12 5.92e-01
C13 N12 N13 1.63e-09
L13 N12 N13 2.92e-11
R13 N12 N13 9.56e-02
C14 N13 Port2 7.07e-12
L14 N13 Port2 3.97e-11
R14 N13 Port2 9.00e+00
.ENDS GRM15XB11C472MA86
