*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/R(-55to125[deg])/2.20e-02[uF]/16[V]
* Murata P/N :GRM155R11C223MA01
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R11C223MA01 Port1 Port2
C01 Port1 N01 2.12e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.35e-10
R03 N02 N03 4.51e-02
C04 N03 N04 2.23e-06
R04 N03 N04 1.66e+03
C05 N04 N05 4.85e-06
R05 N04 N05 1.09e+02
C06 N05 N06 3.60e-06
R06 N05 N06 2.34e+01
C07 N06 N07 3.32e-06
R07 N06 N07 4.80e+00
C08 N07 N08 2.40e-06
R08 N07 N08 8.30e-01
C09 N08 N09 1.56e-06
R09 N08 N09 1.38e-01
C10 N09 N10 1.02e-06
R10 N09 N10 1.90e-02
L11 N10 N11 5.66e-11
R11 N10 N11 1.51e-01
L12 N11 N12 3.81e-12
R12 N11 N12 1.30e-01
C13 N12 N13 1.75e-08
L13 N12 N13 4.06e-11
R13 N12 N13 4.05e-02
C14 N13 Port2 1.71e-12
L14 N13 Port2 1.61e-10
R14 N13 Port2 2.50e+01
.ENDS GRM155R11C223MA01
