*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.50e+01[uF]/4[V]
* Murata P/N :GRM155R60G156ME15
* Property : C = 1.50e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R60G156ME15 Port1 Port2
C01 Port1 N01 1.13e-05
R01 Port1 N01 3.33e+06
L02 N01 N02 1.31e-10
R03 N02 N03 3.85e-03
C04 N03 N04 6.92e-04
R04 N03 N04 7.15e+00
C05 N04 N05 7.90e-04
R05 N04 N05 6.01e-01
C06 N05 N06 8.78e-04
R06 N05 N06 6.17e-02
C07 N06 N07 6.90e-04
R07 N06 N07 6.47e-03
L08 N07 N08 2.21e-11
R08 N07 N08 1.39e-01
L09 N08 N09 7.26e-11
R09 N08 N09 5.90e-02
L10 N09 N10 2.07e-10
R10 N09 N10 1.90e-02
C11 N10 N11 7.95e-06
L11 N10 N11 1.40e-10
R11 N10 N11 3.50e-03
C12 N11 Port2 3.77e-11
L12 N11 Port2 5.81e-12
R12 N11 Port2 6.09e-01
.ENDS GRM155R60G156ME15
