*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/2.70e-02[uF]/25[V]
* Murata P/N :GRM155R71E273KA88
* Property : C = 2.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R71E273KA88 Port1 Port2
C01 Port1 N01 2.78e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.99e-10
R03 N02 N03 4.69e-02
C04 N03 N04 2.72e-06
R04 N03 N04 1.26e+03
C05 N04 N05 8.21e-06
R05 N04 N05 7.60e+01
C06 N05 N06 3.61e-06
R06 N05 N06 3.64e+01
C07 N06 N07 3.17e-06
R07 N06 N07 3.72e+00
C08 N07 N08 2.48e-05
R08 N07 N08 1.20e+00
C09 N08 N09 2.58e-06
R09 N08 N09 5.14e-01
C10 N09 N10 2.39e-06
R10 N09 N10 8.90e-02
C11 N10 N11 1.79e-06
R11 N10 N11 2.17e-02
L12 N11 N12 6.51e-11
R12 N11 N12 2.60e-01
C13 N12 N13 1.24e-08
L13 N12 N13 4.61e-11
R13 N12 N13 4.41e-02
C14 N13 Port2 3.37e-12
L14 N13 Port2 1.02e-10
R14 N13 Port2 1.23e+01
.ENDS GRM155R71E273KA88
