*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/2.20e+00[uF]/16[V]
* Murata P/N :GRM155R61C225KE44
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61C225KE44 Port1 Port2
C01 Port1 N01 1.72e-06
R01 Port1 N01 2.27e+07
L02 N01 N02 1.40e-10
R03 N02 N03 5.95e-03
C04 N03 N04 7.10e-05
R04 N03 N04 1.11e+01
C05 N04 N05 6.62e-05
R05 N04 N05 1.58e+00
C06 N05 N06 6.05e-05
R06 N05 N06 2.01e-01
C07 N06 N07 4.98e-05
R07 N06 N07 2.77e-02
C08 N07 N08 5.40e-05
R08 N07 N08 5.28e-03
L09 N08 N09 7.37e-12
R09 N08 N09 8.30e-02
L10 N09 N10 2.50e-11
R10 N09 N10 6.23e-02
L11 N10 N11 1.49e-10
R11 N10 N11 2.63e-02
C12 N11 N12 7.95e-06
L12 N11 N12 2.59e-11
R12 N11 N12 3.26e-03
C13 N12 N13 4.47e-06
L13 N12 N13 2.51e-11
R13 N12 N13 3.89e-03
C14 N13 Port2 5.19e-12
L14 N13 Port2 3.97e-11
R14 N13 Port2 1.06e+01
.ENDS GRM155R61C225KE44
