*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X6T(-55to105[deg])/4.70e+00[uF]/10[V]
* Murata P/N :GRM155D81A475ME15
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155D81A475ME15 Port1 Port2
C01 Port1 N01 3.29e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.60e-10
R03 N02 N03 4.36e-03
C04 N03 N04 3.16e-04
R04 N03 N04 6.49e+00
C05 N04 N05 2.18e-04
R05 N04 N05 3.86e+00
C06 N05 N06 2.00e-04
R06 N05 N06 7.45e-01
C07 N06 N07 2.07e-04
R07 N06 N07 1.57e-01
C08 N07 N08 1.47e-04
R08 N07 N08 4.09e-02
C09 N08 N09 9.76e-05
R09 N08 N09 9.45e-03
L10 N09 N10 3.19e-11
R10 N09 N10 8.31e-02
L11 N10 N11 1.39e-10
R11 N10 N11 1.40e-02
L12 N11 N12 6.53e-11
R12 N11 N12 1.09e-02
C13 N12 N13 2.19e-05
L13 N12 N13 2.19e-11
R13 N12 N13 3.61e-03
C14 N13 N14 3.85e-06
L14 N13 N14 5.73e-11
R14 N13 N14 6.21e-03
C15 N14 Port2 1.56e-11
L15 N14 Port2 1.25e-11
R15 N14 Port2 3.97e-01
.ENDS GRM155D81A475ME15
