*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X6S(-55to105[deg])/1.00e+01[uF]/2.5[V]
* Murata P/N :GRM155C80E106ME44
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155C80E106ME44 Port1 Port2
C01 Port1 N01 6.79e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 1.26e-10
R03 N02 N03 4.75e-03
C04 N03 N04 1.84e-04
R04 N03 N04 2.88e+01
C05 N04 N05 3.60e-04
R05 N04 N05 8.57e-01
C06 N05 N06 4.39e-04
R06 N05 N06 6.98e-02
C07 N06 N07 3.48e-04
R07 N06 N07 8.88e-03
C08 N07 N08 1.75e-04
R08 N07 N08 1.75e-03
L09 N08 N09 4.34e-11
R09 N08 N09 2.21e-01
L10 N09 N10 8.98e-11
R10 N09 N10 6.29e-02
L11 N10 N11 1.93e-10
R11 N10 N11 1.60e-02
C12 N11 N12 6.95e-06
L12 N11 N12 9.82e-11
R12 N11 N12 3.17e-03
C13 N12 Port2 1.41e-11
L13 N12 Port2 1.87e-11
R13 N12 Port2 2.24e+00
.ENDS GRM155C80E106ME44
