*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.00e+01[uF]/2.5[V]
* Murata P/N :GRM155R60E106ME16
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R60E106ME16 Port1 Port2
C01 Port1 N01 7.21e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 1.35e-10
R03 N02 N03 5.52e-03
C04 N03 N04 4.24e-04
R04 N03 N04 7.25e+00
C05 N04 N05 4.84e-04
R05 N04 N05 8.65e-01
C06 N05 N06 4.79e-04
R06 N05 N06 1.23e-01
C07 N06 N07 4.56e-04
R07 N06 N07 1.45e-02
C08 N07 N08 3.47e-04
R08 N07 N08 2.15e-03
L09 N08 N09 4.13e-11
R09 N08 N09 1.36e-01
L10 N09 N10 7.83e-11
R10 N09 N10 3.83e-02
L11 N10 N11 1.98e-10
R11 N10 N11 1.58e-02
C12 N11 N12 1.29e-05
L12 N11 N12 8.21e-11
R12 N11 N12 1.58e-03
C13 N12 N13 2.86e-05
L13 N12 N13 2.00e-11
R13 N12 N13 1.22e-03
C14 N13 Port2 9.29e-12
L14 N13 Port2 2.76e-11
R14 N13 Port2 3.72e+00
.ENDS GRM155R60E106ME16
