*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X6T(-55to105[deg])/2.20e+00[uF]/6.3[V]
* Murata P/N :GRM155D80J225ME95
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155D80J225ME95 Port1 Port2
C01 Port1 N01 1.75e-06
R01 Port1 N01 2.27e+07
L02 N01 N02 1.66e-10
R03 N02 N03 1.02e-02
C04 N03 N04 8.06e-05
R04 N03 N04 6.14e+01
C05 N04 N05 1.25e-04
R05 N04 N05 6.22e+00
C06 N05 N06 1.82e-04
R06 N05 N06 8.78e-01
C07 N06 N07 2.01e-04
R07 N06 N07 1.72e-01
C08 N07 N08 1.57e-04
R08 N07 N08 3.28e-02
C09 N08 N09 9.62e-05
R09 N08 N09 6.65e-03
L10 N09 N10 3.22e-11
R10 N09 N10 2.75e-01
L11 N10 N11 3.31e-11
R11 N10 N11 4.86e-02
L12 N11 N12 1.28e-10
R12 N11 N12 2.32e-02
C13 N12 N13 2.24e-06
L13 N12 N13 5.54e-11
R13 N12 N13 4.59e-03
C14 N13 Port2 2.08e-11
L14 N13 Port2 1.58e-11
R14 N13 Port2 4.09e+00
.ENDS GRM155D80J225ME95
