*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.00e+00[uF]/10[V]
* Murata P/N :GRM155R61A105KE01
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61A105KE01 Port1 Port2
C01 Port1 N01 7.82e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.78e-10
R03 N02 N03 1.42e-02
C04 N03 N04 4.37e-06
R04 N03 N04 1.71e+03
C05 N04 N05 3.28e-05
R05 N04 N05 1.46e+01
C06 N05 N06 3.38e-05
R06 N05 N06 1.33e+00
C07 N06 N07 3.14e-05
R07 N06 N07 1.48e-01
C08 N07 N08 2.09e-05
R08 N07 N08 2.27e-02
L09 N08 N09 3.38e-11
R09 N08 N09 1.41e-01
L10 N09 N10 1.10e-10
R10 N09 N10 4.24e-02
C11 N10 N11 5.33e-07
L11 N10 N11 8.71e-11
R11 N10 N11 1.33e-02
C12 N11 Port2 7.86e-12
L12 N11 Port2 4.09e-11
R12 N11 Port2 2.71e+00
.ENDS GRM155R61A105KE01
