*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/4.70e-01[uF]/10[V]
* Murata P/N :GRM155R71A474KE01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R71A474KE01 Port1 Port2
C01 Port1 N01 2.78e-07
R01 Port1 N01 1.06e+08
L02 N01 N02 1.81e-10
R03 N02 N03 1.40e-02
C04 N03 N04 8.14e-06
R04 N03 N04 4.89e+02
C05 N04 N05 1.13e-05
R05 N04 N05 5.12e+01
C06 N05 N06 1.05e-05
R06 N05 N06 6.90e+00
C07 N06 N07 1.13e-05
R07 N06 N07 1.26e+00
C08 N07 N08 8.02e-06
R08 N07 N08 3.05e-01
C09 N08 N09 6.81e-06
R09 N08 N09 4.77e-02
C10 N09 N10 4.48e-06
R10 N09 N10 1.51e-02
L11 N10 N11 2.56e-11
R11 N10 N11 1.41e-01
L12 N11 N12 1.11e-10
R12 N11 N12 5.61e-02
C13 N12 N13 1.59e-06
L13 N12 N13 1.64e-11
R13 N12 N13 6.04e-03
C14 N13 N14 5.16e-07
L14 N13 N14 2.30e-11
R14 N13 N14 1.05e-02
C15 N14 Port2 3.03e-12
L15 N14 Port2 5.92e-11
R15 N14 Port2 8.81e+00
.ENDS GRM155R71A474KE01
