*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/4.70e+00[uF]/6.3[V]
* Murata P/N :GRM153R60J475ME15
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM153R60J475ME15 Port1 Port2
C01 Port1 N01 3.64e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.08e-10
R03 N02 N03 7.85e-03
C04 N03 N04 2.37e-04
R04 N03 N04 1.76e+01
C05 N04 N05 2.70e-04
R05 N04 N05 2.03e+00
C06 N05 N06 3.08e-04
R06 N05 N06 2.44e-01
C07 N06 N07 2.97e-04
R07 N06 N07 3.13e-02
C08 N07 N08 1.88e-04
R08 N07 N08 4.96e-03
L09 N08 N09 4.82e-11
R09 N08 N09 1.97e-01
L10 N09 N10 1.70e-10
R10 N09 N10 7.16e-02
C11 N10 N11 4.16e-06
L11 N10 N11 6.33e-11
R11 N10 N11 2.66e-03
C12 N11 N12 1.65e-06
L12 N11 N12 4.43e-11
R12 N11 N12 3.28e-03
C13 N12 Port2 4.55e-12
L13 N12 Port2 4.78e-11
R13 N12 Port2 1.26e+01
.ENDS GRM153R60J475ME15
