*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/4.70e-04[uF]/50[V]
* Murata P/N :GRM155R71H471KA01
* Property : C = 4.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R71H471KA01 Port1 Port2
C01 Port1 N01 4.93e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.31e-10
R03 N02 N03 1.11e-01
C04 N03 N04 3.53e-08
R04 N03 N04 8.80e+04
C05 N04 N05 1.26e-07
R05 N04 N05 4.95e+03
C06 N05 N06 7.74e-08
R06 N05 N06 8.80e+02
C07 N06 N07 6.50e-08
R07 N06 N07 9.43e+01
C08 N07 N08 4.52e-08
R08 N07 N08 1.21e+01
C09 N08 N09 2.15e-08
R09 N08 N09 2.12e+00
C10 N09 N10 6.51e-09
R10 N09 N10 5.80e-01
C11 N10 N11 9.42e-10
R11 N10 N11 4.85e-01
C12 N11 N12 2.99e-09
L12 N11 N12 2.12e-11
R12 N11 N12 6.80e-02
C13 N12 N13 4.79e-12
L13 N12 N13 1.03e-10
R13 N12 N13 1.18e+00
C14 N13 Port2 1.60e-12
L14 N13 Port2 1.87e-10
R14 N13 Port2 2.06e+01
.ENDS GRM155R71H471KA01
