*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.00e+00[uF]/10[V]
* Murata P/N :GRM155R61A105KE15
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61A105KE15 Port1 Port2
C01 Port1 N01 9.21e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.71e-10
R03 N02 N03 7.22e-03
C04 N03 N04 1.17e-04
R04 N03 N04 2.70e+01
C05 N04 N05 2.11e-04
R05 N04 N05 2.73e+00
C06 N05 N06 1.76e-04
R06 N05 N06 7.24e-01
C07 N06 N07 1.24e-04
R07 N06 N07 1.60e-01
C08 N07 N08 1.19e-04
R08 N07 N08 2.27e-02
C09 N08 N09 1.24e-04
R09 N08 N09 3.30e-03
L10 N09 N10 9.41e-12
R10 N09 N10 1.63e-01
L11 N10 N11 3.40e-11
R11 N10 N11 8.18e-02
L12 N11 N12 1.62e-10
R12 N11 N12 3.08e-02
C13 N12 N13 5.33e-06
L13 N12 N13 2.30e-11
R13 N12 N13 3.79e-03
C14 N13 N14 4.08e-06
L14 N13 N14 1.61e-11
R14 N13 N14 3.69e-03
C15 N14 Port2 3.54e-11
L15 N14 Port2 9.02e-12
R15 N14 Port2 2.11e+00
.ENDS GRM155R61A105KE15
