*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/B(-25to85[deg])/1.00e+00[uF]/6.3[V]
* Murata P/N :GRM155B30J105ME18
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155B30J105ME18 Port1 Port2
C01 Port1 N01 7.81e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.50e-10
R03 N02 N03 1.17e-02
C04 N03 N04 5.13e-05
R04 N03 N04 7.53e+01
C05 N04 N05 4.63e-05
R05 N04 N05 1.16e+01
C06 N05 N06 5.78e-05
R06 N05 N06 1.33e+00
C07 N06 N07 5.73e-05
R07 N06 N07 2.31e-01
C08 N07 N08 4.57e-05
R08 N07 N08 4.41e-02
C09 N08 N09 3.42e-05
R09 N08 N09 9.23e-03
L10 N09 N10 1.43e-11
R10 N09 N10 1.55e-01
L11 N10 N11 2.69e-11
R11 N10 N11 4.82e-02
L12 N11 N12 1.28e-10
R12 N11 N12 3.06e-02
C13 N12 N13 4.24e-06
L13 N12 N13 1.64e-11
R13 N12 N13 2.59e-03
C14 N13 N14 2.60e-06
L14 N13 N14 1.47e-11
R14 N13 N14 3.94e-03
C15 N14 Port2 4.80e-12
L15 N14 Port2 5.89e-11
R15 N14 Port2 6.96e+00
.ENDS GRM155B30J105ME18
