*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X6S(-55to105[deg])/2.20e-01[uF]/6.3[V]
* Murata P/N :GRM155C80J224KE01
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155C80J224KE01 Port1 Port2
C01 Port1 N01 2.17e-07
R01 Port1 N01 2.27e+08
L02 N01 N02 2.02e-10
R03 N02 N03 1.72e-02
C04 N03 N04 2.14e-05
R04 N03 N04 1.86e+02
C05 N04 N05 2.96e-05
R05 N04 N05 2.45e+01
C06 N05 N06 3.13e-05
R06 N05 N06 3.62e+00
C07 N06 N07 3.81e-05
R07 N06 N07 4.66e-01
C08 N07 N08 2.91e-05
R08 N07 N08 1.04e-01
C09 N08 N09 1.59e-05
R09 N08 N09 1.77e-02
L10 N09 N10 2.97e-11
R10 N09 N10 1.82e-01
L11 N10 N11 1.09e-10
R11 N10 N11 5.56e-02
C12 N11 N12 1.41e-06
L12 N11 N12 1.46e-11
R12 N11 N12 5.80e-03
C13 N12 N13 5.49e-07
L13 N12 N13 1.96e-11
R13 N12 N13 8.07e-03
C14 N13 Port2 7.80e-12
L14 N13 Port2 3.68e-11
R14 N13 Port2 5.65e+00
.ENDS GRM155C80J224KE01
