*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.00e-02[uF]/16[V]
* Murata P/N :GRM155R61C103KA01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61C103KA01 Port1 Port2
C01 Port1 N01 9.60e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.60e-10
R03 N02 N03 7.41e-02
C04 N03 N04 1.10e-06
R04 N03 N04 3.62e+03
C05 N04 N05 1.92e-06
R05 N04 N05 3.01e+02
C06 N05 N06 1.41e-06
R06 N05 N06 6.44e+01
C07 N06 N07 1.86e-06
R07 N06 N07 6.59e+00
C08 N07 N08 1.37e-06
R08 N07 N08 1.80e+00
C09 N08 N09 9.05e-07
R09 N08 N09 4.72e-01
C10 N09 N10 3.51e-07
R10 N09 N10 1.05e-01
L11 N10 N11 5.57e-11
R11 N10 N11 1.83e-01
C12 N11 N12 1.22e-08
L12 N11 N12 2.08e-11
R12 N11 N12 4.36e-02
C13 N12 Port2 2.00e-12
L13 N12 Port2 1.49e-10
R13 N12 Port2 2.06e+01
.ENDS GRM155R61C103KA01
