*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X6S(-55to105[deg])/2.20e+00[uF]/10[V]
* Murata P/N :GRM155C81A225ME44
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155C81A225ME44 Port1 Port2
C01 Port1 N01 1.91e-06
R01 Port1 N01 2.27e+07
L02 N01 N02 1.56e-10
R03 N02 N03 5.91e-03
C04 N03 N04 5.62e-05
R04 N03 N04 2.55e+01
C05 N04 N05 6.25e-05
R05 N04 N05 2.37e+00
C06 N05 N06 6.22e-05
R06 N05 N06 2.97e-01
C07 N06 N07 4.86e-05
R07 N06 N07 4.52e-02
C08 N07 N08 5.01e-05
R08 N07 N08 6.95e-03
L09 N08 N09 2.62e-11
R09 N08 N09 1.99e-01
L10 N09 N10 2.82e-11
R10 N09 N10 3.50e-02
L11 N10 N11 1.52e-10
R11 N10 N11 2.09e-02
C12 N11 N12 1.02e-05
L12 N11 N12 2.09e-11
R12 N11 N12 2.25e-03
C13 N12 N13 3.73e-06
L13 N12 N13 2.67e-11
R13 N12 N13 3.86e-03
C14 N13 Port2 1.71e-11
L14 N13 Port2 1.41e-11
R14 N13 Port2 1.58e+00
.ENDS GRM155C81A225ME44
