*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/B(-25to85[deg])/4.70e+00[uF]/6.3[V]
* Murata P/N :GRM155B30J475ME87
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155B30J475ME87 Port1 Port2
C01 Port1 N01 3.99e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.25e-10
R03 N02 N03 5.71e-03
C04 N03 N04 1.51e-04
R04 N03 N04 3.69e+01
C05 N04 N05 2.24e-04
R05 N04 N05 2.02e+00
C06 N05 N06 3.27e-04
R06 N05 N06 1.38e-01
C07 N06 N07 3.22e-04
R07 N06 N07 1.39e-02
C08 N07 N08 2.23e-04
R08 N07 N08 1.96e-03
L09 N08 N09 4.09e-11
R09 N08 N09 1.94e-01
L10 N09 N10 4.31e-11
R10 N09 N10 3.45e-02
L11 N10 N11 1.80e-10
R11 N10 N11 1.68e-02
C12 N11 N12 1.05e-05
L12 N11 N12 4.71e-11
R12 N11 N12 2.26e-03
C13 N12 N13 9.15e-06
L13 N12 N13 2.62e-11
R13 N12 N13 2.22e-03
C14 N13 Port2 4.57e-12
L14 N13 Port2 4.75e-11
R14 N13 Port2 1.87e+01
.ENDS GRM155B30J475ME87
