*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R(-55to85[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GRM155R61C105MA12
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61C105MA12 Port1 Port2
C01 Port1 N01 6.61e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 9.93e-11
R03 N02 N03 1.12e-02
C04 N03 N04 2.55e-06
R04 N03 N04 2.74e+03
C05 N04 N05 1.19e-05
R05 N04 N05 2.54e+01
C06 N05 N06 1.25e-05
R06 N05 N06 2.42e+00
C07 N06 N07 9.90e-06
R07 N06 N07 2.95e-01
C08 N07 N08 7.19e-06
R08 N07 N08 3.13e-02
L09 N08 N09 3.54e-11
R09 N08 N09 1.48e-01
L10 N09 N10 1.21e-10
R10 N09 N10 3.60e-02
C11 N10 N11 1.95e-06
L11 N10 N11 2.54e-11
R11 N10 N11 5.15e-03
C12 N11 N12 1.30e-06
L12 N11 N12 2.16e-11
R12 N11 N12 5.51e-03
C13 N12 Port2 1.40e-12
L13 N12 Port2 9.72e-11
R13 N12 Port2 1.85e+01
.ENDS GRM155R61C105MA12
