*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1810M(0704)/X5R(-55to85[deg])/4.30e+01[uF]/6.3[V]
* Murata P/N :GRMJN7R60J436ME05
* Property : C = 4.30e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRMJN7R60J436ME05 Port1 Port2
C01 Port1 N01 3.18e-05
R01 Port1 N01 1.16e+06
L02 N01 N02 1.72e-10
R03 N02 N03 2.42e-03
C04 N03 N04 2.75e-03
R04 N03 N04 9.66e-01
C05 N04 N05 3.12e-03
R05 N04 N05 2.15e-01
C06 N05 N06 2.78e-03
R06 N05 N06 4.53e-02
C07 N06 N07 3.77e-03
R07 N06 N07 8.32e-03
C08 N07 N08 2.33e-03
R08 N07 N08 1.54e-03
L09 N08 N09 4.26e-11
R09 N08 N09 1.18e-01
L10 N09 N10 8.97e-11
R10 N09 N10 2.63e-02
L11 N10 N11 2.57e-10
R11 N10 N11 5.38e-03
L12 N11 N12 1.29e-10
R12 N11 N12 4.33e-03
C13 N12 N13 3.76e-04
L13 N12 N13 2.42e-11
R13 N12 N13 8.63e-04
C14 N13 N14 4.90e-05
L14 N13 N14 8.90e-11
R14 N13 N14 2.15e-03
C15 N14 Port2 1.83e-11
L15 N14 Port2 2.97e-11
R15 N14 Port2 1.85e+00
.ENDS GRMJN7R60J436ME05
