*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1810M(0704)/X5R(-55to85[deg])/2.20e+01[uF]/16[V]
* Murata P/N :GRMJN7R61C226ME05
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRMJN7R61C226ME05 Port1 Port2
C01 Port1 N01 1.55e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 1.76e-10
R03 N02 N03 2.78e-03
C04 N03 N04 8.87e-04
R04 N03 N04 4.57e+00
C05 N04 N05 1.23e-03
R05 N04 N05 4.12e-01
C06 N05 N06 1.35e-03
R06 N05 N06 5.76e-02
C07 N06 N07 2.07e-03
R07 N06 N07 6.72e-03
C08 N07 N08 1.08e-03
R08 N07 N08 2.75e-03
L09 N08 N09 2.40e-11
R09 N08 N09 1.08e-01
L10 N09 N10 5.54e-11
R10 N09 N10 2.90e-02
L11 N10 N11 2.78e-10
R11 N10 N11 1.38e-02
C12 N11 N12 4.04e-05
L12 N11 N12 7.22e-11
R12 N11 N12 2.20e-03
C13 N12 N13 1.77e-05
L13 N12 N13 8.47e-11
R13 N12 N13 3.34e-03
C14 N13 Port2 1.71e-11
L14 N13 Port2 3.38e-11
R14 N13 Port2 2.46e+00
.ENDS GRMJN7R61C226ME05
