*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/X5R(-55to85[deg])/4.70e-02[uF]/4[V]
* Murata P/N :GRM011R60G473ME01
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM011R60G473ME01 Port1 Port2
C01 Port1 N01 3.84e-08
R01 Port1 N01 1.06e+09
L02 N01 N02 9.90e-11
R03 N02 N03 5.18e-02
C04 N03 N04 1.16e-06
R04 N03 N04 4.58e+03
C05 N04 N05 1.50e-06
R05 N04 N05 5.26e+02
C06 N05 N06 1.94e-06
R06 N05 N06 6.47e+01
C07 N06 N07 2.38e-06
R07 N06 N07 7.09e+00
C08 N07 N08 2.16e-06
R08 N07 N08 1.29e+00
C09 N08 N09 1.73e-06
R09 N08 N09 2.97e-01
C10 N09 N10 1.41e-06
R10 N09 N10 6.05e-02
L11 N10 N11 6.90e-12
R11 N10 N11 5.84e-01
L12 N11 N12 1.09e-11
R12 N11 N12 1.74e-01
L13 N12 Port2 4.33e-11
R13 N12 Port2 9.08e-02
.ENDS GRM011R60G473ME01
