*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/X5R(-55to85[deg])/1.00e-02[uF]/4[V]
* Murata P/N :GRM011R60G103KE01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM011R60G103KE01 Port1 Port2
C01 Port1 N01 9.19e-09
R01 Port1 N01 2.00e+09
L02 N01 N02 1.01e-10
R03 N02 N03 6.68e-02
C04 N03 N04 3.82e-07
R04 N03 N04 8.98e+03
C05 N04 N05 8.35e-07
R05 N04 N05 7.30e+02
C06 N05 N06 8.47e-07
R06 N05 N06 1.52e+02
C07 N06 N07 6.91e-07
R07 N06 N07 2.91e+01
C08 N07 N08 6.44e-07
R08 N07 N08 4.71e+00
C09 N08 N09 8.29e-07
R09 N08 N09 7.94e-01
C10 N09 N10 4.21e-07
R10 N09 N10 3.01e-01
C11 N10 N11 2.79e-07
R11 N10 N11 6.60e-02
L12 N11 N12 4.29e-11
R12 N11 N12 1.44e-01
L13 N12 N13 6.32e-12
R13 N12 N13 6.37e-02
C14 N13 Port2 3.67e-10
L14 N13 Port2 8.73e-13
R14 N13 Port2 5.60e-02
.ENDS GRM011R60G103KE01
