*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/X5R(-55to85[deg])/2.20e-03[uF]/6.3[V]
* Murata P/N :GRM011R60J222KE01
* Property : C = 2.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM011R60J222KE01 Port1 Port2
C01 Port1 N01 2.25e-09
R01 Port1 N01 2.00e+09
L02 N01 N02 1.01e-10
R03 N02 N03 1.20e-01
C04 N03 N04 1.06e-07
R04 N03 N04 1.85e+04
C05 N04 N05 1.82e-07
R05 N04 N05 8.27e+02
C06 N05 N06 1.89e-07
R06 N05 N06 7.04e+01
C07 N06 N07 1.49e-07
R07 N06 N07 8.63e+00
C08 N07 N08 1.00e-07
R08 N07 N08 1.26e+00
C09 N08 N09 4.37e-08
R09 N08 N09 1.84e-01
L10 N09 N10 2.41e-11
R10 N09 N10 2.03e-01
C11 N10 Port2 1.69e-10
L11 N10 Port2 1.04e-12
R11 N10 Port2 1.00e-01
.ENDS GRM011R60J222KE01
