*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GCM188R71C105KA64
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R71C105KA64 Port1 Port2
C01 Port1 N01 6.98e-07
R01 Port1 N01 5.00e+08
L02 N01 N02 1.99e-10
R03 N02 N03 7.75e-03
C04 N03 N04 1.26e-05
R04 N03 N04 4.20e+02
C05 N04 N05 2.09e-05
R05 N04 N05 1.95e+01
C06 N05 N06 1.92e-05
R06 N05 N06 2.12e+00
C07 N06 N07 1.63e-05
R07 N06 N07 2.64e-01
C08 N07 N08 1.29e-05
R08 N07 N08 3.88e-02
C09 N08 N09 2.21e-05
R09 N08 N09 3.78e-03
L10 N09 N10 3.16e-11
R10 N09 N10 1.16e-01
L11 N10 N11 1.89e-10
R11 N10 N11 4.29e-02
C12 N11 N12 2.52e-06
L12 N11 N12 3.56e-11
R12 N11 N12 1.15e-02
C13 N12 N13 1.44e-06
L13 N12 N13 3.04e-11
R13 N12 N13 1.30e-02
C14 N13 Port2 3.32e-12
L14 N13 Port2 1.02e-10
R14 N13 Port2 2.68e+01
.ENDS GCM188R71C105KA64
