*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7T(-55to125[deg])/1.00e+00[uF]/50[V]
* Murata P/N :GCM188D71H105KE36
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188D71H105KE36 Port1 Port2
C01 Port1 N01 9.73e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.85e-10
R03 N02 N03 5.61e-03
C04 N03 N04 1.11e-04
R04 N03 N04 2.22e+01
C05 N04 N05 1.29e-04
R05 N04 N05 4.93e+00
C06 N05 N06 1.18e-04
R06 N05 N06 1.04e+00
C07 N06 N07 1.28e-04
R07 N06 N07 1.98e-01
C08 N07 N08 1.07e-04
R08 N07 N08 4.32e-02
C09 N08 N09 6.22e-05
R09 N08 N09 1.10e-02
L10 N09 N10 1.03e-11
R10 N09 N10 1.08e-01
L11 N10 N11 1.80e-11
R11 N10 N11 4.71e-02
L12 N11 N12 1.29e-10
R12 N11 N12 2.61e-02
L13 N12 N13 4.29e-11
R13 N12 N13 1.00e-02
C14 N13 N14 6.38e-06
L14 N13 N14 2.21e-11
R14 N13 N14 9.76e-03
C15 N14 N15 1.05e-06
L15 N14 N15 6.13e-11
R15 N14 N15 1.36e-02
C16 N15 Port2 2.18e-11
L16 N15 Port2 3.18e-11
R16 N15 Port2 4.03e+00
.ENDS GCM188D71H105KE36
