*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/1.50e-03[uF]/50[V]
* Murata P/N :GCM188R11H152KA01
* Property : C = 1.50e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R11H152KA01 Port1 Port2
C01 Port1 N01 1.55e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.88e-10
R03 N02 N03 2.11e-01
C04 N03 N04 1.54e-07
R04 N03 N04 1.33e+04
C05 N04 N05 2.29e-07
R05 N04 N05 6.66e+02
C06 N05 N06 1.84e-07
R06 N05 N06 8.98e+01
C07 N06 N07 1.69e-07
R07 N06 N07 9.63e+00
C08 N07 N08 1.46e-07
R08 N07 N08 1.92e+00
C09 N08 N09 8.17e-08
R09 N08 N09 5.19e-01
C10 N09 N10 2.67e-08
R10 N09 N10 1.87e-01
L11 N10 N11 8.04e-11
R11 N10 N11 8.45e-01
C12 N11 N12 1.15e-08
L12 N11 N12 1.45e-11
R12 N11 N12 1.00e-01
C13 N12 N13 5.29e-12
L13 N12 N13 1.50e-10
R13 N12 N13 1.44e+01
C14 N13 Port2 5.28e-12
L14 N13 Port2 7.34e-11
R14 N13 Port2 1.48e+01
.ENDS GCM188R11H152KA01
