*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/1.50e-02[uF]/25[V]
* Murata P/N :GCM188R11E153KA01
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R11E153KA01 Port1 Port2
C01 Port1 N01 1.51e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.34e-10
R03 N02 N03 5.36e-02
C04 N03 N04 2.05e-06
R04 N03 N04 1.80e+03
C05 N04 N05 2.98e-06
R05 N04 N05 1.80e+02
C06 N05 N06 2.57e-06
R06 N05 N06 2.99e+01
C07 N06 N07 2.61e-06
R07 N06 N07 3.86e+00
C08 N07 N08 2.05e-06
R08 N07 N08 7.72e-01
C09 N08 N09 1.36e-06
R09 N08 N09 1.56e-01
C10 N09 N10 7.38e-07
R10 N09 N10 4.89e-02
L11 N10 N11 9.76e-11
R11 N10 N11 2.75e-01
C12 N11 N12 6.75e-08
L12 N11 N12 2.38e-11
R12 N11 N12 4.00e-02
C13 N12 N13 2.26e-08
L13 N12 N13 3.02e-11
R13 N12 N13 6.43e-02
C14 N13 Port2 3.35e-12
L14 N13 Port2 1.50e-10
R14 N13 Port2 1.50e+01
.ENDS GCM188R11E153KA01
