*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/1.50e-02[uF]/25[V]
* Murata P/N :GCM188R71E153KA37
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R71E153KA37 Port1 Port2
C01 Port1 N01 1.52e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.31e-10
R03 N02 N03 5.27e-02
C04 N03 N04 2.80e-06
R04 N03 N04 1.32e+03
C05 N04 N05 3.48e-06
R05 N04 N05 2.14e+02
C06 N05 N06 2.66e-06
R06 N05 N06 3.63e+01
C07 N06 N07 2.42e-06
R07 N06 N07 4.37e+00
C08 N07 N08 2.07e-06
R08 N07 N08 6.43e-01
C09 N08 N09 1.64e-06
R09 N08 N09 1.17e-01
C10 N09 N10 9.15e-07
R10 N09 N10 4.48e-02
L11 N10 N11 7.77e-11
R11 N10 N11 2.21e-01
C12 N11 N12 9.41e-08
L12 N11 N12 1.73e-11
R12 N11 N12 3.63e-02
C13 N12 N13 1.75e-08
L13 N12 N13 3.62e-11
R13 N12 N13 7.57e-02
C14 N13 N14 1.16e-10
L14 N13 N14 4.28e-11
R14 N13 N14 8.05e-01
C15 N14 Port2 4.24e-12
L15 N14 Port2 9.55e-11
R15 N14 Port2 6.79e+00
.ENDS GCM188R71E153KA37
