*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GCM188R71C105MA49
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R71C105MA49 Port1 Port2
C01 Port1 N01 7.40e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 2.23e-10
R03 N02 N03 7.70e-03
C04 N03 N04 5.36e-06
R04 N03 N04 1.25e+03
C05 N04 N05 1.82e-05
R05 N04 N05 1.91e+01
C06 N05 N06 1.78e-05
R06 N05 N06 1.75e+00
C07 N06 N07 1.39e-05
R07 N06 N07 2.03e-01
C08 N07 N08 1.04e-05
R08 N07 N08 2.32e-02
L09 N08 N09 2.93e-11
R09 N08 N09 1.10e-01
L10 N09 N10 1.74e-10
R10 N09 N10 4.23e-02
C11 N10 N11 3.08e-06
L11 N10 N11 3.06e-11
R11 N10 N11 1.02e-02
C12 N11 N12 9.65e-07
L12 N11 N12 4.54e-11
R12 N11 N12 1.55e-02
C13 N12 Port2 3.80e-12
L13 N12 Port2 8.22e-11
R13 N12 Port2 1.52e+01
.ENDS GCM188R71C105MA49
