*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X8L(-55to150[deg])/4.70e-02[uF]/50[V]
* Murata P/N :GCM188L81H473KA55
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188L81H473KA55 Port1 Port2
C01 Port1 N01 4.70e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.88e-10
R03 N02 N03 1.81e-02
C04 N03 N04 6.49e-06
R04 N03 N04 5.28e+02
C05 N04 N05 1.93e-05
R05 N04 N05 3.49e+01
C06 N05 N06 8.37e-06
R06 N05 N06 1.96e+01
C07 N06 N07 6.73e-06
R07 N06 N07 2.78e+00
C08 N07 N08 5.18e-06
R08 N07 N08 3.53e-01
C09 N08 N09 4.03e-06
R09 N08 N09 5.65e-02
C10 N09 N10 5.72e-06
R10 N09 N10 7.33e-03
L11 N10 N11 1.14e-10
R11 N10 N11 1.17e-01
L12 N11 N12 1.15e-11
R12 N11 N12 9.64e-02
C13 N12 N13 2.44e-07
L13 N12 N13 2.46e-11
R13 N12 N13 2.99e-02
C14 N13 N14 5.85e-08
L14 N13 N14 4.33e-11
R14 N13 N14 5.15e-02
C15 N14 N15 1.35e-11
L15 N14 N15 4.44e-11
R15 N14 N15 5.40e+00
C16 N15 Port2 2.57e-12
L16 N15 Port2 6.22e-11
R16 N15 Port2 8.48e+00
.ENDS GCM188L81H473KA55
