*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/3.30e-02[uF]/25[V]
* Murata P/N :GCM188R11E333KA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R11E333KA01 Port1 Port2
C01 Port1 N01 3.29e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.54e-10
R03 N02 N03 4.08e-02
C04 N03 N04 4.12e-06
R04 N03 N04 8.97e+02
C05 N04 N05 1.46e-05
R05 N04 N05 6.20e+01
C06 N05 N06 6.78e-06
R06 N05 N06 3.26e+01
C07 N06 N07 6.44e-06
R07 N06 N07 5.79e+00
C08 N07 N08 9.85e-06
R08 N07 N08 1.16e+00
C09 N08 N09 3.80e-06
R09 N08 N09 5.23e-01
C10 N09 N10 2.65e-06
R10 N09 N10 8.47e-02
C11 N10 N11 2.75e-06
R11 N10 N11 1.43e-02
L12 N11 N12 9.36e-11
R12 N11 N12 1.86e-01
C13 N12 N13 1.90e-07
L13 N12 N13 2.33e-11
R13 N12 N13 2.21e-02
C14 N13 N14 6.61e-08
L14 N13 N14 1.91e-11
R14 N13 N14 2.84e-02
C15 N14 Port2 4.30e-12
L15 N14 Port2 1.22e-10
R15 N14 Port2 1.09e+01
.ENDS GCM188R11E333KA01
