*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/4.70e-02[uF]/25[V]
* Murata P/N :GCM188R71E473KA37
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R71E473KA37 Port1 Port2
C01 Port1 N01 4.89e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.98e-10
R03 N02 N03 2.62e-02
C04 N03 N04 6.13e-06
R04 N03 N04 6.03e+02
C05 N04 N05 1.53e-05
R05 N04 N05 5.50e+01
C06 N05 N06 8.12e-06
R06 N05 N06 2.00e+01
C07 N06 N07 7.00e-06
R07 N06 N07 2.51e+00
C08 N07 N08 6.78e-06
R08 N07 N08 3.14e-01
C09 N08 N09 5.32e-06
R09 N08 N09 7.44e-02
C10 N09 N10 2.74e-06
R10 N09 N10 1.85e-02
L11 N10 N11 6.00e-11
R11 N10 N11 6.15e-01
L12 N11 N12 9.41e-11
R12 N11 N12 1.04e-01
C13 N12 N13 7.85e-07
L13 N12 N13 7.73e-12
R13 N12 N13 1.14e-02
C14 N13 N14 5.69e-08
L14 N13 N14 4.88e-11
R14 N13 N14 4.29e-02
C15 N14 Port2 4.06e-12
L15 N14 Port2 8.53e-11
R15 N14 Port2 1.29e+01
.ENDS GCM188R71E473KA37
