*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/X7R(-55to125[deg])/2.20e-04[uF]/16[V]
* Murata P/N :GRM022R71C221ME14
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022R71C221ME14 Port1 Port2
C01 Port1 N01 2.15e-10
R01 Port1 N01 2.00e+09
L02 N01 N02 1.52e-10
R03 N02 N03 5.41e-01
C04 N03 N04 1.56e-08
R04 N03 N04 3.55e+05
C05 N04 N05 3.09e-08
R05 N04 N05 1.38e+04
C06 N05 N06 3.00e-08
R06 N05 N06 1.18e+03
C07 N06 N07 2.56e-08
R07 N06 N07 1.29e+02
C08 N07 N08 1.70e-08
R08 N07 N08 2.08e+01
C09 N08 N09 1.11e-08
R09 N08 N09 3.29e+00
C10 N09 N10 2.06e-09
R10 N09 N10 6.84e-01
L11 N10 Port2 2.24e-11
R11 N10 Port2 7.22e-01
.ENDS GRM022R71C221ME14
