*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/4.70e-01[uF]/50[V]
* Murata P/N :GRM31MR71H474KA01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31MR71H474KA01 Port1 Port2
C01 Port1 N01 4.67e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 1.50e-12
R03 N02 N03 7.92e-03
C04 N03 N04 6.70e-05
R04 N03 N04 6.57e+01
C05 N04 N05 7.83e-05
R05 N04 N05 1.04e+01
C06 N05 N06 5.46e-05
R06 N05 N06 1.69e+00
C07 N06 N07 6.40e-05
R07 N06 N07 1.40e-01
C08 N07 N08 6.81e-05
R08 N07 N08 2.34e-02
C09 N08 N09 6.15e-05
R09 N08 N09 4.66e-03
L10 N09 N10 1.88e-11
R10 N09 N10 6.65e-02
L11 N10 N11 2.74e-10
R11 N10 N11 6.03e-02
C12 N11 N12 2.26e-06
L12 N11 N12 4.75e-11
R12 N11 N12 2.17e-02
C13 N12 N13 5.99e-07
L13 N12 N13 7.99e-11
R13 N12 N13 3.00e-02
C14 N13 N14 1.05e-11
L14 N13 N14 8.71e-11
R14 N13 N14 1.41e+01
C15 N14 Port2 1.11e-12
L15 N14 Port2 4.29e-10
R15 N14 Port2 1.15e+02
.ENDS GRM31MR71H474KA01
