*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/B(-25to85[deg])/1.50e-01[uF]/50[V]
* Murata P/N :GRM31MB11H154KA01
* Property : C = 1.50e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31MB11H154KA01 Port1 Port2
C01 Port1 N01 1.53e-07
R01 Port1 N01 3.33e+09
L02 N01 N02 3.05e-11
R03 N02 N03 1.83e-02
C04 N03 N04 1.87e-05
R04 N03 N04 2.13e+02
C05 N04 N05 4.27e-05
R05 N04 N05 1.69e+01
C06 N05 N06 2.87e-05
R06 N05 N06 4.25e+00
C07 N06 N07 2.45e-05
R07 N06 N07 6.74e-01
C08 N07 N08 1.89e-05
R08 N07 N08 1.10e-01
C09 N08 N09 1.61e-05
R09 N08 N09 1.87e-02
C10 N09 N10 1.86e-05
R10 N09 N10 4.79e-03
L11 N10 N11 1.86e-11
R11 N10 N11 1.33e-01
L12 N11 N12 1.74e-10
R12 N11 N12 9.11e-02
C13 N12 N13 7.36e-07
L13 N12 N13 3.56e-11
R13 N12 N13 1.84e-02
C14 N13 N14 2.73e-07
L14 N13 N14 2.67e-11
R14 N13 N14 1.86e-02
C15 N14 N15 2.21e-11
L15 N14 N15 9.20e-11
R15 N14 N15 8.76e+00
C16 N15 Port2 9.73e-13
L16 N15 Port2 4.68e-10
R16 N15 Port2 8.33e+01
.ENDS GRM31MB11H154KA01
