*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X6S(-55to105[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GRM319C81C106MA12
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM319C81C106MA12 Port1 Port2
C01 Port1 N01 7.40e-06
R01 Port1 N01 5.00e+07
L02 N01 N02 7.13e-11
R03 N02 N03 4.82e-03
C04 N03 N04 2.16e-04
R04 N03 N04 2.45e+01
C05 N04 N05 1.86e-04
R05 N04 N05 3.08e+00
C06 N05 N06 1.78e-04
R06 N05 N06 3.36e-01
C07 N06 N07 1.47e-04
R07 N06 N07 4.51e-02
C08 N07 N08 1.39e-04
R08 N07 N08 6.19e-03
L09 N08 N09 1.33e-11
R09 N08 N09 5.74e-02
L10 N09 N10 5.02e-11
R10 N09 N10 4.53e-02
L11 N10 N11 2.67e-10
R11 N10 N11 2.28e-02
C12 N11 N12 2.82e-05
L12 N11 N12 4.53e-11
R12 N11 N12 2.54e-03
C13 N12 N13 4.88e-06
L13 N12 N13 1.12e-10
R13 N12 N13 6.37e-03
C14 N13 N14 2.05e-11
L14 N13 N14 5.40e-11
R14 N13 N14 8.38e+00
C15 N14 Port2 1.32e-12
L15 N14 Port2 2.98e-10
R15 N14 Port2 1.02e+02
.ENDS GRM319C81C106MA12
