*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/3.30e-03[uF]/1000[V]
* Murata P/N :GRM31BR73A332KW01
* Property : C = 3.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31BR73A332KW01 Port1 Port2
C01 Port1 N01 3.31e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.56e-10
R03 N02 N03 1.55e-01
C04 N03 N04 3.57e-07
R04 N03 N04 5.01e+03
C05 N04 N05 4.48e-07
R05 N04 N05 6.64e+02
C06 N05 N06 4.01e-07
R06 N05 N06 1.35e+02
C07 N06 N07 3.65e-07
R07 N06 N07 2.46e+01
C08 N07 N08 2.92e-07
R08 N07 N08 4.70e+00
C09 N08 N09 1.95e-07
R09 N08 N09 1.03e+00
C10 N09 N10 9.05e-08
R10 N09 N10 1.88e-01
L11 N10 N11 7.05e-11
R11 N10 N11 8.84e-01
L12 N11 N12 5.00e-11
R12 N11 N12 4.20e-01
C13 N12 N13 4.23e-08
L13 N12 N13 5.79e-12
R13 N12 N13 4.38e-02
C14 N13 N14 2.46e-09
L14 N13 N14 3.50e-11
R14 N13 N14 2.61e-01
C15 N14 Port2 9.14e-12
L15 N14 Port2 2.89e-10
R15 N14 Port2 1.36e+01
.ENDS GRM31BR73A332KW01
