*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/2.20e+01[uF]/6.3[V]
* Murata P/N :GRM31CR70J226ME19
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CR70J226ME19 Port1 Port2
C01 Port1 N01 1.47e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 1.80e-10
R03 N02 N03 2.70e-03
C04 N03 N04 3.71e-04
R04 N03 N04 1.33e+01
C05 N04 N05 4.92e-04
R05 N04 N05 1.02e+00
C06 N05 N06 4.08e-04
R06 N05 N06 1.38e-01
C07 N06 N07 4.46e-04
R07 N06 N07 1.52e-02
C08 N07 N08 3.07e-04
R08 N07 N08 3.99e-03
L09 N08 N09 2.42e-11
R09 N08 N09 1.34e-01
L10 N09 N10 5.29e-11
R10 N09 N10 6.16e-02
L11 N10 N11 8.29e-11
R11 N10 N11 2.15e-02
L12 N11 N12 5.09e-10
R12 N11 N12 1.22e-02
C13 N12 N13 5.85e-05
L13 N12 N13 7.50e-11
R13 N12 N13 3.31e-03
C14 N13 N14 3.63e-05
L14 N13 N14 6.29e-11
R14 N13 N14 3.33e-03
C15 N14 N15 1.50e-11
L15 N14 N15 7.33e-11
R15 N14 N15 7.21e+00
C16 N15 Port2 2.17e-12
L16 N15 Port2 1.75e-10
R16 N15 Port2 1.11e+02
.ENDS GRM31CR70J226ME19
