*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X6S(-55to105[deg])/6.80e+00[uF]/16[V]
* Murata P/N :GRM31MC81C685MA12
* Property : C = 6.80e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31MC81C685MA12 Port1 Port2
C01 Port1 N01 5.08e-06
R01 Port1 N01 7.35e+06
L02 N01 N02 9.48e-11
R03 N02 N03 4.07e-03
C04 N03 N04 1.68e-04
R04 N03 N04 2.69e+01
C05 N04 N05 1.69e-04
R05 N04 N05 2.89e+00
C06 N05 N06 1.42e-04
R06 N05 N06 4.11e-01
C07 N06 N07 1.14e-04
R07 N06 N07 5.69e-02
C08 N07 N08 9.36e-05
R08 N07 N08 8.13e-03
L09 N08 N09 1.71e-11
R09 N08 N09 8.78e-02
L10 N09 N10 5.30e-11
R10 N09 N10 4.98e-02
L11 N10 N11 3.16e-10
R11 N10 N11 2.52e-02
C12 N11 N12 1.50e-05
L12 N11 N12 7.34e-11
R12 N11 N12 6.44e-03
C13 N12 N13 5.65e-06
L13 N12 N13 8.80e-11
R13 N12 N13 8.46e-03
C14 N13 N14 1.53e-11
L14 N13 N14 5.42e-11
R14 N13 N14 1.07e+01
C15 N14 Port2 1.52e-12
L15 N14 Port2 2.46e-10
R15 N14 Port2 1.01e+02
.ENDS GRM31MC81C685MA12
