*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/6.80e-01[uF]/100[V]
* Murata P/N :GRM31MR72A684KA35
* Property : C = 6.80e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31MR72A684KA35 Port1 Port2
C01 Port1 N01 6.75e-07
R01 Port1 N01 7.35e+08
L02 N01 N02 1.32e-10
R03 N02 N03 6.76e-03
C04 N03 N04 7.31e-05
R04 N03 N04 2.31e-02
C05 N04 N05 8.91e-05
R05 N04 N05 5.79e-03
L06 N05 N06 1.77e-11
R06 N05 N06 8.59e-02
L07 N06 N07 1.84e-10
R07 N06 N07 5.89e-02
C08 N07 N08 1.54e-06
L08 N07 N08 8.78e-11
R08 N07 N08 2.91e-02
C09 N08 N09 5.61e-07
L09 N08 N09 8.40e-11
R09 N08 N09 3.01e-02
C10 N09 Port2 1.68e-12
L10 N09 Port2 2.79e-10
R10 N09 Port2 7.80e+01
.ENDS GRM31MR72A684KA35
