*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/2.20e+01[uF]/16[V]
* Murata P/N :GRM31CZ71C226ME15
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CZ71C226ME15 Port1 Port2
C01 Port1 N01 1.68e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 3.64e-12
R03 N02 N03 2.20e-03
C04 N03 N04 6.94e-04
R04 N03 N04 9.62e+00
C05 N04 N05 9.09e-04
R05 N04 N05 1.04e+00
C06 N05 N06 7.42e-04
R06 N05 N06 1.49e-01
C07 N06 N07 8.88e-04
R07 N06 N07 1.39e-02
C08 N07 N08 6.19e-04
R08 N07 N08 3.97e-03
L09 N08 N09 1.62e-11
R09 N08 N09 3.16e-02
L10 N09 N10 7.70e-11
R10 N09 N10 2.66e-02
L11 N10 N11 5.83e-10
R11 N10 N11 1.16e-02
C12 N11 N12 8.88e-05
L12 N11 N12 5.68e-11
R12 N11 N12 3.62e-03
C13 N12 N13 5.02e-05
L13 N12 N13 5.00e-11
R13 N12 N13 2.95e-03
C14 N13 N14 1.76e-11
L14 N13 N14 7.58e-11
R14 N13 N14 9.89e+00
C15 N14 Port2 8.62e-13
L15 N14 Port2 3.83e-10
R15 N14 Port2 1.70e+02
.ENDS GRM31CZ71C226ME15
