*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/1.50e-02[uF]/250[V]
* Murata P/N :GRM31BR72E153KW01
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31BR72E153KW01 Port1 Port2
C01 Port1 N01 1.52e-08
R01 Port1 N01 6.67e+09
L02 N01 N02 4.50e-10
R03 N02 N03 9.69e-02
C04 N03 N04 1.41e-06
R04 N03 N04 1.49e+03
C05 N04 N05 1.80e-06
R05 N04 N05 2.36e+02
C06 N05 N06 1.53e-06
R06 N05 N06 5.46e+01
C07 N06 N07 1.42e-06
R07 N06 N07 1.08e+01
C08 N07 N08 1.26e-06
R08 N07 N08 2.11e+00
C09 N08 N09 1.07e-06
R09 N08 N09 4.90e-01
C10 N09 N10 6.39e-07
R10 N09 N10 8.39e-02
L11 N10 N11 6.89e-11
R11 N10 N11 2.85e-01
L12 N11 N12 2.91e-11
R12 N11 N12 5.47e-02
C13 N12 N13 7.69e-08
L13 N12 N13 6.83e-12
R13 N12 N13 1.27e-02
C14 N13 Port2 6.18e-12
L14 N13 Port2 4.45e-10
R14 N13 Port2 2.19e+01
.ENDS GRM31BR72E153KW01
