*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X5R(-55to85[deg])/2.20e+01[uF]/25[V]
* Murata P/N :GRM31CR61E226KE15
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CR61E226KE15 Port1 Port2
C01 Port1 N01 1.78e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 7.19e-11
R03 N02 N03 2.04e-03
C04 N03 N04 8.84e-04
R04 N03 N04 6.29e+00
C05 N04 N05 9.43e-04
R05 N04 N05 5.36e-01
C06 N05 N06 8.69e-04
R06 N05 N06 6.07e-02
C07 N06 N07 8.87e-04
R07 N06 N07 5.92e-03
C08 N07 N08 3.77e-04
R08 N07 N08 8.38e-04
L09 N08 N09 6.38e-11
R09 N08 N09 2.87e-02
L10 N09 N10 9.57e-12
R10 N09 N10 2.68e-02
L11 N10 N11 5.33e-10
R11 N10 N11 1.39e-02
C12 N11 N12 6.04e-05
L12 N11 N12 8.25e-11
R12 N11 N12 2.94e-03
C13 N12 N13 2.51e-05
L13 N12 N13 9.23e-11
R13 N12 N13 3.18e-03
C14 N13 N14 1.15e-11
L14 N13 N14 9.41e-11
R14 N13 N14 9.58e+00
C15 N14 Port2 1.31e-12
L15 N14 Port2 3.14e-10
R15 N14 Port2 1.26e+02
.ENDS GRM31CR61E226KE15
