*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/1.00e-01[uF]/200[V]
* Murata P/N :GRM31CR72D104KW03
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CR72D104KW03 Port1 Port2
C01 Port1 N01 1.01e-07
R01 Port1 N01 1.00e+09
L02 N01 N02 4.41e-10
R03 N02 N03 2.02e-02
C04 N03 N04 8.47e-06
R04 N03 N04 2.10e+02
C05 N04 N05 1.05e-05
R05 N04 N05 3.45e+01
C06 N05 N06 8.61e-06
R06 N05 N06 7.59e+00
C07 N06 N07 7.79e-06
R07 N06 N07 1.35e+00
C08 N07 N08 8.53e-06
R08 N07 N08 2.61e-01
C09 N08 N09 6.10e-06
R09 N08 N09 3.71e-02
L10 N09 N10 3.57e-11
R10 N09 N10 3.37e-01
L11 N10 N11 1.41e-10
R11 N10 N11 8.51e-02
C12 N11 N12 7.16e-07
L12 N11 N12 2.63e-11
R12 N11 N12 2.26e-02
C13 N12 N13 1.10e-07
L13 N12 N13 6.80e-11
R13 N12 N13 4.40e-02
C14 N13 Port2 1.23e-11
L14 N13 Port2 1.93e-10
R14 N13 Port2 1.12e+01
.ENDS GRM31CR72D104KW03
