*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/4.70e-03[uF]/1000[V]
* Murata P/N :GRM31BR73A472KW01
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31BR73A472KW01 Port1 Port2
C01 Port1 N01 4.68e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.64e-10
R03 N02 N03 1.19e-01
C04 N03 N04 5.36e-07
R04 N03 N04 3.31e+03
C05 N04 N05 6.73e-07
R05 N04 N05 4.83e+02
C06 N05 N06 5.93e-07
R06 N05 N06 9.98e+01
C07 N06 N07 5.52e-07
R07 N06 N07 1.83e+01
C08 N07 N08 4.71e-07
R08 N07 N08 3.65e+00
C09 N08 N09 3.03e-07
R09 N08 N09 7.53e-01
C10 N09 N10 1.38e-07
R10 N09 N10 1.57e-01
L11 N10 N11 9.55e-11
R11 N10 N11 5.11e-01
L12 N11 N12 7.58e-11
R12 N11 N12 3.70e-01
C13 N12 N13 8.61e-08
L13 N12 N13 6.00e-12
R13 N12 N13 6.02e-02
C14 N13 N14 3.43e-09
L14 N13 N14 4.20e-11
R14 N13 N14 2.28e-01
C15 N14 Port2 1.55e-11
L15 N14 Port2 1.65e-10
R15 N14 Port2 1.11e+01
.ENDS GRM31BR73A472KW01
