*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/R(-55to125[deg])/1.00e+01[uF]/10[V]
* Murata P/N :GRM31CR11A106MA01
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CR11A106MA01 Port1 Port2
C01 Port1 N01 9.52e-06
R01 Port1 N01 5.00e+07
L02 N01 N02 2.38e-10
R03 N02 N03 2.56e-03
C04 N03 N04 1.25e-03
R04 N03 N04 2.64e+00
C05 N04 N05 1.71e-03
R05 N04 N05 3.76e-01
C06 N05 N06 1.17e-03
R06 N05 N06 8.46e-02
C07 N06 N07 1.29e-03
R07 N06 N07 1.12e-02
C08 N07 N08 1.10e-03
R08 N07 N08 2.07e-03
L09 N08 N09 2.31e-11
R09 N08 N09 7.11e-02
L10 N09 N10 6.46e-11
R10 N09 N10 2.72e-02
L11 N10 N11 4.78e-10
R11 N10 N11 1.79e-02
C12 N11 N12 2.96e-05
L12 N11 N12 1.07e-10
R12 N11 N12 5.48e-03
C13 N12 N13 1.78e-05
L13 N12 N13 8.05e-11
R13 N12 N13 5.10e-03
C14 N13 Port2 2.32e-12
L14 N13 Port2 1.47e-10
R14 N13 Port2 1.72e+01
.ENDS GRM31CR11A106MA01
