*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GRM31CR71C106KAC7
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CR71C106KAC7 Port1 Port2
C01 Port1 N01 7.41e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 1.40e-10
R03 N02 N03 3.66e-03
C04 N03 N04 2.33e-04
R04 N03 N04 2.10e+01
C05 N04 N05 3.40e-04
R05 N04 N05 2.46e+00
C06 N05 N06 2.40e-04
R06 N05 N06 5.90e-01
C07 N06 N07 1.92e-04
R07 N06 N07 8.42e-02
C08 N07 N08 1.34e-04
R08 N07 N08 1.28e-02
L09 N08 N09 4.54e-11
R09 N08 N09 4.36e-02
L10 N09 N10 3.70e-10
R10 N09 N10 2.33e-02
C11 N10 N11 2.26e-05
L11 N10 N11 8.85e-11
R11 N10 N11 8.12e-03
C12 N11 N12 1.01e-05
L12 N11 N12 9.30e-11
R12 N11 N12 8.74e-03
C13 N12 N13 1.24e-11
L13 N12 N13 9.84e-11
R13 N12 N13 1.33e+01
C14 N13 Port2 2.04e-12
L14 N13 Port2 2.37e-10
R14 N13 Port2 9.83e+01
.ENDS GRM31CR71C106KAC7
