*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/R(-55to125[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GRM319R11C105KAA3
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM319R11C105KAA3 Port1 Port2
C01 Port1 N01 9.54e-07
R01 Port1 N01 5.00e+08
L02 N01 N02 9.05e-11
R03 N02 N03 6.42e-03
C04 N03 N04 2.00e-04
R04 N03 N04 2.88e+00
C05 N04 N05 1.29e-04
R05 N04 N05 4.51e-01
C06 N05 N06 1.16e-04
R06 N05 N06 5.83e-02
C07 N06 N07 8.25e-05
R07 N06 N07 8.28e-03
L08 N07 N08 2.29e-10
R08 N07 N08 4.04e-02
L09 N08 N09 1.66e-11
R09 N08 N09 2.74e-02
C10 N09 N10 4.99e-06
L10 N09 N10 3.14e-11
R10 N09 N10 7.99e-03
C11 N10 N11 1.21e-06
L11 N10 N11 5.25e-11
R11 N10 N11 1.40e-02
C12 N11 N12 1.48e-11
L12 N11 N12 8.69e-11
R12 N11 N12 1.29e+01
C13 N12 Port2 1.41e-12
L13 N12 Port2 3.97e-10
R13 N12 Port2 8.56e+01
.ENDS GRM319R11C105KAA3
