*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/B(-25to85[deg])/2.20e-01[uF]/25[V]
* Murata P/N :GRM31MB11E224MA01
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31MB11E224MA01 Port1 Port2
C01 Port1 N01 2.20e-07
R01 Port1 N01 2.27e+09
L02 N01 N02 4.24e-11
R03 N02 N03 1.38e-02
C04 N03 N04 2.86e-05
R04 N03 N04 1.94e+02
C05 N04 N05 4.31e-05
R05 N04 N05 1.89e+01
C06 N05 N06 3.37e-05
R06 N05 N06 2.74e+00
C07 N06 N07 4.31e-05
R07 N06 N07 1.93e-01
C08 N07 N08 7.99e-05
R08 N07 N08 1.12e-01
C09 N08 N09 2.42e-05
R09 N08 N09 3.74e-02
C10 N09 N10 1.86e-05
R10 N09 N10 5.24e-03
L11 N10 N11 2.75e-11
R11 N10 N11 7.53e-02
L12 N11 N12 1.71e-10
R12 N11 N12 7.48e-02
C13 N12 N13 1.09e-06
L13 N12 N13 3.43e-11
R13 N12 N13 1.64e-02
C14 N13 N14 1.80e-07
L14 N13 N14 8.36e-11
R14 N13 N14 3.11e-02
C15 N14 N15 2.42e-11
L15 N14 N15 5.67e-11
R15 N14 N15 5.86e+00
C16 N15 Port2 1.08e-12
L16 N15 Port2 4.17e-10
R16 N15 Port2 8.69e+01
.ENDS GRM31MB11E224MA01
