*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/R(-55to125[deg])/4.70e-01[uF]/25[V]
* Murata P/N :GRM319R11E474KA01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM319R11E474KA01 Port1 Port2
C01 Port1 N01 4.60e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 9.40e-11
R03 N02 N03 8.00e-03
C04 N03 N04 4.62e-05
R04 N03 N04 1.12e+02
C05 N04 N05 6.49e-05
R05 N04 N05 1.26e+01
C06 N05 N06 4.57e-05
R06 N05 N06 2.08e+00
C07 N06 N07 5.74e-05
R07 N06 N07 1.77e-01
C08 N07 N08 6.08e-05
R08 N07 N08 3.22e-02
C09 N08 N09 4.22e-05
R09 N08 N09 7.92e-03
C10 N09 N10 1.22e-05
R10 N09 N10 1.49e-03
L11 N10 N11 3.54e-11
R11 N10 N11 5.80e-02
L12 N11 N12 1.85e-10
R12 N11 N12 5.75e-02
C13 N12 N13 3.79e-06
L13 N12 N13 2.31e-11
R13 N12 N13 9.85e-03
C14 N13 N14 3.67e-07
L14 N13 N14 9.65e-11
R14 N13 N14 2.78e-02
C15 N14 N15 1.49e-11
L15 N14 N15 8.31e-11
R15 N14 N15 6.93e+00
C16 N15 Port2 1.38e-12
L16 N15 Port2 4.10e-10
R16 N15 Port2 9.19e+01
.ENDS GRM319R11E474KA01
