*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :5750M(2220)/U2J(-55to125[deg])/5.60e-03[uF]/1000[V]
* Murata P/N :GRM55Q7U3A562JW31
* Property : C = 5.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM55Q7U3A562JW31 Port1 Port2
C01 Port1 N01 5.52e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 3.22e-11
R03 N02 N03 3.63e-03
L04 N03 N04 1.32e-10
R04 N03 N04 4.90e-01
L05 N04 N05 3.31e-11
R05 N04 N05 6.12e-03
C06 N05 N06 7.76e-09
L06 N05 N06 1.00e-10
R06 N05 N06 1.38e+00
C07 N06 N07 5.91e-09
L07 N06 N07 4.47e-11
R07 N06 N07 9.84e-01
C08 N07 N08 1.25e-08
L08 N07 N08 9.16e-12
R08 N07 N08 2.09e-01
C09 N08 N09 6.41e-09
L09 N08 N09 1.04e-11
R09 N08 N09 1.84e-01
C10 N09 Port2 3.98e-12
L10 N09 Port2 3.60e-10
R10 N09 Port2 1.97e+02
.ENDS GRM55Q7U3A562JW31
