*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN36NG80
* Property : L = 36[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN36NG80 port1 port2
C1 port1 port2 2.64e-14
L2 port1 1 3.89e-8
R2 1 port2 3.59e-1
R3 port1 port2 1.42e+4
L4 port1 2 6.26e-7
R4 2 port2 115
L5 port1 3 1.21e-6
R5 3 port2 1.62e+3
L6 port1 4 2.28e-6
C6 4 5 1.70e-16
R6 5 port2 7.03e+3
L7 port1 6 2.02e-6
C7 6 7 6.16e-17
R7 7 port2 6.32e+3
.ENDS LQW15AN36NG80
*----------------------------------------------------------------------
