*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/CH(-55to125[deg])/4.70e-05[uF]/25[V]
* Murata P/N :GRM0222C1E470JA02
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0222C1E470JA02 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.61e-10
R03 N02 N03 1.35e-01
L04 N03 N04 1.19e-11
R04 N03 N04 2.79e-01
C05 N04 Port2 6.99e-11
L05 N04 Port2 7.43e-12
R05 N04 Port2 7.19e-01
.ENDS GRM0222C1E470JA02
