*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/6.20e-06[uF]/50[V]
* Murata P/N :GRM0225C1H6R2WA03
* Property : C = 6.20e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1H6R2WA03 Port1 Port2
C01 Port1 N01 6.20e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.38e-10
R03 N02 N03 1.44e-01
L04 N03 N04 1.20e-11
R04 N03 N04 1.87e-01
C05 N04 N05 1.33e-10
L05 N04 N05 2.81e-12
R05 N04 N05 2.03e-01
C06 N05 N06 7.08e-11
L06 N05 N06 2.11e-12
R06 N05 N06 1.26e+00
C07 N06 N07 1.20e-11
L07 N06 N07 5.58e-12
R07 N06 N07 5.65e+00
C08 N07 N08 3.28e-12
L08 N07 N08 6.66e-12
R08 N07 N08 4.93e+00
C09 N08 Port2 4.55e-12
L09 N08 Port2 2.61e-12
R09 N08 Port2 4.37e+00
.ENDS GRM0225C1H6R2WA03
