*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/9.70e-06[uF]/50[V]
* Murata P/N :GRM0225C1H9R7DA03
* Property : C = 9.70e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1H9R7DA03 Port1 Port2
C01 Port1 N01 9.70e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.37e-10
R03 N02 N03 1.29e-01
L04 N03 N04 1.17e-11
R04 N03 N04 1.80e-01
C05 N04 N05 1.05e-10
L05 N04 N05 3.21e-12
R05 N04 N05 2.54e-01
C06 N05 N06 8.02e-11
L06 N05 N06 2.91e-12
R06 N05 N06 9.39e-01
C07 N06 N07 1.70e-11
L07 N06 N07 5.97e-12
R07 N06 N07 3.90e+00
C08 N07 N08 9.50e-12
L08 N07 N08 3.53e-12
R08 N07 N08 3.71e+00
C09 N08 Port2 5.77e-12
L09 N08 Port2 2.17e-12
R09 N08 Port2 5.11e+00
.ENDS GRM0225C1H9R7DA03
