*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/2.00e-05[uF]/25[V]
* Murata P/N :GRM0225C1E200GA02
* Property : C = 2.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1E200GA02 Port1 Port2
C01 Port1 N01 2.00e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.47e-10
R03 N02 N03 1.85e-01
L04 N03 N04 4.38e-12
R04 N03 N04 9.12e-02
C05 N04 N05 1.35e-09
L05 N04 N05 1.77e-12
R05 N04 N05 6.60e-02
C06 N05 N06 6.65e-11
L06 N05 N06 6.49e-12
R06 N05 N06 5.65e-01
C07 N06 N07 2.86e-11
L07 N06 N07 5.85e-12
R07 N06 N07 1.41e+00
C08 N07 N08 4.68e-11
L08 N07 N08 1.09e-12
R08 N07 N08 7.40e-01
C09 N08 N09 4.90e-12
L09 N08 N09 4.78e-12
R09 N08 N09 2.57e+00
C10 N09 Port2 3.80e-12
L10 N09 Port2 3.23e-12
R10 N09 Port2 4.78e+00
.ENDS GRM0225C1E200GA02
