*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/4.60e-06[uF]/50[V]
* Murata P/N :GRM0225C1H4R6BA03
* Property : C = 4.60e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1H4R6BA03 Port1 Port2
C01 Port1 N01 4.60e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.31e-10
R03 N02 N03 1.60e-01
L04 N03 N04 9.44e-12
R04 N03 N04 7.47e-02
C05 N04 N05 6.45e-11
L05 N04 N05 5.67e-12
R05 N04 N05 2.71e-01
C06 N05 N06 4.69e-11
L06 N05 N06 2.41e-12
R06 N05 N06 1.89e+00
C07 N06 N07 8.84e-12
L07 N06 N07 5.72e-12
R07 N06 N07 8.50e+00
C08 N07 N08 1.92e-11
L08 N07 N08 1.58e-12
R08 N07 N08 2.26e+00
C09 N08 N09 2.06e-12
L09 N08 N09 9.98e-12
R09 N08 N09 2.37e+01
C10 N09 Port2 1.76e-12
L10 N09 Port2 6.75e-12
R10 N09 Port2 8.95e+00
.ENDS GRM0225C1H4R6BA03
