*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/2.00e-07[uF]/25[V]
* Murata P/N :GRM0225C1ER20BA03
* Property : C = 2.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1ER20BA03 Port1 Port2
C01 Port1 N01 2.00e-13
R01 Port1 N01 1.00e+10
L02 N01 N02 1.47e-10
R03 N02 N03 5.41e-01
L04 N03 Port2 1.83e-12
R04 N03 Port2 9.42e-01
.ENDS GRM0225C1ER20BA03
