*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/8.30e-06[uF]/25[V]
* Murata P/N :GRM0225C1E8R3BA03
* Property : C = 8.30e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1E8R3BA03 Port1 Port2
C01 Port1 N01 8.30e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.39e-10
R03 N02 N03 1.37e-01
L04 N03 N04 1.28e-11
R04 N03 N04 3.32e-01
C05 N04 N05 4.08e-10
L05 N04 N05 9.36e-13
R05 N04 N05 1.19e-01
C06 N05 N06 1.08e-10
L06 N05 N06 1.81e-12
R06 N05 N06 8.74e-01
C07 N06 N07 1.35e-11
L07 N06 N07 5.64e-12
R07 N06 N07 4.23e+00
C08 N07 N08 8.58e-12
L08 N07 N08 3.16e-12
R08 N07 N08 3.51e+00
C09 N08 Port2 4.60e-12
L09 N08 Port2 2.74e-12
R09 N08 Port2 4.85e+00
.ENDS GRM0225C1E8R3BA03
