*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/CK(-55to125[deg])/1.40e-06[uF]/25[V]
* Murata P/N :GRM0224C1E1R4CA03
* Property : C = 1.40e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0224C1E1R4CA03 Port1 Port2
C01 Port1 N01 1.40e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.42e-10
R03 N02 N03 3.76e-01
L04 N03 N04 1.00e-11
R04 N03 N04 2.04e-01
C05 N04 N05 2.20e-11
L05 N04 N05 1.76e-12
R05 N04 N05 5.29e+00
C06 N05 N06 3.17e-12
L06 N05 N06 5.63e-12
R06 N05 N06 1.33e+01
C07 N06 Port2 6.63e-12
L07 N06 Port2 1.85e-12
R07 N06 Port2 4.67e+00
.ENDS GRM0224C1E1R4CA03
