*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/1.50e-05[uF]/25[V]
* Murata P/N :GRM0225C1E150JA03
* Property : C = 1.50e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1E150JA03 Port1 Port2
C01 Port1 N01 1.50e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.33e-10
R03 N02 N03 1.66e-01
L04 N03 N04 3.31e-12
R04 N03 N04 5.39e-02
C05 N04 N05 2.45e-09
L05 N04 N05 1.03e-12
R05 N04 N05 4.73e-02
C06 N05 N06 5.61e-11
L06 N05 N06 7.05e-12
R06 N05 N06 8.24e-01
C07 N06 N07 1.99e-11
L07 N06 N07 7.77e-12
R07 N06 N07 2.13e+00
C08 N07 N08 2.92e-11
L08 N07 N08 1.79e-12
R08 N07 N08 1.70e+00
C09 N08 Port2 2.17e-12
L09 N08 Port2 5.51e-12
R09 N08 Port2 4.26e+00
.ENDS GRM0225C1E150JA03
