*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/1.50e-04[uF]/16[V]
* Murata P/N :GRM0225C1C151GA02
* Property : C = 1.50e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1C151GA02 Port1 Port2
C01 Port1 N01 1.50e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.54e-10
R03 N02 N03 8.85e-02
L04 N03 N04 1.45e-11
R04 N03 N04 1.37e-01
C05 N04 N05 1.01e-09
L05 N04 N05 3.52e-12
R05 N04 N05 1.01e-01
C06 N05 N06 1.88e-10
L06 N05 N06 9.53e-12
R06 N05 N06 3.25e-01
C07 N06 Port2 4.95e-11
L07 N06 Port2 7.68e-12
R07 N06 Port2 6.33e-01
.ENDS GRM0225C1C151GA02
