*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/CK(-55to125[deg])/5.00e-07[uF]/50[V]
* Murata P/N :GRM0224C1HR50WA03
* Property : C = 5.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0224C1HR50WA03 Port1 Port2
C01 Port1 N01 5.00e-13
R01 Port1 N01 1.00e+10
L02 N01 N02 1.37e-10
R03 N02 N03 4.73e-01
L04 N03 N04 6.70e-13
R04 N03 N04 2.10e-01
C05 N04 Port2 3.97e-12
L05 N04 Port2 3.92e-12
R05 N04 Port2 1.93e+01
.ENDS GRM0224C1HR50WA03
