*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/7.00e-06[uF]/50[V]
* Murata P/N :GRM0225C1H7R0BA03
* Property : C = 7.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1H7R0BA03 Port1 Port2
C01 Port1 N01 7.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.40e-10
R03 N02 N03 1.41e-01
L04 N03 N04 1.14e-11
R04 N03 N04 1.79e-01
C05 N04 N05 1.13e-10
L05 N04 N05 3.17e-12
R05 N04 N05 2.15e-01
C06 N05 N06 8.64e-11
L06 N05 N06 1.92e-12
R06 N05 N06 1.05e+00
C07 N06 N07 1.36e-11
L07 N06 N07 5.06e-12
R07 N06 N07 5.52e+00
C08 N07 N08 3.28e-12
L08 N07 N08 6.73e-12
R08 N07 N08 6.09e+00
C09 N08 Port2 4.58e-12
L09 N08 Port2 2.57e-12
R09 N08 Port2 6.07e+00
.ENDS GRM0225C1H7R0BA03
