*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/C0G(-55to125[deg])/3.10e-06[uF]/50[V]
* Murata P/N :GRM0225C1H3R1BA03
* Property : C = 3.10e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0225C1H3R1BA03 Port1 Port2
C01 Port1 N01 3.10e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.47e-10
R03 N02 N03 1.99e-01
L04 N03 N04 1.55e-11
R04 N03 N04 3.90e-01
C05 N04 N05 4.38e-11
L05 N04 N05 1.57e-12
R05 N04 N05 2.47e+00
C06 N05 N06 5.19e-12
L06 N05 N06 6.13e-12
R06 N05 N06 1.19e+01
C07 N06 Port2 1.47e-12
L07 N06 Port2 8.02e-12
R07 N06 Port2 9.43e+00
.ENDS GRM0225C1H3R1BA03
