*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/CH(-55to125[deg])/9.40e-06[uF]/25[V]
* Murata P/N :GRM0222C1E9R4BA03
* Property : C = 9.40e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0222C1E9R4BA03 Port1 Port2
C01 Port1 N01 9.40e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.34e-10
R03 N02 N03 1.31e-01
L04 N03 N04 1.22e-11
R04 N03 N04 2.29e-01
C05 N04 N05 2.38e-10
L05 N04 N05 1.66e-12
R05 N04 N05 1.79e-01
C06 N05 N06 7.33e-11
L06 N05 N06 3.12e-12
R06 N05 N06 1.01e+00
C07 N06 N07 1.59e-11
L07 N06 N07 6.29e-12
R07 N06 N07 4.04e+00
C08 N07 N08 8.89e-12
L08 N07 N08 3.68e-12
R08 N07 N08 4.09e+00
C09 N08 N09 1.05e-11
L09 N08 N09 2.01e-12
R09 N08 N09 4.68e+00
C10 N09 Port2 2.90e-12
L10 N09 Port2 4.06e-12
R10 N09 Port2 8.34e+00
.ENDS GRM0222C1E9R4BA03
