*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/X7T(-55to125[deg])/1.00e+00[uF]/2.5[V]
* Murata P/N :GCM033D70E105ME35
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM033D70E105ME35 Port1 Port2
C01 Port1 N01 8.97e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.16e-10
R03 N02 N03 6.65e-03
C04 N03 N04 7.90e-05
R04 N03 N04 6.71e+01
C05 N04 N05 8.55e-05
R05 N04 N05 9.65e+00
C06 N05 N06 8.19e-05
R06 N05 N06 1.62e+00
C07 N06 N07 8.37e-05
R07 N06 N07 2.36e-01
C08 N07 N08 7.96e-05
R08 N07 N08 3.76e-02
C09 N08 N09 1.29e-04
R09 N08 N09 5.64e-03
C10 N09 N10 5.73e-05
R10 N09 N10 5.31e-03
L11 N10 N11 8.24e-12
R11 N10 N11 6.11e-01
L12 N11 N12 9.47e-12
R12 N11 N12 9.13e-02
L13 N12 N13 1.81e-11
R13 N12 N13 3.15e-02
L14 N13 N14 9.27e-11
R14 N13 N14 2.26e-02
C15 N14 N15 4.64e-06
L15 N14 N15 1.41e-11
R15 N14 N15 3.35e-03
C16 N15 Port2 2.22e-06
L16 N15 Port2 1.48e-11
R16 N15 Port2 4.77e-03
.ENDS GCM033D70E105ME35
