*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/X7R(-55to125[deg])/2.20e-03[uF]/16[V]
* Murata P/N :GCM033R71C222KA55
* Property : C = 2.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM033R71C222KA55 Port1 Port2
C01 Port1 N01 2.22e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.05e-10
R03 N02 N03 1.40e-01
C04 N03 N04 2.30e-07
R04 N03 N04 1.20e+04
C05 N04 N05 3.95e-07
R05 N04 N05 1.31e+03
C06 N05 N06 2.66e-07
R06 N05 N06 2.23e+02
C07 N06 N07 2.32e-07
R07 N06 N07 2.18e+01
C08 N07 N08 1.89e-07
R08 N07 N08 2.62e+00
C09 N08 N09 1.07e-07
R09 N08 N09 4.94e-01
C10 N09 N10 9.32e-08
R10 N09 N10 5.69e-02
L11 N10 N11 4.65e-11
R11 N10 N11 3.89e-01
C12 N11 Port2 6.52e-12
L12 N11 Port2 3.74e-11
R12 N11 Port2 7.61e+00
.ENDS GCM033R71C222KA55
