*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN14NJ80
* Property : L = 14[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN14NJ80 port1 port2
C1 port1 port2 3.56e-14
L2 port1 1 1.50e-8
R2 1 port2 9.20e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.53e-7
R4 2 port2 37.2
L5 port1 3 6.20e-7
R5 3 port2 1.70e+3
L6 port1 4 2.28e-6
C6 4 5 6.45e-17
R6 5 port2 7.03e+3
.ENDS LQW15AN14NJ80
*----------------------------------------------------------------------
