*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/1.50e-02[uF]/50[V]
* Murata P/N :GCM155R71H153KA40
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R71H153KA40 Port1 Port2
C01 Port1 N01 1.51e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.99e-10
R03 N02 N03 4.55e-02
C04 N03 N04 1.69e-06
R04 N03 N04 2.36e+03
C05 N04 N05 3.56e-06
R05 N04 N05 2.15e+02
C06 N05 N06 1.89e-06
R06 N05 N06 7.45e+01
C07 N06 N07 1.76e-06
R07 N06 N07 7.80e+00
C08 N07 N08 1.39e-06
R08 N07 N08 9.76e-01
C09 N08 N09 1.03e-06
R09 N08 N09 1.56e-01
C10 N09 N10 9.30e-07
R10 N09 N10 2.60e-02
L11 N10 N11 6.21e-11
R11 N10 N11 1.77e-01
C12 N11 N12 3.75e-07
L12 N11 N12 2.98e-12
R12 N11 N12 1.00e-02
C13 N12 N13 1.84e-08
L13 N12 N13 2.73e-11
R13 N12 N13 4.64e-02
C14 N13 Port2 3.27e-12
L14 N13 Port2 8.81e-11
R14 N13 Port2 1.19e+01
.ENDS GCM155R71H153KA40
