*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8L(-55to150[deg])/2.20e-02[uF]/16[V]
* Murata P/N :GCM155L81C223KA37
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155L81C223KA37 Port1 Port2
C01 Port1 N01 2.20e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.05e-10
R03 N02 N03 4.34e-02
C04 N03 N04 2.84e-06
R04 N03 N04 1.40e+03
C05 N04 N05 6.57e-06
R05 N04 N05 1.28e+02
C06 N05 N06 3.30e-06
R06 N05 N06 3.95e+01
C07 N06 N07 3.05e-06
R07 N06 N07 4.76e+00
C08 N07 N08 2.78e-06
R08 N07 N08 6.28e-01
C09 N08 N09 2.10e-06
R09 N08 N09 1.17e-01
C10 N09 N10 1.02e-06
R10 N09 N10 2.95e-02
L11 N10 N11 7.05e-11
R11 N10 N11 1.52e-01
C12 N11 N12 3.36e-08
L12 N11 N12 2.66e-11
R12 N11 N12 3.16e-02
C13 N12 Port2 3.84e-12
L13 N12 Port2 8.53e-11
R13 N12 Port2 1.22e+01
.ENDS GCM155L81C223KA37
