*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/1.50e-01[uF]/16[V]
* Murata P/N :GCM155R71C154KE02
* Property : C = 1.50e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R71C154KE02 Port1 Port2
C01 Port1 N01 9.16e-08
R01 Port1 N01 3.33e+08
L02 N01 N02 1.84e-10
R03 N02 N03 2.46e-02
C04 N03 N04 3.26e-06
R04 N03 N04 1.22e+03
C05 N04 N05 3.94e-06
R05 N04 N05 1.47e+02
C06 N05 N06 3.75e-06
R06 N05 N06 1.93e+01
C07 N06 N07 5.48e-06
R07 N06 N07 3.14e+00
C08 N07 N08 2.54e-06
R08 N07 N08 1.14e+00
C09 N08 N09 1.79e-06
R09 N08 N09 1.54e-01
C10 N09 N10 1.49e-06
R10 N09 N10 2.59e-02
L11 N10 N11 2.48e-11
R11 N10 N11 1.50e-01
L12 N11 N12 7.62e-11
R12 N11 N12 7.44e-02
C13 N12 N13 8.03e-08
L13 N12 N13 4.03e-11
R13 N12 N13 2.42e-02
C14 N13 Port2 3.75e-12
L14 N13 Port2 9.74e-11
R14 N13 Port2 1.58e+01
.ENDS GCM155R71C154KE02
