*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/3.30e-04[uF]/100[V]
* Murata P/N :GCM155R72A331KA01
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R72A331KA01 Port1 Port2
C01 Port1 N01 3.25e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.07e-10
R03 N02 N03 4.60e-01
C04 N03 N04 4.61e-08
R04 N03 N04 1.08e+05
C05 N04 N05 4.62e-08
R05 N04 N05 1.46e+04
C06 N05 N06 4.70e-08
R06 N05 N06 1.21e+03
C07 N06 N07 4.09e-08
R07 N06 N07 1.27e+02
C08 N07 N08 3.34e-08
R08 N07 N08 1.59e+01
C09 N08 N09 2.32e-08
R09 N08 N09 2.98e+00
C10 N09 N10 8.11e-09
R10 N09 N10 1.12e+00
C11 N10 N11 1.70e-09
R11 N10 N11 6.47e-01
C12 N11 N12 2.20e-10
L12 N11 N12 2.38e-11
R12 N11 N12 3.52e-01
C13 N12 Port2 1.45e-12
L13 N12 Port2 2.42e-10
R13 N12 Port2 2.38e+01
.ENDS GCM155R72A331KA01
