*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7S(-55to125[deg])/6.80e-01[uF]/10[V]
* Murata P/N :GCM155C71A684KE39
* Property : C = 6.80e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155C71A684KE39 Port1 Port2
C01 Port1 N01 5.21e-07
R01 Port1 N01 7.35e+07
L02 N01 N02 1.92e-10
R03 N02 N03 2.01e-02
C04 N03 N04 2.09e-05
R04 N03 N04 1.90e+02
C05 N04 N05 2.83e-05
R05 N04 N05 1.90e+01
C06 N05 N06 2.35e-05
R06 N05 N06 2.23e+00
C07 N06 N07 1.99e-05
R07 N06 N07 2.45e-01
C08 N07 N08 1.34e-05
R08 N07 N08 3.06e-02
L09 N08 N09 3.14e-11
R09 N08 N09 2.84e-01
L10 N09 N10 2.97e-11
R10 N09 N10 5.92e-02
L11 N10 N11 1.02e-10
R11 N10 N11 3.64e-02
C12 N11 N12 1.70e-06
L12 N11 N12 3.65e-11
R12 N11 N12 3.12e-03
C13 N12 N13 5.14e-07
L13 N12 N13 3.52e-11
R13 N12 N13 5.37e-03
C14 N13 Port2 9.14e-12
L14 N13 Port2 4.15e-11
R14 N13 Port2 7.66e+00
.ENDS GCM155C71A684KE39
