*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :4520M(1808)/U2J(-55to125[deg])/4.70e-05[uF]/3150[V]
* Murata P/N :GRM42A7U3F470JW31
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM42A7U3F470JW31 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 5.00e-12
R03 N02 N03 1.47e-01
C04 N03 N04 7.89e-11
L04 N03 N04 3.92e-11
R04 N03 N04 3.26e+00
C05 N04 Port2 1.22e-12
L05 N04 Port2 9.37e-10
R05 N04 Port2 4.21e+02
.ENDS GRM42A7U3F470JW31
