*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN9N3H00
* Property : L = 9.3[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN9N3H00 port1 port2
C1 port1 port2 4.03e-14
L2 port1 1 9.60e-9
R2 1 port2 1.00e-1
R3 port1 port2 1.43e+4
L4 port1 2 1.49e-7
R4 2 port2 46.7
L5 port1 3 3.85e-7
R5 3 port2 1.43e+3
.ENDS LQW15AN9N3H00
*----------------------------------------------------------------------
