*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN8N3D10
* Property : L = 8.3[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN8N3D10 port1 port2
C1 port1 port2 3.98e-14
L2 port1 1 8.24e-9
R2 1 port2 5.60e-2
R3 port1 port2 1.80e+4
L4 port1 2 2.46e-7
R4 2 port2 51.4
L5 port1 3 2.69e-7
R5 3 port2 686
L6 port1 4 2.38e-6
C6 4 5 3.23e-17
R6 5 port2 1.83e+3
.ENDS LQW15AN8N3D10
*----------------------------------------------------------------------
