*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/2.20e-04[uF]/100[V]
* Murata P/N :GRM1555C2A221JE01
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C2A221JE01 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.92e-10
R03 N02 N03 9.10e-02
L04 N03 N04 5.45e-11
R04 N03 N04 4.05e+00
L05 N04 N05 3.76e-11
R05 N04 N05 7.23e-01
C06 N05 N06 4.61e-09
L06 N05 N06 3.16e-12
R06 N05 N06 1.79e-01
C07 N06 N07 4.21e-10
L07 N06 N07 1.38e-11
R07 N06 N07 6.08e-01
C08 N07 Port2 5.64e-11
L08 N07 Port2 4.85e-12
R08 N07 Port2 7.00e-01
.ENDS GRM1555C2A221JE01
