*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/UJ(-25to85[deg])/1.50e-03[uF]/10[V]
* Murata P/N :GRM1553U1A152JA01
* Property : C = 1.50e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1553U1A152JA01 Port1 Port2
C01 Port1 N01 1.47e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.15e-10
R03 N02 N03 2.24e-02
L04 N03 N04 5.67e-11
R04 N03 N04 6.78e-01
L05 N04 N05 7.41e-11
R05 N04 N05 3.87e-02
C06 N05 N06 1.77e-08
L06 N05 N06 6.57e-12
R06 N05 N06 8.97e-02
C07 N06 N07 2.60e-09
L07 N06 N07 1.97e-11
R07 N06 N07 2.79e-01
C08 N07 Port2 3.95e-12
L08 N07 Port2 7.57e-11
R08 N07 Port2 3.53e+01
.ENDS GRM1553U1A152JA01
