*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/8.20e-03[uF]/50[V]
* Murata P/N :GRM1555C1H822GE01
* Property : C = 8.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H822GE01 Port1 Port2
C01 Port1 N01 8.06e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.00e-10
R03 N02 N03 2.81e-03
L04 N03 N04 4.26e-11
R04 N03 N04 1.82e-01
L05 N04 N05 1.91e-11
R05 N04 N05 1.16e-02
L06 N05 N06 8.66e-11
R06 N05 N06 8.53e-03
L07 N06 N07 1.31e-10
R07 N06 N07 1.41e-03
C08 N07 N08 3.10e-08
L08 N07 N08 2.11e-11
R08 N07 N08 1.65e-01
C09 N08 N09 1.50e-08
L09 N08 N09 2.01e-11
R09 N08 N09 2.05e-01
C10 N09 N10 5.04e-08
L10 N09 N10 3.04e-12
R10 N09 N10 4.39e-02
C11 N10 N11 1.29e-08
L11 N10 N11 7.33e-12
R11 N10 N11 8.77e-02
C12 N11 Port2 1.74e-11
L12 N11 Port2 1.71e-11
R12 N11 Port2 7.44e+00
.ENDS GRM1555C1H822GE01
