*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/1.00e-03[uF]/25[V]
* Murata P/N :GRM1555C1E102JA01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1E102JA01 Port1 Port2
C01 Port1 N01 9.93e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 9.26e-11
R03 N02 N03 1.46e-02
L04 N03 N04 1.36e-10
R04 N03 N04 2.95e-02
C05 N04 N05 5.86e-09
L05 N04 N05 1.40e-11
R05 N04 N05 2.91e-01
C06 N05 N06 1.79e-09
L06 N05 N06 2.06e-11
R06 N05 N06 4.45e-01
C07 N06 N07 2.01e-12
L07 N06 N07 1.29e-10
R07 N06 N07 1.00e+05
C08 N07 Port2 6.84e-13
L08 N07 Port2 6.98e-11
R08 N07 Port2 9.47e-01
.ENDS GRM1555C1E102JA01
