*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/SL(-55to125[deg])/2.20e-03[uF]/10[V]
* Murata P/N :GRM1551X1A222JA01
* Property : C = 2.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1551X1A222JA01 Port1 Port2
C01 Port1 N01 2.22e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.00e-10
R03 N02 N03 2.09e-02
L04 N03 N04 7.81e-11
R04 N03 N04 1.89e-01
L05 N04 N05 4.48e-11
R05 N04 N05 6.19e-03
C06 N05 N06 4.82e-07
L06 N05 N06 3.62e-13
R06 N05 N06 3.05e-02
C07 N06 N07 4.58e-09
L07 N06 N07 1.56e-11
R07 N06 N07 1.60e-01
C08 N07 N08 1.10e-11
L08 N07 N08 2.70e-11
R08 N07 N08 7.73e-01
C09 N08 Port2 1.75e-12
L09 N08 Port2 1.26e-10
R09 N08 Port2 1.00e+05
.ENDS GRM1551X1A222JA01
