*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/4.70e-05[uF]/100[V]
* Murata P/N :GRM1555C2A470JA01
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C2A470JA01 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 7.48e-11
R03 N02 N03 1.00e-01
L04 N03 N04 1.30e-11
R04 N03 N04 1.44e-01
C05 N04 N05 3.94e-10
L05 N04 N05 1.00e-11
R05 N04 N05 9.37e-01
C06 N05 N06 7.38e-11
L06 N05 N06 1.73e-11
R06 N05 N06 1.86e+00
C07 N06 N07 1.34e-11
L07 N06 N07 2.64e-11
R07 N06 N07 2.96e+00
C08 N07 Port2 8.21e-13
L08 N07 Port2 2.00e-10
R08 N07 Port2 1.00e+05
.ENDS GRM1555C2A470JA01
