*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/3.00e-05[uF]/50[V]
* Murata P/N :GRM1555C1H300JA01
* Property : C = 3.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H300JA01 Port1 Port2
C01 Port1 N01 3.00e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.88e-10
R03 N02 N03 1.15e-01
L04 N03 N04 2.41e-11
R04 N03 N04 2.48e-01
C05 N04 N05 3.78e-10
L05 N04 N05 5.80e-12
R05 N04 N05 5.25e-01
C06 N05 N06 3.74e-11
L06 N05 N06 1.61e-11
R06 N05 N06 1.99e+00
C07 N06 N07 5.32e-11
L07 N06 N07 6.26e-12
R07 N06 N07 1.58e+00
C08 N07 Port2 1.39e-12
L08 N07 Port2 1.24e-10
R08 N07 Port2 1.00e+05
.ENDS GRM1555C1H300JA01
