*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/3.30e-04[uF]/100[V]
* Murata P/N :GRM1555C2A331JE01
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C2A331JE01 Port1 Port2
C01 Port1 N01 3.30e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.89e-10
R03 N02 N03 3.48e-02
L04 N03 N04 5.97e-11
R04 N03 N04 9.22e-01
L05 N04 N05 1.05e-10
R05 N04 N05 2.58e-02
C06 N05 N06 9.57e-08
L06 N05 N06 6.49e-12
R06 N05 N06 1.23e-02
C07 N06 N07 4.07e-09
L07 N06 N07 6.29e-12
R07 N06 N07 2.51e-01
C08 N07 Port2 7.10e-10
L08 N07 Port2 1.58e-11
R08 N07 Port2 6.24e-01
.ENDS GRM1555C2A331JE01
