*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/9.10e-05[uF]/50[V]
* Murata P/N :GRM1552C1H910JA01
* Property : C = 9.10e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1552C1H910JA01 Port1 Port2
C01 Port1 N01 9.10e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.65e-10
R03 N02 N03 1.05e-01
L04 N03 N04 1.59e-11
R04 N03 N04 9.89e-02
C05 N04 N05 1.01e-09
L05 N04 N05 5.88e-12
R05 N04 N05 3.74e-01
C06 N05 N06 1.23e-10
L06 N05 N06 1.90e-11
R06 N05 N06 1.16e+00
C07 N06 N07 8.39e-12
L07 N06 N07 3.87e-11
R07 N06 N07 2.87e+00
C08 N07 Port2 1.85e-12
L08 N07 Port2 1.34e-10
R08 N07 Port2 1.00e+05
.ENDS GRM1552C1H910JA01
