*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CK(-55to125[deg])/1.80e-06[uF]/100[V]
* Murata P/N :GRM1554C2A1R8BA01
* Property : C = 1.80e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1554C2A1R8BA01 Port1 Port2
C01 Port1 N01 1.80e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 2.57e-10
R03 N02 N03 4.20e-01
C04 N03 N04 1.70e-11
L04 N03 N04 1.80e-11
R04 N03 N04 3.70e+00
C05 N04 Port2 6.87e-12
L05 N04 Port2 4.01e-11
R05 N04 Port2 1.00e+05
.ENDS GRM1554C2A1R8BA01
