*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/4.70e-04[uF]/50[V]
* Murata P/N :GRM1552C1H471GA01
* Property : C = 4.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1552C1H471GA01 Port1 Port2
C01 Port1 N01 4.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.78e-10
R03 N02 N03 5.20e-02
L04 N03 N04 3.64e-11
R04 N03 N04 4.09e-01
L05 N04 N05 2.96e-11
R05 N04 N05 3.72e-01
C06 N05 N06 5.30e-09
L06 N05 N06 7.26e-12
R06 N05 N06 2.25e-01
C07 N06 N07 1.09e-09
L07 N06 N07 1.61e-11
R07 N06 N07 4.96e-01
C08 N07 Port2 2.49e-12
L08 N07 Port2 8.90e-11
R08 N07 Port2 1.00e+05
.ENDS GRM1552C1H471GA01
