*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/2.70e-04[uF]/50[V]
* Murata P/N :GRM1552C1H271JA01
* Property : C = 2.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1552C1H271JA01 Port1 Port2
C01 Port1 N01 2.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.22e-10
R03 N02 N03 8.50e-02
L04 N03 N04 5.93e-11
R04 N03 N04 1.31e+00
L05 N04 N05 3.37e-12
R05 N04 N05 8.32e-03
C06 N05 N06 4.11e-09
L06 N05 N06 4.87e-12
R06 N05 N06 1.41e-01
C07 N06 N07 6.03e-10
L07 N06 N07 1.31e-11
R07 N06 N07 4.84e-01
C08 N07 N08 2.44e-11
L08 N07 N08 1.54e-11
R08 N07 N08 3.82e+00
C09 N08 Port2 1.39e-12
L09 N08 Port2 1.79e-10
R09 N08 Port2 1.00e+05
.ENDS GRM1552C1H271JA01
