*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/8.00e-07[uF]/100[V]
* Murata P/N :GRM1555C2AR80BA01
* Property : C = 8.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-20[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C2AR80BA01 Port1 Port2
C01 Port1 N01 8.00e-13
R01 Port1 N01 1.00e+10
L02 N01 N02 3.16e-10
R03 N02 N03 7.64e-01
C04 N03 N04 1.34e-12
L04 N03 N04 4.41e-11
R04 N03 N04 3.17e+01
C05 N04 Port2 4.34e-13
L05 N04 Port2 1.07e-10
R05 N04 Port2 1.00e+08
.ENDS GRM1555C2AR80BA01
