*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/2.20e-04[uF]/50[V]
* Murata P/N :GRM1552C1H221GA01
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1552C1H221GA01 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.72e-10
R03 N02 N03 9.00e-02
L04 N03 N04 5.37e-11
R04 N03 N04 1.06e+00
C05 N04 N05 2.16e-09
L05 N04 N05 6.41e-12
R05 N04 N05 1.87e-01
C06 N05 N06 4.14e-10
L06 N05 N06 1.36e-11
R06 N05 N06 5.70e-01
C07 N06 N07 5.54e-11
L07 N06 N07 5.97e-12
R07 N06 N07 3.61e-01
C08 N07 Port2 2.85e-12
L08 N07 Port2 8.91e-11
R08 N07 Port2 5.66e+08
.ENDS GRM1552C1H221GA01
