*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/7.00e-06[uF]/50[V]
* Murata P/N :GRM1555C1H7R0CA01
* Property : C = 7.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H7R0CA01 Port1 Port2
C01 Port1 N01 7.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 2.23e-10
R03 N02 N03 2.00e-01
L04 N03 N04 2.29e-11
R04 N03 N04 3.39e-01
C05 N04 N05 1.27e-10
L05 N04 N05 4.41e-12
R05 N04 N05 1.12e+00
C06 N05 N06 7.05e-11
L06 N05 N06 5.00e-12
R06 N05 N06 1.61e+00
C07 N06 Port2 3.34e-12
L07 N06 Port2 7.34e-11
R07 N06 Port2 1.00e+05
.ENDS GRM1555C1H7R0CA01
