*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/3.60e-04[uF]/50[V]
* Murata P/N :GRM1555C1H361JA01
* Property : C = 3.60e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H361JA01 Port1 Port2
C01 Port1 N01 3.60e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.52e-10
R03 N02 N03 6.50e-02
L04 N03 N04 2.44e-11
R04 N03 N04 6.41e-01
L05 N04 N05 1.04e-11
R05 N04 N05 3.27e-02
C06 N05 N06 7.26e-10
L06 N05 N06 1.67e-11
R06 N05 N06 5.46e-01
C07 N06 N07 5.73e-10
L07 N06 N07 6.31e-12
R07 N06 N07 2.26e-01
C08 N07 Port2 7.33e-12
L08 N07 Port2 3.74e-11
R08 N07 Port2 2.64e+01
.ENDS GRM1555C1H361JA01
