*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/1.20e-03[uF]/50[V]
* Murata P/N :GRM1555C1H122GA01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H122GA01 Port1 Port2
C01 Port1 N01 1.18e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.94e-10
R03 N02 N03 6.67e-03
L04 N03 N04 2.99e-11
R04 N03 N04 4.16e-01
L05 N04 N05 2.56e-11
R05 N04 N05 3.10e-02
L06 N05 N06 9.58e-11
R06 N05 N06 1.85e-02
L07 N06 N07 2.10e-10
R07 N06 N07 4.02e-03
C08 N07 N08 1.60e-08
L08 N07 N08 5.45e-12
R08 N07 N08 1.14e-01
C09 N08 N09 2.16e-09
L09 N08 N09 1.82e-11
R09 N08 N09 3.55e-01
C10 N09 N10 1.06e-09
L10 N09 N10 1.11e-11
R10 N09 N10 1.73e-01
C11 N10 Port2 2.13e-12
L11 N10 Port2 9.71e-11
R11 N10 Port2 8.87e+01
.ENDS GRM1555C1H122GA01
