*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/UJ(-25to85[deg])/1.80e-03[uF]/10[V]
* Murata P/N :GRM1553U1A182JA01
* Property : C = 1.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1553U1A182JA01 Port1 Port2
C01 Port1 N01 1.76e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.37e-10
R03 N02 N03 1.12e-02
L04 N03 N04 6.07e-11
R04 N03 N04 4.28e-01
L05 N04 N05 5.27e-11
R05 N04 N05 2.29e-02
L06 N05 N06 1.00e-10
R06 N05 N06 6.06e-03
C07 N06 N07 2.17e-08
L07 N06 N07 6.67e-12
R07 N06 N07 1.19e-01
C08 N07 N08 3.15e-09
L08 N07 N08 2.08e-11
R08 N07 N08 2.87e-01
C09 N08 Port2 7.33e-12
L09 N08 Port2 3.98e-11
R09 N08 Port2 1.83e+01
.ENDS GRM1553U1A182JA01
