*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/1.00e+01[uF]/25[V]
* Murata P/N :GRM32DR71E106KA12
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32DR71E106KA12 Port1 Port2
C01 Port1 N01 9.71e-06
R01 Port1 N01 5.00e+07
L02 N01 N02 5.63e-11
R03 N02 N03 1.58e-03
C04 N03 N04 7.02e-04
R04 N03 N04 9.74e+00
C05 N04 N05 1.23e-03
R05 N04 N05 3.93e-01
C06 N05 N06 1.01e-03
R06 N05 N06 5.17e-02
C07 N06 N07 9.23e-04
R07 N06 N07 4.71e-03
C08 N07 N08 6.42e-04
R08 N07 N08 6.33e-04
L09 N08 N09 3.44e-11
R09 N08 N09 3.11e-02
L10 N09 N10 3.94e-10
R10 N09 N10 1.75e-02
C11 N10 N11 2.01e-05
L11 N10 N11 1.02e-10
R11 N10 N11 9.19e-03
C12 N11 N12 9.86e-06
L12 N11 N12 8.68e-11
R12 N11 N12 7.67e-03
C13 N12 N13 1.50e-11
L13 N12 N13 7.50e-11
R13 N12 N13 7.40e+00
C14 N13 Port2 2.10e-12
L14 N13 Port2 1.87e-10
R14 N13 Port2 1.40e+02
.ENDS GRM32DR71E106KA12
