*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/R(-55to125[deg])/2.20e+00[uF]/16[V]
* Murata P/N :GRM32MR11C225KA01
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32MR11C225KA01 Port1 Port2
C01 Port1 N01 2.11e-06
R01 Port1 N01 2.27e+08
L02 N01 N02 1.25e-10
R03 N02 N03 3.83e-03
C04 N03 N04 3.25e-04
R04 N03 N04 4.35e+00
C05 N04 N05 2.90e-04
R05 N04 N05 4.73e-01
C06 N05 N06 2.55e-04
R06 N05 N06 6.43e-02
C07 N06 N07 1.96e-04
R07 N06 N07 7.90e-03
L08 N07 N08 1.46e-11
R08 N07 N08 3.01e-02
L09 N08 N09 1.49e-10
R09 N08 N09 2.88e-02
C10 N09 N10 6.16e-06
L10 N09 N10 4.64e-11
R10 N09 N10 8.97e-03
C11 N10 N11 1.31e-06
L11 N10 N11 8.05e-11
R11 N10 N11 1.26e-02
C12 N11 N12 9.39e-12
L12 N11 N12 1.43e-10
R12 N11 N12 2.42e+01
C13 N12 Port2 3.59e-12
L13 N12 Port2 1.57e-10
R13 N12 Port2 4.91e+01
.ENDS GRM32MR11C225KA01
