*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7S(-55to125[deg])/4.70e+00[uF]/100[V]
* Murata P/N :GRM32DC72A475ME01
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32DC72A475ME01 Port1 Port2
C01 Port1 N01 4.53e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.19e-10
R03 N02 N03 2.52e-03
C04 N03 N04 4.91e-04
R04 N03 N04 6.82e+00
C05 N04 N05 4.76e-04
R05 N04 N05 9.51e-01
C06 N05 N06 3.99e-04
R06 N05 N06 1.63e-01
C07 N06 N07 4.88e-04
R07 N06 N07 1.76e-02
C08 N07 N08 3.67e-04
R08 N07 N08 3.22e-03
L09 N08 N09 1.49e-11
R09 N08 N09 7.35e-02
L10 N09 N10 2.66e-10
R10 N09 N10 2.27e-02
L11 N10 N11 2.81e-11
R11 N10 N11 2.21e-02
C12 N11 N12 7.55e-06
L12 N11 N12 1.37e-10
R12 N11 N12 1.68e-02
C13 N12 N13 5.17e-06
L13 N12 N13 8.05e-11
R13 N12 N13 1.24e-02
C14 N13 N14 2.17e-11
L14 N13 N14 5.27e-11
R14 N13 N14 1.09e+01
C15 N14 Port2 2.53e-12
L15 N14 Port2 1.68e-10
R15 N14 Port2 8.28e+01
.ENDS GRM32DC72A475ME01
