*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/B(-25to85[deg])/2.20e+01[uF]/25[V]
* Murata P/N :GRM32EB31E226KE15
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32EB31E226KE15 Port1 Port2
C01 Port1 N01 2.05e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 5.19e-11
R03 N02 N03 1.63e-03
C04 N03 N04 1.27e-03
R04 N03 N04 4.19e+00
C05 N04 N05 1.37e-03
R05 N04 N05 5.01e-01
C06 N05 N06 1.11e-03
R06 N05 N06 6.77e-02
C07 N06 N07 1.11e-03
R07 N06 N07 6.10e-03
C08 N07 N08 1.60e-03
R08 N07 N08 4.89e-04
L09 N08 N09 4.57e-11
R09 N08 N09 2.70e-02
L10 N09 N10 3.77e-10
R10 N09 N10 1.31e-02
C11 N10 N11 4.72e-05
L11 N10 N11 1.31e-10
R11 N10 N11 6.36e-03
C12 N11 N12 1.70e-05
L12 N11 N12 1.40e-10
R12 N11 N12 5.40e-03
C13 N12 N13 3.50e-11
L13 N12 N13 7.13e-11
R13 N12 N13 3.94e+00
C14 N13 Port2 2.01e-12
L14 N13 Port2 2.59e-10
R14 N13 Port2 6.80e+01
.ENDS GRM32EB31E226KE15
