*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X5R(-55to85[deg])/2.20e+02[uF]/4[V]
* Murata P/N :GRM32ER60G227ME05
* Property : C = 2.20e+02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32ER60G227ME05 Port1 Port2
C01 Port1 N01 1.77e-04
R01 Port1 N01 2.27e+05
L02 N01 N02 1.13e-10
R03 N02 N03 8.72e-04
C04 N03 N04 8.49e-03
R04 N03 N04 6.25e-01
C05 N04 N05 9.22e-03
R05 N04 N05 6.58e-02
C06 N05 N06 7.68e-03
R06 N05 N06 1.12e-02
L07 N06 N07 1.23e-11
R07 N06 N07 5.47e-02
L08 N07 N08 3.67e-11
R08 N07 N08 1.96e-02
L09 N08 N09 7.95e-11
R09 N08 N09 8.28e-03
L10 N09 N10 5.91e-10
R10 N09 N10 4.91e-03
C11 N10 N11 3.47e-04
L11 N10 N11 2.44e-10
R11 N10 N11 1.53e-03
C12 N11 N12 4.26e-04
L12 N11 N12 9.29e-11
R12 N11 N12 1.20e-03
C13 N12 N13 6.52e-11
L13 N12 N13 5.86e-11
R13 N12 N13 4.17e+00
C14 N13 Port2 3.21e-12
L14 N13 Port2 2.02e-10
R14 N13 Port2 8.17e+01
.ENDS GRM32ER60G227ME05
