*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X5R(-55to85[deg])/2.20e+01[uF]/6.3[V]
* Murata P/N :GRM32DR60J226MA01
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32DR60J226MA01 Port1 Port2
C01 Port1 N01 1.71e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 9.46e-11
R03 N02 N03 1.94e-03
C04 N03 N04 4.72e-04
R04 N03 N04 9.35e+00
C05 N04 N05 5.30e-04
R05 N04 N05 9.03e-01
C06 N05 N06 4.49e-04
R06 N05 N06 1.27e-01
C07 N06 N07 4.14e-04
R07 N06 N07 1.64e-02
C08 N07 N08 3.73e-04
R08 N07 N08 2.83e-03
L09 N08 N09 1.10e-11
R09 N08 N09 3.02e-02
L10 N09 N10 4.18e-11
R10 N09 N10 2.18e-02
L11 N10 N11 3.15e-10
R11 N10 N11 1.26e-02
C12 N11 N12 4.16e-05
L12 N11 N12 8.82e-11
R12 N11 N12 5.40e-03
C13 N12 N13 1.59e-05
L13 N12 N13 9.98e-11
R13 N12 N13 5.52e-03
C14 N13 N14 1.61e-11
L14 N13 N14 9.40e-11
R14 N13 N14 1.71e+01
C15 N14 Port2 2.64e-12
L15 N14 Port2 2.18e-10
R15 N14 Port2 5.07e+01
.ENDS GRM32DR60J226MA01
