*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/B(-25to85[deg])/6.80e-01[uF]/50[V]
* Murata P/N :GRM32NB11H684KA01
* Property : C = 6.80e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32NB11H684KA01 Port1 Port2
C01 Port1 N01 6.79e-07
R01 Port1 N01 7.35e+08
L02 N01 N02 6.60e-11
R03 N02 N03 5.83e-03
C04 N03 N04 1.01e-04
R04 N03 N04 3.67e+01
C05 N04 N05 1.71e-04
R05 N04 N05 3.94e+00
C06 N05 N06 1.11e-04
R06 N05 N06 1.27e+00
C07 N06 N07 9.33e-05
R07 N06 N07 1.64e-01
C08 N07 N08 6.96e-05
R08 N07 N08 2.86e-02
C09 N08 N09 5.23e-05
R09 N08 N09 4.81e-03
L10 N09 N10 1.76e-10
R10 N09 N10 4.44e-02
L11 N10 N11 2.22e-11
R11 N10 N11 3.54e-02
C12 N11 N12 1.58e-06
L12 N11 N12 6.29e-11
R12 N11 N12 2.68e-02
C13 N12 N13 5.24e-07
L13 N12 N13 7.27e-11
R13 N12 N13 2.41e-02
C14 N13 N14 1.52e-11
L14 N13 N14 5.96e-11
R14 N13 N14 7.15e+00
C15 N14 Port2 1.65e-12
L15 N14 Port2 1.86e-10
R15 N14 Port2 2.47e+01
.ENDS GRM32NB11H684KA01
