*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X6S(-55to105[deg])/2.20e+01[uF]/10[V]
* Murata P/N :GRM32NC81A226ME19
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32NC81A226ME19 Port1 Port2
C01 Port1 N01 1.71e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 8.60e-11
R03 N02 N03 2.13e-03
C04 N03 N04 4.44e-04
R04 N03 N04 9.95e+00
C05 N04 N05 4.83e-04
R05 N04 N05 1.04e+00
C06 N05 N06 4.38e-04
R06 N05 N06 1.36e-01
C07 N06 N07 3.82e-04
R07 N06 N07 1.99e-02
C08 N07 N08 3.55e-04
R08 N07 N08 3.19e-03
L09 N08 N09 9.09e-12
R09 N08 N09 4.17e-02
L10 N09 N10 4.05e-11
R10 N09 N10 2.48e-02
L11 N10 N11 2.82e-10
R11 N10 N11 1.42e-02
C12 N11 N12 3.52e-05
L12 N11 N12 9.85e-11
R12 N11 N12 4.92e-03
C13 N12 N13 1.39e-05
L13 N12 N13 1.02e-10
R13 N12 N13 6.16e-03
C14 N13 N14 1.15e-11
L14 N13 N14 8.70e-11
R14 N13 N14 2.34e+01
C15 N14 Port2 2.70e-12
L15 N14 Port2 1.64e-10
R15 N14 Port2 6.78e+01
.ENDS GRM32NC81A226ME19
