*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/6.80e-03[uF]/1000[V]
* Murata P/N :GCM31CR73A682KX03
* Property : C = 6.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31CR73A682KX03 Port1 Port2
C01 Port1 N01 7.13e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 3.84e-10
R03 N02 N03 9.26e-02
C04 N03 N04 6.53e-07
R04 N03 N04 2.73e+03
C05 N04 N05 7.96e-07
R05 N04 N05 5.35e+02
C06 N05 N06 7.34e-07
R06 N05 N06 1.06e+02
C07 N06 N07 7.30e-07
R07 N06 N07 2.01e+01
C08 N07 N08 5.93e-07
R08 N07 N08 3.92e+00
C09 N08 N09 5.08e-07
R09 N08 N09 7.95e-01
C10 N09 N10 3.46e-07
R10 N09 N10 1.68e-01
L11 N10 N11 4.09e-11
R11 N10 N11 4.19e-01
L12 N11 N12 7.12e-11
R12 N11 N12 1.67e-01
C13 N12 N13 8.43e-08
L13 N12 N13 1.22e-11
R13 N12 N13 5.06e-02
C14 N13 N14 9.54e-09
L14 N13 N14 3.92e-11
R14 N13 N14 1.30e-01
C15 N14 Port2 7.59e-12
L15 N14 Port2 3.66e-10
R15 N14 Port2 2.37e+01
.ENDS GCM31CR73A682KX03
