*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/2.20e+01[uF]/6.3[V]
* Murata P/N :GCM31CR70J226KE26
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31CR70J226KE26 Port1 Port2
C01 Port1 N01 1.48e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 2.64e-11
R03 N02 N03 3.04e-03
C04 N03 N04 4.29e-04
R04 N03 N04 3.22e+00
C05 N04 N05 5.24e-04
R05 N04 N05 3.17e-01
C06 N05 N06 4.92e-04
R06 N05 N06 4.88e-02
C07 N06 N07 3.50e-04
R07 N06 N07 7.80e-03
L08 N07 N08 1.88e-11
R08 N07 N08 4.70e-02
L09 N08 N09 6.95e-11
R09 N08 N09 2.59e-02
L10 N09 N10 4.86e-10
R10 N09 N10 1.37e-02
C11 N10 N11 5.76e-05
L11 N10 N11 8.14e-11
R11 N10 N11 3.99e-03
C12 N11 N12 2.92e-05
L12 N11 N12 7.69e-11
R12 N11 N12 4.60e-03
C13 N12 N13 2.08e-11
L13 N12 N13 6.36e-11
R13 N12 N13 1.52e+01
C14 N13 Port2 1.16e-12
L14 N13 Port2 3.89e-10
R14 N13 Port2 1.29e+02
.ENDS GCM31CR70J226KE26
