*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R(-55to125[deg])/2.20e+01[uF]/10[V]
* Murata P/N :GCM31CR71A226KE02
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31CR71A226KE02 Port1 Port2
C01 Port1 N01 1.60e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 7.04e-11
R03 N02 N03 2.91e-03
C04 N03 N04 4.10e-04
R04 N03 N04 1.07e+01
C05 N04 N05 5.41e-04
R05 N04 N05 9.06e-01
C06 N05 N06 5.20e-04
R06 N05 N06 1.31e-01
C07 N06 N07 5.04e-04
R07 N06 N07 1.89e-02
C08 N07 N08 3.63e-04
R08 N07 N08 3.89e-03
L09 N08 N09 2.66e-11
R09 N08 N09 5.98e-02
L10 N09 N10 7.14e-11
R10 N09 N10 2.76e-02
L11 N10 N11 4.06e-10
R11 N10 N11 1.42e-02
C12 N11 N12 4.61e-05
L12 N11 N12 9.37e-11
R12 N11 N12 5.58e-03
C13 N12 N13 1.66e-05
L13 N12 N13 1.20e-10
R13 N12 N13 6.45e-03
C14 N13 N14 2.52e-11
L14 N13 N14 4.40e-11
R14 N13 N14 1.09e+01
C15 N14 Port2 1.31e-12
L15 N14 Port2 3.22e-10
R15 N14 Port2 1.40e+02
.ENDS GCM31CR71A226KE02
