*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/R(-55to125[deg])/4.70e-01[uF]/50[V]
* Murata P/N :GCM31MR11H474KA01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM31MR11H474KA01 Port1 Port2
C01 Port1 N01 4.58e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 7.52e-11
R03 N02 N03 8.52e-03
C04 N03 N04 7.35e-05
R04 N03 N04 4.67e+01
C05 N04 N05 9.72e-05
R05 N04 N05 6.90e+00
C06 N05 N06 6.75e-05
R06 N05 N06 9.98e-01
C07 N06 N07 7.95e-05
R07 N06 N07 8.40e-02
C08 N07 N08 4.30e-05
R08 N07 N08 2.46e-02
C09 N08 N09 7.39e-05
R09 N08 N09 2.85e-03
L10 N09 N10 2.77e-11
R10 N09 N10 7.46e-02
L11 N10 N11 1.89e-10
R11 N10 N11 5.94e-02
C12 N11 N12 1.73e-06
L12 N11 N12 4.89e-11
R12 N11 N12 1.84e-02
C13 N12 N13 4.58e-07
L13 N12 N13 7.98e-11
R13 N12 N13 2.90e-02
C14 N13 N14 2.58e-11
L14 N13 N14 7.00e-11
R14 N13 N14 5.35e+00
C15 N14 Port2 1.50e-12
L15 N14 Port2 3.14e-10
R15 N14 Port2 1.18e+02
.ENDS GCM31MR11H474KA01
