*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN3N7B80
* Property : L = 3.7[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN3N7B80 port1 port2
C1 port1 port2 2.29e-14
L2 port1 1 3.66e-9
R2 1 port2 2.50e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.23e-7
R4 2 port2 17.7
L5 port1 3 1.33e-7
R5 3 port2 333
.ENDS LQW15AN3N7B80
*----------------------------------------------------------------------
