*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :4532M(1812)/X7R(-55to125[deg])/6.80e-02[uF]/630[V]
* Murata P/N :GCM43QR72J683KX01
* Property : C = 6.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM43QR72J683KX01 Port1 Port2
C01 Port1 N01 6.80e-08
R01 Port1 N01 1.47e+09
L02 N01 N02 3.63e-10
R03 N02 N03 1.79e-02
C04 N03 N04 8.69e-06
R04 N03 N04 2.50e+02
C05 N04 N05 8.52e-06
R05 N04 N05 7.15e+01
C06 N05 N06 7.64e-06
R06 N05 N06 1.54e+01
C07 N06 N07 7.29e-06
R07 N06 N07 3.34e+00
C08 N07 N08 6.10e-06
R08 N07 N08 7.47e-01
C09 N08 N09 4.94e-06
R09 N08 N09 1.36e-01
C10 N09 N10 3.68e-06
R10 N09 N10 2.80e-02
L11 N10 N11 1.07e-10
R11 N10 N11 1.24e-01
L12 N11 N12 1.03e-11
R12 N11 N12 9.72e-02
C13 N12 N13 1.69e-07
L13 N12 N13 5.39e-11
R13 N12 N13 8.25e-02
C14 N13 N14 3.35e-08
L14 N13 N14 9.04e-11
R14 N13 N14 9.19e-02
C15 N14 Port2 1.66e-11
L15 N14 Port2 1.46e-10
R15 N14 Port2 7.47e+00
.ENDS GCM43QR72J683KX01
