*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/3.00e-07[uF]/50[V]
* Murata P/N :GCM1555G1HR30CA16
* Property : C = 3.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-20[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1HR30CA16 Port1 Port2
C01 Port1 N01 3.00e-13
R01 Port1 N01 1.00e+11
L02 N01 N02 2.45e-10
R03 N02 N03 7.95e-01
C04 N03 Port2 3.04e-13
L04 N03 Port2 1.28e-10
R04 N03 Port2 1.12e+03
.ENDS GCM1555G1HR30CA16
