*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/3.90e-05[uF]/50[V]
* Murata P/N :GCM1555G1H390JA16
* Property : C = 3.90e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H390JA16 Port1 Port2
C01 Port1 N01 3.90e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 1.99e-10
R03 N02 N03 1.54e-01
C04 N03 N04 3.50e-10
L04 N03 N04 9.12e-12
R04 N03 N04 1.18e+00
C05 N04 N05 1.69e-10
L05 N04 N05 6.09e-12
R05 N04 N05 1.09e+00
C06 N05 Port2 7.60e-13
L06 N05 Port2 1.24e-10
R06 N05 Port2 1.72e+01
.ENDS GCM1555G1H390JA16
