*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN1N8C00
* Property : L = 1.8[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN1N8C00 port1 port2
C1 port1 port2 2.15e-14
L2 port1 1 1.49e-9
R2 1 port2 1.10e-1
R3 port1 port2 6.53e+3
L4 port1 2 3.05e-8
R4 2 port2 62.3
L5 port1 3 4.98e-8
R5 3 port2 441
.ENDS LQW15AN1N8C00
*----------------------------------------------------------------------
