*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/U2J(-55to125[deg])/1.20e-04[uF]/2000[V]
* Murata P/N :GRM32A7U3D121JW31
* Property : C = 1.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32A7U3D121JW31 Port1 Port2
C01 Port1 N01 1.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 3.54e-12
R03 N02 N03 8.04e-02
C04 N03 N04 1.87e-10
L04 N03 N04 4.00e-11
R04 N03 N04 2.45e+00
C05 N04 N05 4.35e-11
L05 N04 N05 4.88e-11
R05 N04 N05 4.20e+00
C06 N05 Port2 1.22e-12
L06 N05 Port2 4.61e-10
R06 N05 Port2 1.97e+02
.ENDS GRM32A7U3D121JW31
