*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/U2J(-55to125[deg])/6.80e-03[uF]/630[V]
* Murata P/N :GRM32Q7U2J682JW31
* Property : C = 6.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32Q7U2J682JW31 Port1 Port2
C01 Port1 N01 6.77e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 9.91e-12
R03 N02 N03 4.51e-03
L04 N03 N04 1.46e-10
R04 N03 N04 4.21e-01
L05 N04 N05 2.28e-11
R05 N04 N05 2.74e-03
C06 N05 N06 1.05e-08
L06 N05 N06 1.02e-10
R06 N05 N06 8.29e-01
C07 N06 N07 9.06e-09
L07 N06 N07 4.48e-11
R07 N06 N07 7.27e-01
C08 N07 N08 1.99e-08
L08 N07 N08 9.54e-12
R08 N07 N08 1.88e-01
C09 N08 N09 1.07e-08
L09 N08 N09 1.08e-11
R09 N08 N09 1.80e-01
C10 N09 Port2 1.33e-12
L10 N09 Port2 3.49e-10
R10 N09 Port2 2.86e+02
.ENDS GRM32Q7U2J682JW31
