*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/C0G(-55to125[deg])/1.50e-02[uF]/1000[V]
* Murata P/N :GRM32E5C3A153FWAA
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32E5C3A153FWAA Port1 Port2
C01 Port1 N01 1.46e-08
R01 Port1 N01 6.67e+09
L02 N01 N02 2.72e-10
R03 N02 N03 9.78e-03
C04 N03 N04 1.37e-06
R04 N03 N04 1.25e+02
L05 N04 N05 1.45e-10
R05 N04 N05 2.63e-01
L06 N05 N06 7.28e-10
R06 N05 N06 3.75e-03
C07 N06 N07 3.82e-08
L07 N06 N07 9.93e-11
R07 N06 N07 7.63e-01
C08 N07 N08 3.98e-08
L08 N07 N08 3.89e-11
R08 N07 N08 5.48e-01
C09 N08 N09 4.33e-08
L09 N08 N09 1.84e-11
R09 N08 N09 2.62e-01
C10 N09 N10 3.51e-08
L10 N09 N10 1.43e-11
R10 N09 N10 2.51e-01
C11 N10 N11 1.66e-07
L11 N10 N11 1.99e-12
R11 N10 N11 6.53e-02
C12 N11 N12 3.11e-08
L12 N11 N12 7.59e-12
R12 N11 N12 1.22e-01
C13 N12 Port2 3.87e-12
L13 N12 Port2 1.68e-10
R13 N12 Port2 3.57e+02
.ENDS GRM32E5C3A153FWAA
