*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/C0G(-55to125[deg])/8.20e-03[uF]/1000[V]
* Murata P/N :GRM32D5C3A822FWA1
* Property : C = 8.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32D5C3A822FWA1 Port1 Port2
C01 Port1 N01 8.01e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.42e-11
R03 N02 N03 1.17e-02
C04 N03 N04 7.60e-07
R04 N03 N04 3.15e+02
L05 N04 N05 1.43e-10
R05 N04 N05 3.87e-01
L06 N05 N06 5.40e-11
R06 N05 N06 4.56e-03
C07 N06 N07 1.29e-08
L07 N06 N07 1.25e-10
R07 N06 N07 1.49e+00
C08 N07 N08 9.11e-09
L08 N07 N08 7.15e-11
R08 N07 N08 1.13e+00
C09 N08 N09 2.02e-08
L09 N08 N09 1.57e-11
R09 N08 N09 3.88e-01
C10 N09 N10 1.45e-08
L10 N09 N10 1.37e-11
R10 N09 N10 4.03e-01
C11 N10 N11 1.01e-08
L11 N10 N11 1.12e-11
R11 N10 N11 1.43e-01
C12 N11 Port2 1.67e-12
L12 N11 Port2 3.50e-10
R12 N11 Port2 3.02e+02
.ENDS GRM32D5C3A822FWA1
