*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/C0G(-55to125[deg])/2.20e-02[uF]/1000[V]
* Murata P/N :GRM32E5C3A223GWAA
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32E5C3A223GWAA Port1 Port2
C01 Port1 N01 2.17e-08
R01 Port1 N01 4.55e+09
L02 N01 N02 1.02e-10
R03 N02 N03 5.41e-03
C04 N03 N04 4.16e-07
R04 N03 N04 1.66e+03
L05 N04 N05 2.40e-10
R05 N04 N05 8.27e-03
L06 N05 N06 2.94e-09
R06 N05 N06 4.19e-03
C07 N06 N07 1.07e-07
L07 N06 N07 2.01e-11
R07 N06 N07 2.11e-01
C08 N07 N08 2.81e-07
L08 N07 N08 2.49e-12
R08 N07 N08 7.37e-02
C09 N08 N09 3.52e-07
L09 N08 N09 9.48e-13
R09 N08 N09 4.17e-02
C10 N09 N10 6.07e-10
L10 N09 N10 4.95e-11
R10 N09 N10 7.56e-02
C11 N10 Port2 1.41e-12
L11 N10 Port2 3.84e-10
R11 N10 Port2 2.84e+02
.ENDS GRM32E5C3A223GWAA
