*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/C0G(-55to125[deg])/1.80e-02[uF]/1000[V]
* Murata P/N :GRM32E5C3A183GWAA
* Property : C = 1.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32E5C3A183GWAA Port1 Port2
C01 Port1 N01 1.77e-08
R01 Port1 N01 5.56e+09
L02 N01 N02 1.40e-10
R03 N02 N03 1.06e-02
C04 N03 N04 6.43e-06
R04 N03 N04 7.48e+00
L05 N04 N05 9.83e-11
R05 N04 N05 2.30e-01
L06 N05 N06 1.45e-10
R06 N05 N06 8.76e-03
C07 N06 N07 4.23e-08
L07 N06 N07 9.44e-11
R07 N06 N07 6.09e-01
C08 N07 N08 2.66e-08
L08 N07 N08 5.83e-11
R08 N07 N08 5.20e-01
C09 N08 N09 7.79e-08
L09 N08 N09 1.01e-11
R09 N08 N09 1.95e-01
C10 N09 N10 3.20e-08
L10 N09 N10 1.47e-11
R10 N09 N10 1.95e-01
C11 N10 N11 4.07e-08
L11 N10 N11 5.53e-12
R11 N10 N11 8.17e-02
C12 N11 Port2 1.83e-12
L12 N11 Port2 4.09e-10
R12 N11 Port2 1.13e+03
.ENDS GRM32E5C3A183GWAA
