*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/2.20e-04[uF]/50[V]
* Murata P/N :GCM1555G1H221FA16
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H221FA16 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 2.53e-10
R03 N02 N03 8.82e-02
L04 N03 N04 3.77e-11
R04 N03 N04 6.77e-01
C05 N04 N05 7.46e-09
L05 N04 N05 1.94e-12
R05 N04 N05 1.05e-01
C06 N05 N06 3.64e-10
L06 N05 N06 1.59e-11
R06 N05 N06 6.05e-01
C07 N06 Port2 2.84e-12
L07 N06 Port2 9.38e-11
R07 N06 Port2 2.70e+01
.ENDS GCM1555G1H221FA16
