*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/2.70e-04[uF]/50[V]
* Murata P/N :GCM1555G1H271JA16
* Property : C = 2.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H271JA16 Port1 Port2
C01 Port1 N01 2.70e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 2.99e-10
R03 N02 N03 7.42e-02
L04 N03 N04 4.86e-11
R04 N03 N04 9.90e-01
L05 N04 N05 4.58e-12
R05 N04 N05 1.15e-02
C06 N05 N06 5.05e-09
L06 N05 N06 3.85e-12
R06 N05 N06 1.94e-01
C07 N06 Port2 5.19e-10
L07 N06 Port2 1.56e-11
R07 N06 Port2 5.72e-01
.ENDS GCM1555G1H271JA16
