*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/ZLM(-25to85[deg])/1.20e-03[uF]/100[V]
* Murata P/N :GCM2199E2A122KA04
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2199E2A122KA04 Port1 Port2
C01 Port1 N01 1.17e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 5.17e-11
R03 N02 N03 8.60e-02
C04 N03 N04 1.87e-07
R04 N03 N04 1.03e+01
C05 N04 N05 3.26e-07
R05 N04 N05 4.37e-01
C06 N05 N06 3.26e-07
R06 N05 N06 4.58e-02
L07 N06 N07 9.16e-11
R07 N06 N07 1.55e+00
C08 N07 N08 7.92e-09
L08 N07 N08 1.03e-11
R08 N07 N08 1.68e-01
C09 N08 N09 6.02e-10
L09 N08 N09 4.99e-11
R09 N08 N09 6.46e-01
C10 N09 N10 5.50e-12
L10 N09 N10 2.06e-10
R10 N09 N10 3.36e+01
C11 N10 N11 2.32e-11
L11 N10 N11 2.06e-11
R11 N10 N11 7.30e+00
C12 N11 Port2 1.96e-12
L12 N11 Port2 1.38e-10
R12 N11 Port2 1.68e+01
.ENDS GCM2199E2A122KA04
