*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/2.70e-04[uF]/100[V]
* Murata P/N :GCM2162C2A271JA01
* Property : C = 2.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2162C2A271JA01 Port1 Port2
C01 Port1 N01 2.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 6.34e-11
R03 N02 N03 7.00e-02
L04 N03 N04 4.00e-11
R04 N03 N04 1.25e+00
C05 N04 N05 8.64e-10
L05 N04 N05 2.33e-11
R05 N04 N05 1.02e+00
C06 N05 N06 2.50e-10
L06 N05 N06 2.77e-11
R06 N05 N06 1.54e+00
C07 N06 N07 1.32e-09
L07 N06 N07 2.32e-12
R07 N06 N07 2.68e-01
C08 N07 N08 5.15e-10
L08 N07 N08 3.31e-12
R08 N07 N08 4.32e-01
C09 N08 N09 5.92e-12
L09 N08 N09 5.27e-11
R09 N08 N09 1.31e+01
C10 N09 Port2 1.08e-12
L10 N09 Port2 2.19e-10
R10 N09 Port2 1.00e+05
.ENDS GCM2162C2A271JA01
