*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/1.30e-02[uF]/80[V]
* Murata P/N :GCM2192C1K133GA01
* Property : C = 1.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2192C1K133GA01 Port1 Port2
C01 Port1 N01 1.31e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.04e-10
R03 N02 N03 2.61e-03
L04 N03 N04 7.71e-11
R04 N03 N04 2.28e-01
L05 N04 N05 5.93e-11
R05 N04 N05 7.73e-03
L06 N05 N06 1.87e-10
R06 N05 N06 2.92e-03
C07 N06 N07 3.58e-08
L07 N06 N07 4.37e-11
R07 N06 N07 2.86e-01
C08 N07 N08 1.44e-08
L08 N07 N08 4.37e-11
R08 N07 N08 3.13e-01
C09 N08 N09 7.18e-08
L09 N08 N09 4.24e-12
R09 N08 N09 5.94e-02
C10 N09 N10 1.64e-08
L10 N09 N10 1.11e-11
R10 N09 N10 1.06e-01
C11 N10 Port2 3.48e-12
L11 N10 Port2 9.08e-11
R11 N10 Port2 2.46e+01
.ENDS GCM2192C1K133GA01
