*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/6.80e-05[uF]/250[V]
* Murata P/N :GCM21A5C2E680JX01
* Property : C = 6.80e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21A5C2E680JX01 Port1 Port2
C01 Port1 N01 6.80e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 3.77e-10
R03 N02 N03 1.31e-01
L04 N03 N04 1.74e-11
R04 N03 N04 4.23e-01
C05 N04 N05 6.48e-10
L05 N04 N05 7.55e-12
R05 N04 N05 8.06e-01
C06 N05 N06 5.45e-11
L06 N05 N06 3.02e-11
R06 N05 N06 3.69e+00
C07 N06 Port2 2.02e-12
L07 N06 Port2 1.74e-10
R07 N06 Port2 3.23e+01
.ENDS GCM21A5C2E680JX01
