*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/U2J(-55to125[deg])/1.20e-03[uF]/250[V]
* Murata P/N :GCM21A7U2E122JX01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21A7U2E122JX01 Port1 Port2
C01 Port1 N01 1.20e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 4.44e-11
R03 N02 N03 2.16e-02
L04 N03 N04 7.51e-11
R04 N03 N04 4.17e-01
C05 N04 N05 2.43e-08
L05 N04 N05 6.64e-11
R05 N04 N05 2.06e-02
C06 N05 N06 1.35e-08
L06 N05 N06 7.25e-12
R06 N05 N06 1.49e-01
C07 N06 N07 1.54e-09
L07 N06 N07 2.22e-11
R07 N06 N07 4.19e-01
C08 N07 Port2 8.04e-13
L08 N07 Port2 4.50e-10
R08 N07 Port2 5.29e+02
.ENDS GCM21A7U2E122JX01
