*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/2.20e-04[uF]/100[V]
* Murata P/N :GCM2162C2A221JA01
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2162C2A221JA01 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 7.40e-11
R03 N02 N03 7.35e-02
L04 N03 N04 1.74e-11
R04 N03 N04 3.38e-01
C05 N04 N05 7.83e-10
L05 N04 N05 1.81e-11
R05 N04 N05 8.79e-01
C06 N05 N06 1.62e-10
L06 N05 N06 2.89e-11
R06 N05 N06 1.65e+00
C07 N06 N07 1.45e-10
L07 N06 N07 7.82e-12
R07 N06 N07 8.02e-01
C08 N07 Port2 1.17e-12
L08 N07 Port2 3.13e-10
R08 N07 Port2 2.34e+02
.ENDS GCM2162C2A221JA01
