*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/U2J(-55to125[deg])/1.00e-04[uF]/250[V]
* Murata P/N :GCM21A7U2E101JX01
* Property : C = 1.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21A7U2E101JX01 Port1 Port2
C01 Port1 N01 1.00e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 1.38e-11
R03 N02 N03 1.56e-01
C04 N03 N04 2.10e-09
L04 N03 N04 5.91e-12
R04 N03 N04 3.42e-01
C05 N04 N05 1.19e-10
L05 N04 N05 4.12e-11
R05 N04 N05 2.04e+00
C06 N05 N06 4.51e-11
L06 N05 N06 2.89e-11
R06 N05 N06 1.49e+00
C07 N06 Port2 7.96e-13
L07 N06 Port2 6.07e-10
R07 N06 Port2 3.65e+02
.ENDS GCM21A7U2E101JX01
