*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.80e-03[uF]/100[V]
* Murata P/N :GCM2165C2A182JA16
* Property : C = 1.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2165C2A182JA16 Port1 Port2
C01 Port1 N01 1.77e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 4.03e-11
R03 N02 N03 1.30e-02
L04 N03 N04 5.23e-11
R04 N03 N04 5.55e-01
L05 N04 N05 6.93e-11
R05 N04 N05 2.67e-02
C06 N05 N06 1.12e-08
L06 N05 N06 1.15e-11
R06 N05 N06 2.27e-01
C07 N06 N07 1.43e-09
L07 N06 N07 2.94e-11
R07 N06 N07 3.95e-01
C08 N07 N08 2.13e-11
L08 N07 N08 1.75e-11
R08 N07 N08 4.12e+00
C09 N08 Port2 6.90e-13
L09 N08 Port2 3.82e-10
R09 N08 Port2 1.00e+05
.ENDS GCM2165C2A182JA16
