*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/5.60e-04[uF]/100[V]
* Murata P/N :GCM2162C2A561JA01
* Property : C = 5.60e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2162C2A561JA01 Port1 Port2
C01 Port1 N01 5.60e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 8.59e-11
R03 N02 N03 5.00e-02
C04 N03 N04 1.76e-09
L04 N03 N04 1.89e-11
R04 N03 N04 3.51e-01
C05 N04 N05 3.10e-10
L05 N04 N05 3.30e-11
R05 N04 N05 7.10e-01
C06 N05 N06 2.64e-10
L06 N05 N06 1.08e-11
R06 N05 N06 5.58e-01
C07 N06 N07 3.64e-12
L07 N06 N07 8.60e-11
R07 N06 N07 2.77e+01
C08 N07 Port2 1.22e-12
L08 N07 Port2 2.54e-10
R08 N07 Port2 1.00e+05
.ENDS GCM2162C2A561JA01
