*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/U2J(-55to125[deg])/3.30e-04[uF]/250[V]
* Murata P/N :GCM21A7U2E331JX01
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21A7U2E331JX01 Port1 Port2
C01 Port1 N01 3.30e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 6.17e-12
R03 N02 N03 8.74e-02
L04 N03 N04 1.08e-10
R04 N03 N04 1.38e+00
C05 N04 N05 1.28e-08
L05 N04 N05 3.48e-12
R05 N04 N05 1.12e-01
C06 N05 N06 7.09e-10
L06 N05 N06 2.53e-11
R06 N05 N06 7.14e-01
C07 N06 Port2 7.31e-13
L07 N06 Port2 6.09e-10
R07 N06 Port2 8.58e+02
.ENDS GCM21A7U2E331JX01
