*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/2.20e-02[uF]/50[V]
* Murata P/N :GCM21B2C1H223JA01
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21B2C1H223JA01 Port1 Port2
C01 Port1 N01 2.20e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 6.17e-11
R03 N02 N03 3.28e-03
L04 N03 N04 1.25e-10
R04 N03 N04 2.03e-01
L05 N04 N05 7.39e-11
R05 N04 N05 5.06e-03
C06 N05 N06 5.98e-08
L06 N05 N06 5.67e-11
R06 N05 N06 2.80e-01
C07 N06 N07 2.98e-08
L07 N06 N07 4.96e-11
R07 N06 N07 2.37e-01
C08 N07 N08 7.48e-08
L08 N07 N08 1.02e-11
R08 N07 N08 6.61e-02
C09 N08 N09 4.79e-08
L09 N08 N09 9.99e-12
R09 N08 N09 8.13e-02
C10 N09 N10 2.85e-12
L10 N09 N10 1.05e-10
R10 N09 N10 4.56e+01
C11 N10 Port2 2.23e-12
L11 N10 Port2 1.31e-10
R11 N10 Port2 1.00e+05
.ENDS GCM21B2C1H223JA01
