*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/2.20e-02[uF]/63[V]
* Murata P/N :GCM21B5C1J223JA16
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21B5C1J223JA16 Port1 Port2
C01 Port1 N01 2.25e-08
R01 Port1 N01 4.55e+10
L02 N01 N02 1.08e-10
R03 N02 N03 3.30e-03
C04 N03 N04 4.25e-06
R04 N03 N04 1.08e+00
C05 N04 N05 5.94e-05
R05 N04 N05 6.37e-03
L06 N05 N06 1.57e-10
R06 N05 N06 1.82e-01
L07 N06 N07 6.30e-11
R07 N06 N07 3.28e-03
C08 N07 N08 5.19e-08
L08 N07 N08 6.72e-11
R08 N07 N08 3.14e-01
C09 N08 N09 5.13e-08
L09 N08 N09 3.04e-11
R09 N08 N09 2.27e-01
C10 N09 N10 1.49e-07
L10 N09 N10 5.43e-12
R10 N09 N10 7.84e-02
C11 N10 N11 8.52e-08
L11 N10 N11 6.01e-12
R11 N10 N11 8.12e-02
C12 N11 Port2 1.30e-12
L12 N11 Port2 1.88e-10
R12 N11 Port2 1.39e+02
.ENDS GCM21B5C1J223JA16
