*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/3.30e-04[uF]/100[V]
* Murata P/N :GCM2165C2A331JA16
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM2165C2A331JA16 Port1 Port2
C01 Port1 N01 3.30e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 2.00e-11
R03 N02 N03 1.80e-02
C04 N03 N04 1.55e-08
R04 N03 N04 1.14e-01
L05 N04 N05 5.12e-11
R05 N04 N05 8.38e-02
L06 N05 N06 6.56e-11
R06 N05 N06 4.27e+00
C07 N06 N07 5.80e-13
L07 N06 N07 4.16e-10
C08 N07 N08 1.62e-10
L08 N07 N08 1.92e-12
R08 N07 N08 4.61e-01
C09 N08 N09 1.72e-10
L09 N08 N09 1.88e-11
R09 N08 N09 6.19e-01
C10 N09 Port2 1.20e-09
L10 N09 Port2 1.08e-11
R10 N09 Port2 2.39e-01
.ENDS GCM2165C2A331JA16
