*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :4532M(1812)/X7R(-55to125[deg])/2.20e-01[uF]/500[V]
* Murata P/N :GRM43DR72H224KW10
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM43DR72H224KW10 Port1 Port2
C01 Port1 N01 2.22e-07
R01 Port1 N01 4.55e+08
L02 N01 N02 3.75e-10
R03 N02 N03 1.34e-02
C04 N03 N04 2.03e-05
R04 N03 N04 9.56e+01
C05 N04 N05 2.41e-05
R05 N04 N05 1.76e+01
C06 N05 N06 2.01e-05
R06 N05 N06 3.90e+00
C07 N06 N07 1.75e-05
R07 N06 N07 7.66e-01
C08 N07 N08 2.34e-05
R08 N07 N08 1.11e-01
C09 N08 N09 1.51e-05
R09 N08 N09 2.46e-02
L10 N09 N10 1.68e-10
R10 N09 N10 6.46e-02
L11 N10 N11 1.58e-11
R11 N10 N11 3.15e-02
C12 N11 N12 4.77e-07
L12 N11 N12 7.07e-11
R12 N11 N12 3.63e-02
C13 N12 N13 2.17e-07
L13 N12 N13 5.01e-11
R13 N12 N13 3.11e-02
C14 N13 Port2 8.66e-12
L14 N13 Port2 2.83e-10
R14 N13 Port2 1.40e+01
.ENDS GRM43DR72H224KW10
