*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :4532M(1812)/X7R(-55to125[deg])/4.70e-01[uF]/250[V]
* Murata P/N :GRM43DR72E474KW01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM43DR72E474KW01 Port1 Port2
C01 Port1 N01 4.69e-07
R01 Port1 N01 2.13e+08
L02 N01 N02 4.01e-10
R03 N02 N03 8.74e-03
C04 N03 N04 4.61e-05
R04 N03 N04 4.49e+01
C05 N04 N05 5.03e-05
R05 N04 N05 1.01e+01
C06 N05 N06 4.31e-05
R06 N05 N06 2.14e+00
C07 N06 N07 3.84e-05
R07 N06 N07 4.77e-01
C08 N07 N08 5.29e-05
R08 N07 N08 6.05e-02
C09 N08 N09 3.41e-05
R09 N08 N09 1.16e-02
L10 N09 N10 1.82e-10
R10 N09 N10 5.21e-02
L11 N10 N11 2.60e-11
R11 N10 N11 1.07e-02
C12 N11 N12 1.40e-06
L12 N11 N12 6.21e-11
R12 N11 N12 2.68e-02
C13 N12 N13 2.86e-07
L13 N12 N13 9.73e-11
R13 N12 N13 2.96e-02
C14 N13 Port2 1.41e-11
L14 N13 Port2 1.72e-10
R14 N13 Port2 9.51e+00
.ENDS GRM43DR72E474KW01
