*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/6.80e-04[uF]/25[V]
* Murata P/N :GRM1882C1E681JA01
* Property : C = 6.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1882C1E681JA01 Port1 Port2
C01 Port1 N01 6.80e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.36e-10
R03 N02 N03 5.00e-02
L04 N03 N04 2.04e-11
R04 N03 N04 9.21e-01
L05 N04 N05 8.36e-11
R05 N04 N05 5.86e-01
C06 N05 N06 6.32e-09
L06 N05 N06 1.49e-11
R06 N05 N06 3.90e-01
C07 N06 N07 1.61e-09
L07 N06 N07 1.92e-11
R07 N06 N07 5.32e-01
C08 N07 Port2 7.45e-13
L08 N07 Port2 2.57e-10
R08 N07 Port2 1.00e+05
.ENDS GRM1882C1E681JA01
