*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/6.00e-07[uF]/50[V]
* Murata P/N :GRM1885C1HR60WA01
* Property : C = 6.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1HR60WA01 Port1 Port2
C01 Port1 N01 6.00e-13
R01 Port1 N01 1.00e+10
L02 N01 N02 1.53e-11
R03 N02 N03 5.77e-01
L04 N03 N04 5.35e-10
R04 N03 N04 5.91e+03
C05 N04 Port2 4.17e-10
L05 N04 Port2 8.11e-13
R05 N04 Port2 1.32e+00
.ENDS GRM1885C1HR60WA01
