*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/SL(-55to125[deg])/1.20e-03[uF]/50[V]
* Murata P/N :GRM1881X1H122JA01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1881X1H122JA01 Port1 Port2
C01 Port1 N01 1.17e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.11e-10
R03 N02 N03 2.77e-02
L04 N03 N04 7.47e-11
R04 N03 N04 7.07e-01
L05 N04 N05 1.73e-10
R05 N04 N05 1.96e-02
C06 N05 N06 1.14e-08
L06 N05 N06 1.35e-11
R06 N05 N06 1.51e-01
C07 N06 N07 1.92e-09
L07 N06 N07 3.43e-11
R07 N06 N07 4.20e-01
C08 N07 Port2 1.07e-12
L08 N07 Port2 3.37e-10
R08 N07 Port2 8.18e+02
.ENDS GRM1881X1H122JA01
