*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/UJ(-25to85[deg])/8.20e-03[uF]/50[V]
* Murata P/N :GRM1883U1H822JA01
* Property : C = 8.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1883U1H822JA01 Port1 Port2
C01 Port1 N01 8.35e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 7.47e-11
R03 N02 N03 1.14e-02
L04 N03 N04 7.54e-11
R04 N03 N04 2.80e-01
L05 N04 N05 5.26e-11
R05 N04 N05 1.27e-02
C06 N05 N06 4.49e-08
L06 N05 N06 2.40e-11
R06 N05 N06 1.01e-01
C07 N06 N07 1.59e-08
L07 N06 N07 3.16e-11
R07 N06 N07 1.79e-01
C08 N07 N08 9.81e-09
L08 N07 N08 1.51e-11
R08 N07 N08 6.55e-02
C09 N08 N09 2.46e-12
L09 N08 N09 1.24e-10
R09 N08 N09 1.41e+02
C10 N09 Port2 1.64e-12
L10 N09 Port2 1.52e-10
R10 N09 Port2 1.00e+05
.ENDS GRM1883U1H822JA01
