*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/3.90e-03[uF]/100[V]
* Murata P/N :GRM1882C2A392JA01
* Property : C = 3.90e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1882C2A392JA01 Port1 Port2
C01 Port1 N01 3.84e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 3.17e-10
R03 N02 N03 7.60e-03
L04 N03 N04 1.02e-10
R04 N03 N04 3.69e-01
L05 N04 N05 5.34e-11
R05 N04 N05 1.33e-02
L06 N05 N06 1.38e-10
R06 N05 N06 5.29e-03
C07 N06 N07 2.13e-08
L07 N06 N07 2.39e-11
R07 N06 N07 3.03e-01
C08 N07 N08 8.43e-09
L08 N07 N08 2.82e-11
R08 N07 N08 3.91e-01
C09 N08 Port2 1.70e-11
L09 N08 Port2 2.15e-11
R09 N08 Port2 5.93e+00
.ENDS GRM1882C2A392JA01
