*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/3.00e-03[uF]/50[V]
* Murata P/N :GRM1885C1H302JA01
* Property : C = 3.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1H302JA01 Port1 Port2
C01 Port1 N01 3.07e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.69e-10
R03 N02 N03 9.20e-03
L04 N03 N04 7.91e-11
R04 N03 N04 3.43e-01
L05 N04 N05 2.90e-11
R05 N04 N05 1.32e-02
L06 N05 N06 9.67e-11
R06 N05 N06 6.72e-03
C07 N06 N07 1.97e-08
L07 N06 N07 2.01e-11
R07 N06 N07 2.61e-01
C08 N07 N08 6.89e-09
L08 N07 N08 2.58e-11
R08 N07 N08 3.79e-01
C09 N08 N09 7.00e-09
L09 N08 N09 8.22e-12
R09 N08 N09 1.18e-01
C10 N09 Port2 3.96e-13
L10 N09 Port2 1.96e-10
R10 N09 Port2 1.67e+02
.ENDS GRM1885C1H302JA01
