*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/2.00e-04[uF]/50[V]
* Murata P/N :GRM1885C1H201JA01
* Property : C = 2.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1H201JA01 Port1 Port2
C01 Port1 N01 2.00e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.29e-10
R03 N02 N03 9.11e-02
L04 N03 N04 2.75e-11
R04 N03 N04 8.65e-02
L05 N04 N05 1.08e-12
R05 N04 N05 2.27e-02
C06 N05 N06 2.15e-10
L06 N05 N06 2.60e-11
R06 N05 N06 9.76e-01
C07 N06 N07 1.31e-10
L07 N06 N07 1.03e-11
R07 N06 N07 5.35e-01
C08 N07 Port2 1.01e-12
L08 N07 Port2 2.82e-10
R08 N07 Port2 3.23e+02
.ENDS GRM1885C1H201JA01
