*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/8.30e-06[uF]/50[V]
* Murata P/N :GRM1882C1H8R3BA01
* Property : C = 8.30e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1882C1H8R3BA01 Port1 Port2
C01 Port1 N01 8.30e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 3.22e-10
R03 N02 N03 1.08e-01
L04 N03 N04 1.13e-10
R04 N03 N04 1.81e-01
C05 N04 N05 4.54e-11
L05 N04 N05 2.11e-11
R05 N04 N05 8.42e+00
C06 N05 N06 5.13e-12
L06 N05 N06 8.00e-11
R06 N05 N06 2.99e+01
C07 N06 Port2 6.46e-12
L07 N06 Port2 5.05e-11
R07 N06 Port2 4.22e+01
.ENDS GRM1882C1H8R3BA01
