*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/3.90e-04[uF]/50[V]
* Murata P/N :GRM1885C1H391JA01
* Property : C = 3.90e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1H391JA01 Port1 Port2
C01 Port1 N01 3.90e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.00e-11
R03 N02 N03 6.00e-02
L04 N03 N04 5.49e-11
R04 N03 N04 7.60e-01
C05 N04 N05 9.78e-13
L05 N04 N05 3.85e-10
R05 N04 N05 3.20e+02
C06 N05 N06 7.59e-10
L06 N05 N06 7.13e-12
R06 N05 N06 2.62e-01
C07 N06 N07 6.22e-10
L07 N06 N07 2.83e-11
R07 N06 N07 7.43e-01
C08 N07 Port2 2.69e-09
L08 N07 Port2 1.92e-11
R08 N07 Port2 5.71e-01
.ENDS GRM1885C1H391JA01
