*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/4.00e-06[uF]/50[V]
* Murata P/N :GRM1885C1H4R0WA01
* Property : C = 4.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1H4R0WA01 Port1 Port2
C01 Port1 N01 4.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 3.92e-10
R03 N02 N03 1.43e-01
L04 N03 N04 1.14e-10
R04 N03 N04 2.57e-01
C05 N04 N05 8.50e-12
L05 N04 N05 4.98e-11
R05 N04 N05 2.28e+01
C06 N05 Port2 7.58e-12
L06 N05 Port2 4.44e-11
R06 N05 Port2 1.31e+02
.ENDS GRM1885C1H4R0WA01
