*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/2.00e-05[uF]/50[V]
* Murata P/N :GRM1885C1H200JA01
* Property : C = 2.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1885C1H200JA01 Port1 Port2
C01 Port1 N01 2.00e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 4.65e-10
R03 N02 N03 2.24e-01
L04 N03 N04 1.76e-11
R04 N03 N04 6.98e-01
C05 N04 N05 2.97e-10
L05 N04 N05 8.68e-12
R05 N04 N05 9.88e-01
C06 N05 N06 3.43e-11
L06 N05 N06 2.22e-11
R06 N05 N06 3.04e+00
C07 N06 Port2 2.00e-11
L07 N06 Port2 1.66e-11
R07 N06 Port2 3.22e+00
.ENDS GRM1885C1H200JA01
