*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/X7S(-55to125[deg])/1.00e-02[uF]/10[V]
* Murata P/N :GRM022C71A103ME01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022C71A103ME01 Port1 Port2
C01 Port1 N01 7.61e-09
R01 Port1 N01 2.00e+09
L02 N01 N02 1.55e-10
R03 N02 N03 9.72e-02
C04 N03 N04 1.71e-07
R04 N03 N04 1.89e+04
C05 N04 N05 2.35e-07
R05 N04 N05 1.50e+03
C06 N05 N06 2.00e-07
R06 N05 N06 2.38e+02
C07 N06 N07 1.71e-07
R07 N06 N07 3.77e+01
C08 N07 N08 1.46e-07
R08 N07 N08 6.30e+00
C09 N08 N09 1.16e-07
R09 N08 N09 1.30e+00
C10 N09 N10 2.01e-07
R10 N09 N10 2.04e-01
C11 N10 N11 6.37e-08
R11 N10 N11 1.41e-01
L12 N11 N12 1.74e-11
R12 N11 N12 1.65e+00
L13 N12 N13 4.17e-11
R13 N12 N13 1.65e-01
C14 N13 Port2 3.30e-08
L14 N13 Port2 3.37e-12
R14 N13 Port2 1.19e-02
.ENDS GRM022C71A103ME01
