*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/X5R(-55to85[deg])/1.00e-03[uF]/16[V]
* Murata P/N :GRM022R61C102ME01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022R61C102ME01 Port1 Port2
C01 Port1 N01 8.34e-10
R01 Port1 N01 2.00e+09
L02 N01 N02 1.39e-10
R03 N02 N03 2.49e-01
C04 N03 N04 2.58e-08
R04 N03 N04 2.00e+05
C05 N04 N05 2.76e-08
R05 N04 N05 2.41e+04
C06 N05 N06 2.46e-08
R06 N05 N06 2.83e+03
C07 N06 N07 2.37e-08
R07 N06 N07 3.73e+02
C08 N07 N08 1.49e-08
R08 N07 N08 7.21e+01
C09 N08 N09 1.16e-08
R09 N08 N09 1.00e+01
C10 N09 N10 8.35e-09
R10 N09 N10 1.60e+00
C11 N10 N11 8.47e-09
R11 N10 N11 2.38e-01
L12 N11 N12 3.17e-11
R12 N11 N12 9.02e-01
C13 N12 N13 1.19e-09
L13 N12 N13 3.86e-12
R13 N12 N13 7.64e-02
C14 N13 Port2 1.19e-11
L14 N13 Port2 2.01e-11
R14 N13 Port2 1.35e+01
.ENDS GRM022R61C102ME01
