*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/X7R(-55to125[deg])/1.00e-03[uF]/10[V]
* Murata P/N :GRM022R71A102KA12
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022R71A102KA12 Port1 Port2
C01 Port1 N01 1.04e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.77e-10
R03 N02 N03 2.57e-01
C04 N03 N04 9.74e-08
R04 N03 N04 1.81e+04
C05 N04 N05 1.59e-07
R05 N04 N05 1.11e+03
C06 N05 N06 1.44e-07
R06 N05 N06 1.69e+02
C07 N06 N07 1.01e-07
R07 N06 N07 2.28e+01
C08 N07 N08 7.50e-08
R08 N07 N08 3.09e+00
C09 N08 N09 8.05e-08
R09 N08 N09 3.87e-01
C10 N09 N10 3.12e-08
R10 N09 N10 1.72e-01
L11 N10 N11 2.58e-11
R11 N10 N11 3.89e-01
C12 N11 Port2 4.32e-11
L12 N11 Port2 7.40e-12
R12 N11 Port2 5.76e-01
.ENDS GRM022R71A102KA12
