*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/X5R(-55to85[deg])/3.30e-02[uF]/6.3[V]
* Murata P/N :GRM022R60J333ME15
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022R60J333ME15 Port1 Port2
C01 Port1 N01 2.96e-08
R01 Port1 N01 1.52e+09
L02 N01 N02 1.57e-10
R03 N02 N03 7.41e-02
C04 N03 N04 1.98e-06
R04 N03 N04 2.01e+03
C05 N04 N05 2.72e-06
R05 N04 N05 3.57e+02
C06 N05 N06 3.48e-06
R06 N05 N06 6.35e+01
C07 N06 N07 3.45e-06
R07 N06 N07 1.45e+01
C08 N07 N08 4.13e-06
R08 N07 N08 2.97e+00
C09 N08 N09 2.37e-06
R09 N08 N09 9.22e-01
C10 N09 N10 2.22e-06
R10 N09 N10 1.74e-01
C11 N10 N11 1.25e-06
R11 N10 N11 4.54e-02
L12 N11 N12 2.30e-11
R12 N11 N12 3.54e-01
L13 N12 N13 4.32e-11
R13 N12 N13 8.33e-02
C14 N13 Port2 5.47e-11
L14 N13 Port2 5.66e-12
R14 N13 Port2 6.55e-01
.ENDS GRM022R60J333ME15
