*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :5750M(2220)/X7R(-55to125[deg])/6.80e-02[uF]/1000[V]
* Murata P/N :GRM55DR73A683KW01
* Property : C = 6.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM55DR73A683KW01 Port1 Port2
C01 Port1 N01 6.92e-08
R01 Port1 N01 1.47e+09
L02 N01 N02 2.52e-10
R03 N02 N03 2.10e-02
C04 N03 N04 8.60e-06
R04 N03 N04 2.87e+02
C05 N04 N05 9.97e-06
R05 N04 N05 5.70e+01
C06 N05 N06 8.71e-06
R06 N05 N06 1.31e+01
C07 N06 N07 8.27e-06
R07 N06 N07 2.80e+00
C08 N07 N08 6.88e-06
R08 N07 N08 6.34e-01
C09 N08 N09 6.12e-06
R09 N08 N09 1.14e-01
C10 N09 N10 4.27e-06
R10 N09 N10 2.62e-02
L11 N10 N11 6.61e-11
R11 N10 N11 7.82e-02
C12 N11 N12 1.23e-07
L12 N11 N12 5.55e-11
R12 N11 N12 5.55e-02
C13 N12 N13 4.79e-08
L13 N12 N13 3.90e-11
R13 N12 N13 4.92e-02
C14 N13 Port2 8.62e-12
L14 N13 Port2 4.94e-10
R14 N13 Port2 2.31e+01
.ENDS GRM55DR73A683KW01
