*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/4.70e-03[uF]/100[V]
* Murata P/N :GCM155R72A472KA01
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R72A472KA01 Port1 Port2
C01 Port1 N01 4.92e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.86e-10
R03 N02 N03 9.30e-02
C04 N03 N04 6.64e-07
R04 N03 N04 2.65e+03
C05 N04 N05 8.29e-07
R05 N04 N05 2.36e+02
C06 N05 N06 7.20e-07
R06 N05 N06 2.84e+01
C07 N06 N07 5.72e-07
R07 N06 N07 3.31e+00
C08 N07 N08 4.80e-07
R08 N07 N08 4.74e-01
C09 N08 N09 2.74e-07
R09 N08 N09 1.29e-01
C10 N09 N10 1.01e-07
R10 N09 N10 4.62e-02
L11 N10 N11 5.25e-11
R11 N10 N11 2.85e-01
C12 N11 N12 6.09e-09
L12 N11 N12 2.25e-11
R12 N11 N12 8.27e-02
C13 N12 Port2 3.82e-12
L13 N12 Port2 8.84e-11
R13 N12 Port2 1.13e+01
.ENDS GCM155R72A472KA01
