*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R(-55to125[deg])/3.30e-03[uF]/100[V]
* Murata P/N :GCM155R72A332KA01
* Property : C = 3.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R72A332KA01 Port1 Port2
C01 Port1 N01 3.32e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.89e-10
R03 N02 N03 1.30e-01
C04 N03 N04 4.10e-07
R04 N03 N04 4.62e+03
C05 N04 N05 5.22e-07
R05 N04 N05 3.35e+02
C06 N05 N06 4.94e-07
R06 N05 N06 3.85e+01
C07 N06 N07 3.79e-07
R07 N06 N07 4.95e+00
C08 N07 N08 2.75e-07
R08 N07 N08 7.22e-01
C09 N08 N09 1.42e-07
R09 N08 N09 1.72e-01
C10 N09 N10 9.56e-08
R10 N09 N10 3.20e-02
L11 N10 N11 3.83e-11
R11 N10 N11 3.38e-01
C12 N11 N12 3.09e-09
L12 N11 N12 2.44e-11
R12 N11 N12 1.02e-01
C13 N12 Port2 3.30e-12
L13 N12 Port2 1.03e-10
R13 N12 Port2 1.45e+01
.ENDS GCM155R72A332KA01
