*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/6.80e-04[uF]/100[V]
* Murata P/N :GRM188R72A681KA01
* Property : C = 6.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R72A681KA01 Port1 Port2
C01 Port1 N01 6.94e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.70e-10
R03 N02 N03 2.94e-01
C04 N03 N04 7.21e-08
R04 N03 N04 2.11e+04
C05 N04 N05 1.03e-07
R05 N04 N05 1.60e+03
C06 N05 N06 1.06e-07
R06 N05 N06 1.67e+02
C07 N06 N07 7.66e-08
R07 N06 N07 2.84e+01
C08 N07 N08 4.92e-08
R08 N07 N08 4.28e+00
C09 N08 N09 2.27e-08
R09 N08 N09 8.03e-01
C10 N09 N10 6.23e-09
R10 N09 N10 2.92e-01
C11 N10 N11 5.96e-07
R11 N10 N11 1.93e-01
C12 N11 N12 8.77e-10
L12 N11 N12 2.31e-11
R12 N11 N12 2.08e-01
C13 N12 N13 3.86e-12
L13 N12 N13 2.24e-10
R13 N12 N13 1.26e+01
C14 N13 Port2 4.35e-12
L14 N13 Port2 8.88e-11
R14 N13 Port2 1.75e+01
.ENDS GRM188R72A681KA01
