*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/1.00e-02[uF]/50[V]
* Murata P/N :GRM188R11H103MA01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R11H103MA01 Port1 Port2
C01 Port1 N01 9.50e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 9.00e-11
R03 N02 N03 6.28e-02
C04 N03 N04 5.83e-07
R04 N03 N04 1.47e+01
C05 N04 N05 7.00e-07
R05 N04 N05 2.53e+00
C06 N05 N06 7.13e-06
R06 N05 N06 2.23e+00
C07 N06 N07 6.24e-07
R07 N06 N07 4.28e-01
C08 N07 N08 4.82e-07
R08 N07 N08 8.25e-02
C09 N08 N09 8.33e-07
R09 N08 N09 1.34e-02
L10 N09 N10 7.53e-11
R10 N09 N10 2.32e-01
C11 N10 N11 1.34e-07
L11 N10 N11 7.51e-12
R11 N10 N11 2.45e-02
C12 N11 N12 1.19e-08
L12 N11 N12 3.30e-11
R12 N11 N12 8.26e-02
C13 N12 N13 3.22e-11
L13 N12 N13 1.26e-10
R13 N12 N13 2.50e+00
C14 N13 Port2 1.52e-12
L14 N13 Port2 2.31e-10
R14 N13 Port2 2.94e+01
.ENDS GRM188R11H103MA01
