*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/4.70e-01[uF]/25[V]
* Murata P/N :GRM188R71E474KA12
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R71E474KA12 Port1 Port2
C01 Port1 N01 3.78e-07
R01 Port1 N01 1.06e+08
L02 N01 N02 1.62e-10
R03 N02 N03 9.62e-03
C04 N03 N04 1.31e-05
R04 N03 N04 3.58e+02
C05 N04 N05 1.54e-05
R05 N04 N05 3.34e+01
C06 N05 N06 1.35e-05
R06 N05 N06 4.30e+00
C07 N06 N07 1.08e-05
R07 N06 N07 6.44e-01
C08 N07 N08 9.19e-06
R08 N07 N08 9.51e-02
C09 N08 N09 6.01e-06
R09 N08 N09 1.68e-02
L10 N09 N10 2.42e-11
R10 N09 N10 1.24e-01
L11 N10 N11 1.76e-10
R11 N10 N11 5.20e-02
C12 N11 N12 1.57e-06
L12 N11 N12 3.01e-11
R12 N11 N12 1.33e-02
C13 N12 N13 8.07e-07
L13 N12 N13 2.88e-11
R13 N12 N13 1.73e-02
C14 N13 N14 1.09e-11
L14 N13 N14 4.82e-11
R14 N13 N14 9.44e+00
C15 N14 Port2 4.93e-12
L15 N14 Port2 6.21e-11
R15 N14 Port2 1.04e+01
.ENDS GRM188R71E474KA12
