*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/B(-25to85[deg])/4.70e-04[uF]/50[V]
* Murata P/N :GRM188B11H471KA01
* Property : C = 4.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188B11H471KA01 Port1 Port2
C01 Port1 N01 4.81e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.50e-10
R03 N02 N03 3.20e-01
C04 N03 N04 5.24e-08
R04 N03 N04 4.87e+04
C05 N04 N05 1.46e-07
R05 N04 N05 7.72e+03
C06 N05 N06 1.15e-07
R06 N05 N06 1.54e+03
C07 N06 N07 7.20e-08
R07 N06 N07 3.69e+02
C08 N07 N08 6.31e-08
R08 N07 N08 6.42e+01
C09 N08 N09 6.00e-08
R09 N08 N09 1.07e+01
C10 N09 N10 3.00e-08
R10 N09 N10 3.79e+00
C11 N10 N11 1.84e-08
R11 N10 N11 8.64e-01
C12 N11 N12 3.11e-09
R12 N11 N12 3.97e-01
C13 N12 N13 2.15e-08
R13 N12 N13 1.89e-01
C14 N13 N14 5.84e-10
L14 N13 N14 3.01e-11
R14 N13 N14 2.72e-01
C15 N14 N15 6.49e-12
L15 N14 N15 1.77e-10
R15 N14 N15 9.67e+00
C16 N15 Port2 2.94e-12
L16 N15 Port2 1.23e-10
R16 N15 Port2 1.80e+01
.ENDS GRM188B11H471KA01
