*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/2.20e-04[uF]/250[V]
* Murata P/N :GRM188R72E221KW07
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R72E221KW07 Port1 Port2
C01 Port1 N01 2.22e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 3.74e-10
R03 N02 N03 7.17e-01
C04 N03 N04 1.70e-08
R04 N03 N04 1.68e+05
C05 N04 N05 2.85e-08
R05 N04 N05 9.68e+03
C06 N05 N06 2.96e-08
R06 N05 N06 1.65e+03
C07 N06 N07 2.58e-08
R07 N06 N07 3.42e+02
C08 N07 N08 2.10e-08
R08 N07 N08 6.74e+01
C09 N08 N09 1.50e-08
R09 N08 N09 1.38e+01
C10 N09 N10 6.85e-09
R10 N09 N10 3.37e+00
C11 N10 N11 1.85e-09
R11 N10 N11 1.30e+00
C12 N11 N12 6.44e-10
L12 N11 N12 1.11e-11
R12 N11 N12 3.39e-01
C13 N12 Port2 2.49e-11
L13 N12 Port2 9.94e-11
R13 N12 Port2 4.25e+00
.ENDS GRM188R72E221KW07
