*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X6S(-55to105[deg])/4.70e+01[uF]/4[V]
* Murata P/N :GRM188C80G476ME01
* Property : C = 4.70e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188C80G476ME01 Port1 Port2
C01 Port1 N01 3.27e-05
R01 Port1 N01 1.06e+06
L02 N01 N02 1.76e-10
R03 N02 N03 1.90e-03
C04 N03 N04 1.48e-03
R04 N03 N04 4.31e+00
C05 N04 N05 2.11e-03
R05 N04 N05 2.88e-01
C06 N05 N06 2.14e-03
R06 N05 N06 3.06e-02
C07 N06 N07 2.41e-03
R07 N06 N07 2.41e-03
C08 N07 N08 1.96e-03
R08 N07 N08 2.73e-04
L09 N08 N09 3.21e-11
R09 N08 N09 9.56e-02
L10 N09 N10 8.18e-11
R10 N09 N10 2.66e-02
L11 N10 N11 3.54e-10
R11 N10 N11 1.01e-02
C12 N11 N12 3.17e-05
L12 N11 N12 1.94e-10
R12 N11 N12 2.74e-03
C13 N12 Port2 1.41e-11
L13 N12 Port2 2.36e-11
R13 N12 Port2 1.47e+00
.ENDS GRM188C80G476ME01
