*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/3.90e-02[uF]/50[V]
* Murata P/N :GRM188R71H393KA61
* Property : C = 3.90e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R71H393KA61 Port1 Port2
C01 Port1 N01 3.74e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.47e-10
R03 N02 N03 2.20e-02
C04 N03 N04 4.65e-06
R04 N03 N04 7.37e+02
C05 N04 N05 1.22e-05
R05 N04 N05 5.10e+01
C06 N05 N06 6.81e-06
R06 N05 N06 1.81e+01
C07 N06 N07 5.30e-06
R07 N06 N07 2.62e+00
C08 N07 N08 4.44e-06
R08 N07 N08 3.24e-01
C09 N08 N09 3.51e-06
R09 N08 N09 6.17e-02
C10 N09 N10 2.34e-06
R10 N09 N10 1.55e-02
L11 N10 N11 1.27e-11
R11 N10 N11 1.77e-01
L12 N11 N12 1.14e-10
R12 N11 N12 1.15e-01
C13 N12 N13 2.67e-07
L13 N12 N13 1.62e-11
R13 N12 N13 2.45e-02
C14 N13 N14 4.92e-08
L14 N13 N14 3.78e-11
R14 N13 N14 4.62e-02
C15 N14 N15 7.84e-12
L15 N14 N15 7.57e-11
R15 N14 N15 1.33e+01
C16 N15 Port2 2.82e-12
L16 N15 Port2 1.23e-10
R16 N15 Port2 2.09e+01
.ENDS GRM188R71H393KA61
