*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/3.30e-02[uF]/25[V]
* Murata P/N :GRM188R11E333KA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R11E333KA01 Port1 Port2
C01 Port1 N01 3.28e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.77e-11
R03 N02 N03 3.53e-02
C04 N03 N04 1.45e-06
R04 N03 N04 1.10e+01
C05 N04 N05 2.90e-06
R05 N04 N05 5.49e-01
C06 N05 N06 4.35e-06
R06 N05 N06 9.37e-02
C07 N06 N07 1.46e-06
R07 N06 N07 3.79e-02
L08 N07 N08 6.54e-11
R08 N07 N08 1.20e-01
L09 N08 N09 7.02e-12
R09 N08 N09 6.17e-02
C10 N09 N10 1.83e-07
L10 N09 N10 2.39e-11
R10 N09 N10 1.88e-02
C11 N10 N11 3.05e-08
L11 N10 N11 2.60e-11
R11 N10 N11 3.33e-02
C12 N11 N12 8.33e-12
L12 N11 N12 9.70e-11
R12 N11 N12 1.15e+01
C13 N12 N13 2.75e-12
L13 N12 N13 1.34e-10
R13 N12 N13 2.17e+01
C14 N13 Port2 1.82e-12
L14 N13 Port2 1.22e-10
R14 N13 Port2 1.00e+05
.ENDS GRM188R11E333KA01
