*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X5R(-55to85[deg])/4.70e-01[uF]/16[V]
* Murata P/N :GRM188R61C474MA12
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R61C474MA12 Port1 Port2
C01 Port1 N01 4.55e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 1.43e-10
R03 N02 N03 7.60e-03
C04 N03 N04 5.10e-05
R04 N03 N04 7.80e+01
C05 N04 N05 7.42e-05
R05 N04 N05 7.80e+00
C06 N05 N06 7.08e-05
R06 N05 N06 1.49e+00
C07 N06 N07 6.14e-05
R07 N06 N07 2.59e-01
C08 N07 N08 4.06e-05
R08 N07 N08 4.30e-02
C09 N08 N09 3.69e-05
R09 N08 N09 6.41e-03
L10 N09 N10 2.13e-11
R10 N09 N10 6.88e-02
L11 N10 N11 1.48e-10
R11 N10 N11 4.47e-02
C12 N11 N12 3.60e-06
L12 N11 N12 1.76e-11
R12 N11 N12 6.76e-03
C13 N12 N13 6.10e-07
L13 N12 N13 5.29e-11
R13 N12 N13 1.60e-02
C14 N13 N14 7.66e-12
L14 N13 N14 7.82e-11
R14 N13 N14 1.07e+01
C15 N14 Port2 3.05e-12
L15 N14 Port2 1.11e-10
R15 N14 Port2 2.09e+01
.ENDS GRM188R61C474MA12
