*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/1.00e-03[uF]/50[V]
* Murata P/N :GRM188R11H102MA01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R11H102MA01 Port1 Port2
C01 Port1 N01 1.05e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.08e-10
R03 N02 N03 2.31e-01
C04 N03 N04 1.12e-08
R04 N03 N04 2.84e+02
C05 N04 N05 7.67e-08
R05 N04 N05 2.59e+00
C06 N05 N06 3.51e-08
R06 N05 N06 9.06e-01
C07 N06 N07 2.46e-08
R07 N06 N07 1.69e-01
C08 N07 N08 1.17e-08
R08 N07 N08 1.48e-01
L09 N08 N09 1.01e-11
R09 N08 N09 2.27e-01
C10 N09 N10 7.47e-09
L10 N09 N10 1.02e-11
R10 N09 N10 9.46e-02
C11 N10 N11 7.05e-10
L11 N10 N11 3.97e-11
R11 N10 N11 3.06e-01
C12 N11 N12 5.33e-12
L12 N11 N12 1.41e-10
R12 N11 N12 1.49e+01
C13 N12 Port2 2.01e-12
L13 N12 Port2 1.88e-10
R13 N12 Port2 2.64e+01
.ENDS GRM188R11H102MA01
