*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X5R(-55to85[deg])/2.20e+01[uF]/10[V]
* Murata P/N :GRM187R61A226ME15
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM187R61A226ME15 Port1 Port2
C01 Port1 N01 1.73e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 2.05e-10
R03 N02 N03 2.77e-03
C04 N03 N04 1.05e-03
R04 N03 N04 3.88e+00
C05 N04 N05 1.30e-03
R05 N04 N05 3.87e-01
C06 N05 N06 1.51e-03
R06 N05 N06 5.02e-02
C07 N06 N07 2.36e-03
R07 N06 N07 6.08e-03
C08 N07 N08 1.07e-03
R08 N07 N08 1.93e-03
L09 N08 N09 3.79e-11
R09 N08 N09 1.20e-01
L10 N09 N10 7.55e-11
R10 N09 N10 2.66e-02
L11 N10 N11 2.96e-10
R11 N10 N11 1.12e-02
C12 N11 N12 4.68e-05
L12 N11 N12 7.42e-11
R12 N11 N12 1.74e-03
C13 N12 N13 3.45e-05
L13 N12 N13 5.44e-11
R13 N12 N13 1.73e-03
C14 N13 Port2 1.47e-11
L14 N13 Port2 4.08e-11
R14 N13 Port2 3.19e+00
.ENDS GRM187R61A226ME15
