*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X5R(-55to85[deg])/1.00e-02[uF]/50[V]
* Murata P/N :GRM188R61H103KA01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R61H103KA01 Port1 Port2
C01 Port1 N01 9.78e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.43e-10
R03 N02 N03 5.52e-02
C04 N03 N04 1.03e-06
R04 N03 N04 3.11e+03
C05 N04 N05 1.61e-06
R05 N04 N05 3.73e+02
C06 N05 N06 1.27e-06
R06 N05 N06 8.17e+01
C07 N06 N07 1.19e-06
R07 N06 N07 1.15e+01
C08 N07 N08 7.92e-07
R08 N07 N08 1.71e+00
C09 N08 N09 5.71e-07
R09 N08 N09 2.62e-01
C10 N09 N10 4.02e-07
R10 N09 N10 6.02e-02
L11 N10 N11 7.36e-11
R11 N10 N11 1.96e-01
L12 N11 N12 5.90e-12
R12 N11 N12 5.64e-02
C13 N12 N13 1.02e-07
L13 N12 N13 1.15e-11
R13 N12 N13 3.24e-02
C14 N13 N14 1.55e-08
L14 N13 N14 2.27e-11
R14 N13 N14 6.27e-02
C15 N14 Port2 5.32e-12
L15 N14 Port2 1.37e-10
R15 N14 Port2 1.69e+01
.ENDS GRM188R61H103KA01
