*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/R(-55to125[deg])/1.00e-01[uF]/50[V]
* Murata P/N :GRM188R11H104MA93
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R11H104MA93 Port1 Port2
C01 Port1 N01 1.01e-07
R01 Port1 N01 5.00e+09
L02 N01 N02 1.25e-10
R03 N02 N03 1.33e-02
C04 N03 N04 1.29e-05
R04 N03 N04 3.08e+02
C05 N04 N05 1.89e-05
R05 N04 N05 3.30e+01
C06 N05 N06 1.73e-05
R06 N05 N06 4.88e+00
C07 N06 N07 1.75e-05
R07 N06 N07 9.11e-01
C08 N07 N08 1.26e-05
R08 N07 N08 1.80e-01
C09 N08 N09 8.97e-06
R09 N08 N09 3.55e-02
C10 N09 N10 1.57e-05
R10 N09 N10 3.40e-03
L11 N10 N11 1.45e-10
R11 N10 N11 7.97e-02
L12 N11 N12 1.09e-11
R12 N11 N12 3.26e-02
C13 N12 N13 5.86e-07
L13 N12 N13 2.14e-11
R13 N12 N13 2.43e-02
C14 N13 N14 1.91e-07
L14 N13 N14 3.14e-11
R14 N13 N14 3.43e-02
C15 N14 N15 9.10e-12
L15 N14 N15 6.59e-11
R15 N14 N15 7.21e+00
C16 N15 Port2 2.99e-12
L16 N15 Port2 8.57e-11
R16 N15 Port2 2.66e+01
.ENDS GRM188R11H104MA93
