*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/B(-25to85[deg])/4.70e-02[uF]/25[V]
* Murata P/N :GRM188B11E473KA01
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188B11E473KA01 Port1 Port2
C01 Port1 N01 4.83e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.64e-10
R03 N02 N03 2.50e-02
C04 N03 N04 5.80e-06
R04 N03 N04 6.06e+02
C05 N04 N05 9.20e-06
R05 N04 N05 5.04e+01
C06 N05 N06 7.81e-06
R06 N05 N06 9.38e+00
C07 N06 N07 8.90e-06
R07 N06 N07 1.13e+00
C08 N07 N08 6.93e-06
R08 N07 N08 2.61e-01
C09 N08 N09 4.62e-06
R09 N08 N09 5.74e-02
C10 N09 N10 3.22e-06
R10 N09 N10 1.28e-02
L11 N10 N11 1.10e-10
R11 N10 N11 1.09e-01
C12 N11 N12 4.21e-07
L12 N11 N12 1.38e-11
R12 N11 N12 1.56e-02
C13 N12 N13 7.80e-08
L13 N12 N13 3.38e-11
R13 N12 N13 3.78e-02
C14 N13 N14 7.70e-12
L14 N13 N14 8.28e-11
R14 N13 N14 1.16e+01
C15 N14 Port2 2.59e-12
L15 N14 Port2 1.28e-10
R15 N14 Port2 2.05e+01
.ENDS GRM188B11E473KA01
