*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/1.00e-01[uF]/100[V]
* Murata P/N :GRM188R72A104MA35
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R72A104MA35 Port1 Port2
C01 Port1 N01 9.94e-08
R01 Port1 N01 5.00e+09
L02 N01 N02 1.68e-10
R03 N02 N03 1.35e-02
C04 N03 N04 1.39e-05
R04 N03 N04 2.85e+02
C05 N04 N05 2.35e-05
R05 N04 N05 2.85e+01
C06 N05 N06 1.88e-05
R06 N05 N06 7.00e+00
C07 N06 N07 1.68e-05
R07 N06 N07 9.47e-01
C08 N07 N08 1.50e-05
R08 N07 N08 1.51e-01
C09 N08 N09 1.07e-05
R09 N08 N09 2.98e-02
C10 N09 N10 1.31e-05
R10 N09 N10 3.83e-03
L11 N10 N11 1.43e-11
R11 N10 N11 8.15e-02
L12 N11 N12 1.08e-10
R12 N11 N12 7.26e-02
C13 N12 N13 4.76e-07
L13 N12 N13 2.94e-11
R13 N12 N13 3.05e-02
C14 N13 N14 1.58e-07
L14 N13 N14 2.63e-11
R14 N13 N14 2.63e-02
C15 N14 Port2 3.33e-12
L15 N14 Port2 1.14e-10
R15 N14 Port2 2.25e+01
.ENDS GRM188R72A104MA35
