*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/B(-25to85[deg])/3.30e-02[uF]/25[V]
* Murata P/N :GRM188B11E333KA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188B11E333KA01 Port1 Port2
C01 Port1 N01 3.20e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.74e-10
R03 N02 N03 3.30e-02
C04 N03 N04 3.68e-06
R04 N03 N04 1.08e+03
C05 N04 N05 4.73e-06
R05 N04 N05 1.19e+02
C06 N05 N06 3.93e-06
R06 N05 N06 1.92e+01
C07 N06 N07 4.24e-06
R07 N06 N07 1.88e+00
C08 N07 N08 4.52e-06
R08 N07 N08 3.41e-01
C09 N08 N09 2.55e-06
R09 N08 N09 1.34e-01
C10 N09 N10 1.65e-06
R10 N09 N10 2.99e-02
L11 N10 N11 3.18e-11
R11 N10 N11 6.43e-01
L12 N11 N12 7.43e-11
R12 N11 N12 1.78e-01
C13 N12 N13 1.61e-07
L13 N12 N13 2.45e-11
R13 N12 N13 2.24e-02
C14 N13 N14 3.25e-08
L14 N13 N14 2.74e-11
R14 N13 N14 4.07e-02
C15 N14 Port2 9.00e-12
L15 N14 Port2 7.48e-11
R15 N14 Port2 8.55e+00
.ENDS GRM188B11E333KA01
