*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/5.60e-03[uF]/50[V]
* Murata P/N :GRM188R71H562KA01
* Property : C = 5.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R71H562KA01 Port1 Port2
C01 Port1 N01 5.62e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 8.90e-11
R03 N02 N03 9.60e-02
C04 N03 N04 6.56e-07
R04 N03 N04 2.89e+03
C05 N04 N05 1.21e-06
R05 N04 N05 2.09e+02
C06 N05 N06 7.74e-07
R06 N05 N06 3.55e+01
C07 N06 N07 6.04e-07
R07 N06 N07 3.99e+00
C08 N07 N08 6.46e-07
R08 N07 N08 2.96e-01
C09 N08 N09 2.63e-06
R09 N08 N09 2.83e-01
C10 N09 N10 2.35e-07
R10 N09 N10 1.61e-01
C11 N10 N11 2.02e-07
R11 N10 N11 3.37e-02
L12 N11 N12 4.81e-11
R12 N11 N12 1.89e-01
C13 N12 N13 1.00e-07
L13 N12 N13 7.49e-12
R13 N12 N13 2.77e-02
C14 N13 N14 7.76e-09
L14 N13 N14 2.13e-11
R14 N13 N14 6.43e-02
C15 N14 N15 5.37e-12
L15 N14 N15 1.75e-10
R15 N14 N15 2.24e+01
C16 N15 Port2 1.62e-12
L16 N15 Port2 2.17e-10
R16 N15 Port2 2.60e+01
.ENDS GRM188R71H562KA01
