*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/2.20e+00[uF]/6.3[V]
* Murata P/N :GRM188R70J225KE15
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R70J225KE15 Port1 Port2
C01 Port1 N01 1.71e-06
R01 Port1 N01 2.27e+07
L02 N01 N02 1.81e-10
R03 N02 N03 5.94e-03
C04 N03 N04 1.31e-05
R04 N03 N04 5.45e+02
C05 N04 N05 4.06e-05
R05 N04 N05 9.88e+00
C06 N05 N06 3.98e-05
R06 N05 N06 9.97e-01
C07 N06 N07 3.39e-05
R07 N06 N07 1.18e-01
C08 N07 N08 2.49e-05
R08 N07 N08 1.59e-02
L09 N08 N09 3.31e-11
R09 N08 N09 6.97e-02
L10 N09 N10 2.13e-10
R10 N09 N10 3.21e-02
C11 N10 N11 4.31e-06
L11 N10 N11 5.61e-11
R11 N10 N11 7.22e-03
C12 N11 N12 4.44e-06
L12 N11 N12 2.54e-11
R12 N11 N12 7.74e-03
C13 N12 Port2 2.55e-12
L13 N12 Port2 9.30e-11
R13 N12 Port2 1.37e+01
.ENDS GRM188R70J225KE15
