*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/1.50e-02[uF]/100[V]
* Murata P/N :GRM188R72A153MAC4
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R72A153MAC4 Port1 Port2
C01 Port1 N01 1.46e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 2.14e-10
R03 N02 N03 4.75e-02
C04 N03 N04 1.41e-06
R04 N03 N04 2.61e+03
C05 N04 N05 2.13e-06
R05 N04 N05 2.28e+02
C06 N05 N06 2.39e-06
R06 N05 N06 3.22e+01
C07 N06 N07 2.20e-06
R07 N06 N07 7.04e+00
C08 N07 N08 1.53e-06
R08 N07 N08 1.34e+00
C09 N08 N09 8.33e-07
R09 N08 N09 2.92e-01
C10 N09 N10 5.59e-07
R10 N09 N10 3.67e-02
L11 N10 N11 1.04e-10
R11 N10 N11 2.55e-01
L12 N11 N12 2.15e-11
R12 N11 N12 1.16e-01
C13 N12 N13 9.55e-08
L13 N12 N13 1.50e-11
R13 N12 N13 2.58e-02
C14 N13 N14 2.08e-08
L14 N13 N14 3.04e-11
R14 N13 N14 6.74e-02
C15 N14 N15 9.86e-11
L15 N14 N15 5.27e-11
R15 N14 N15 5.61e-01
C16 N15 Port2 3.65e-12
L16 N15 Port2 9.32e-11
R16 N15 Port2 1.12e+01
.ENDS GRM188R72A153MAC4
