*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R(-55to125[deg])/4.70e-01[uF]/10[V]
* Murata P/N :GRM188R71A474KA61
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R71A474KA61 Port1 Port2
C01 Port1 N01 4.49e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 1.66e-10
R03 N02 N03 8.00e-03
C04 N03 N04 4.66e-05
R04 N03 N04 8.53e+01
C05 N04 N05 6.27e-05
R05 N04 N05 7.96e+00
C06 N05 N06 6.17e-05
R06 N05 N06 1.18e+00
C07 N06 N07 5.38e-05
R07 N06 N07 1.74e-01
C08 N07 N08 5.19e-05
R08 N07 N08 3.36e-02
C09 N08 N09 3.57e-05
R09 N08 N09 6.37e-03
C10 N09 N10 3.23e-05
R10 N09 N10 8.20e-04
L11 N10 N11 1.37e-10
R11 N10 N11 4.41e-02
L12 N11 N12 1.56e-11
R12 N11 N12 3.84e-02
C13 N12 N13 2.25e-06
L13 N12 N13 3.12e-11
R13 N12 N13 7.82e-03
C14 N13 N14 8.02e-07
L14 N13 N14 2.90e-11
R14 N13 N14 1.07e-02
C15 N14 N15 1.11e-11
L15 N14 N15 5.39e-11
R15 N14 N15 9.26e+00
C16 N15 Port2 3.47e-12
L16 N15 Port2 1.11e-10
R16 N15 Port2 1.73e+01
.ENDS GRM188R71A474KA61
