*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN6N2D00
* Property : L = 6.2[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN6N2D00 port1 port2
C1 port1 port2 2.27e-14
L2 port1 1 6.73e-9
R2 1 port2 6.00e-2
R3 port1 port2 2.53e+4
L4 port1 2 6.04e-8
R4 2 port2 2.49
L5 port1 3 1.12e-7
R5 3 port2 77.0
L6 port1 4 3.11e-7
R6 4 port2 3.60e+3
.ENDS LQW15AN6N2D00
*----------------------------------------------------------------------
