*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/CH(-55to125[deg])/9.40e-06[uF]/50[V]
* Murata P/N :GRM0332C1H9R4BA01
* Property : C = 9.40e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0332C1H9R4BA01 Port1 Port2
C01 Port1 N01 9.40e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 3.75e-11
R03 N02 N03 1.75e-01
L04 N03 N04 1.91e-11
R04 N03 N04 5.11e-01
C05 N04 N05 3.74e-11
L05 N04 N05 9.38e-12
R05 N04 N05 1.21e+00
C06 N05 Port2 5.16e-13
L06 N05 Port2 1.93e-10
R06 N05 Port2 1.00e+05
.ENDS GRM0332C1H9R4BA01
