*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G(-55to125[deg])/2.00e-06[uF]/50[V]
* Murata P/N :GRM0335C1H2R0BA01
* Property : C = 2.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H2R0BA01 Port1 Port2
C01 Port1 N01 2.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 6.79e-11
R03 N02 N03 2.70e-01
L04 N03 N04 1.79e-11
R04 N03 N04 6.64e-01
C05 N04 N05 2.42e-11
L05 N04 N05 9.93e-12
R05 N04 N05 1.55e+00
C06 N05 Port2 1.95e-12
L06 N05 Port2 1.05e-10
R06 N05 Port2 1.00e+05
.ENDS GRM0335C1H2R0BA01
