*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/CH(-55to125[deg])/6.80e-04[uF]/25[V]
* Murata P/N :GRM0332C1E681GA01
* Property : C = 6.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0332C1E681GA01 Port1 Port2
C01 Port1 N01 6.80e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.99e-10
R03 N02 N03 6.12e-02
C04 N03 N04 1.10e-08
L04 N03 N04 3.22e-12
R04 N03 N04 7.26e-02
C05 N04 N05 1.70e-09
L05 N04 N05 1.03e-11
R05 N04 N05 2.41e-01
C06 N05 N06 8.97e-11
L06 N05 N06 3.43e-11
R06 N05 N06 3.61e-01
C07 N06 Port2 3.78e-11
L07 N06 Port2 6.75e-12
R07 N06 Port2 2.03e+00
.ENDS GRM0332C1E681GA01
