*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/CH(-55to125[deg])/1.00e-03[uF]/25[V]
* Murata P/N :GRM0332C1E102JA01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0332C1E102JA01 Port1 Port2
C01 Port1 N01 1.01e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.77e-10
R03 N02 N03 9.26e-03
L04 N03 N04 5.22e-11
R04 N03 N04 4.33e-01
L05 N04 N05 2.70e-11
R05 N04 N05 2.70e-02
L06 N05 N06 6.87e-11
R06 N05 N06 1.01e-02
C07 N06 N07 1.77e-08
L07 N06 N07 3.33e-12
R07 N06 N07 7.40e-02
C08 N07 Port2 2.82e-09
L08 N07 Port2 1.06e-11
R08 N07 Port2 2.03e-01
.ENDS GRM0332C1E102JA01
