*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G(-55to125[deg])/1.50e-05[uF]/50[V]
* Murata P/N :GRM0335C1H150GA01
* Property : C = 1.50e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H150GA01 Port1 Port2
C01 Port1 N01 1.50e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.66e-10
R03 N02 N03 1.78e-01
L04 N03 N04 1.48e-11
R04 N03 N04 2.88e-01
C05 N04 N05 1.08e-11
L05 N04 N05 2.93e-11
R05 N04 N05 4.87e+00
C06 N05 Port2 4.90e-12
L06 N05 Port2 5.39e-11
R06 N05 Port2 1.00e+05
.ENDS GRM0335C1H150GA01
