*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G(-55to125[deg])/2.20e-04[uF]/50[V]
* Murata P/N :GRM0335C1H221GA01
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H221GA01 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.81e-10
R03 N02 N03 7.29e-02
L04 N03 N04 3.30e-11
R04 N03 N04 6.97e-01
C05 N04 N05 2.42e-09
L05 N04 N05 4.73e-12
R05 N04 N05 2.24e-01
C06 N05 N06 4.53e-10
L06 N05 N06 1.18e-11
R06 N05 N06 4.96e-01
C07 N06 Port2 1.44e-10
L07 N06 Port2 2.06e-12
R07 N06 Port2 3.58e-01
.ENDS GRM0335C1H221GA01
