*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/CH(-55to125[deg])/5.60e-06[uF]/25[V]
* Murata P/N :GRM0332C1E5R6DA01
* Property : C = 5.60e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0332C1E5R6DA01 Port1 Port2
C01 Port1 N01 5.60e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 5.29e-11
R03 N02 N03 2.05e-01
L04 N03 N04 5.92e-12
R04 N03 N04 3.07e-01
C05 N04 N05 1.96e-11
L05 N04 N05 1.62e-11
R05 N04 N05 9.48e-01
C06 N05 Port2 2.35e-13
L06 N05 Port2 1.89e-10
R06 N05 Port2 1.00e+05
.ENDS GRM0332C1E5R6DA01
