*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G(-55to125[deg])/1.60e-05[uF]/50[V]
* Murata P/N :GRM0335C1H160JA01
* Property : C = 1.60e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H160JA01 Port1 Port2
C01 Port1 N01 1.60e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 7.90e-12
R03 N02 N03 1.72e-01
L04 N03 N04 3.16e-11
R04 N03 N04 1.30e+00
L05 N04 N05 6.50e-13
R05 N04 N05 5.12e-03
C06 N05 N06 6.04e-10
L06 N05 N06 1.68e-12
R06 N05 N06 1.18e+00
C07 N06 N07 7.47e-11
L07 N06 N07 1.16e-11
R07 N06 N07 4.22e+00
C08 N07 N08 3.73e-11
L08 N07 N08 5.54e-12
R08 N07 N08 1.11e+00
C09 N08 Port2 7.61e-13
L09 N08 Port2 1.92e-10
R09 N08 Port2 1.00e+05
.ENDS GRM0335C1H160JA01
