*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN5N1D1Z
* Property : L = 5.1[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN5N1D1Z port1 port2
C1 port1 port2 2.81e-14
L2 port1 1 5.10e-9
R2 1 port2 3.60e-2
R3 port1 port2 1.61e+4
L4 port1 2 6.30e-8
R4 2 port2 12.4
L5 port1 3 1.46e-7
R5 3 port2 271
.ENDS LQW15AN5N1D1Z
*----------------------------------------------------------------------
