*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN3N8C1Z
* Property : L = 3.8[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN3N8C1Z port1 port2
C1 port1 port2 3.53e-14
L2 port1 1 3.61e-9
R2 1 port2 2.80e-2
R3 port1 port2 7.04e+3
L4 port1 2 1.00e-7
R4 2 port2 47.0
L5 port1 3 1.76e-7
R5 3 port2 688
.ENDS LQW15AN3N8C1Z
*----------------------------------------------------------------------
