*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/R(-55to125[deg])/1.00e+00[uF]/10[V]
* Murata P/N :GCM21BR11A105KA01
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR11A105KA01 Port1 Port2
C01 Port1 N01 8.95e-07
R01 Port1 N01 5.00e+08
L02 N01 N02 1.68e-10
R03 N02 N03 4.69e-03
C04 N03 N04 1.25e-04
R04 N03 N04 1.23e+01
C05 N04 N05 1.21e-04
R05 N04 N05 1.71e+00
C06 N05 N06 8.20e-05
R06 N05 N06 3.27e-01
C07 N06 N07 7.46e-05
R07 N06 N07 3.22e-02
C08 N07 N08 1.29e-04
R08 N07 N08 3.39e-03
L09 N08 N09 1.77e-11
R09 N08 N09 8.09e-02
L10 N09 N10 2.19e-10
R10 N09 N10 4.42e-02
C11 N10 N11 3.33e-06
L11 N10 N11 4.91e-11
R11 N10 N11 1.84e-02
C12 N11 N12 1.12e-06
L12 N11 N12 7.00e-11
R12 N11 N12 2.09e-02
C13 N12 N13 1.56e-11
L13 N12 N13 5.41e-11
R13 N12 N13 4.97e+00
C14 N13 Port2 4.13e-12
L14 N13 Port2 6.83e-11
R14 N13 Port2 1.42e+01
.ENDS GCM21BR11A105KA01
