*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.50e-02[uF]/100[V]
* Murata P/N :GCM21BR72A153KA01
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR72A153KA01 Port1 Port2
C01 Port1 N01 1.57e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.70e-10
R03 N02 N03 3.91e-02
C04 N03 N04 2.31e-06
R04 N03 N04 1.28e+03
C05 N04 N05 4.69e-06
R05 N04 N05 1.54e+02
C06 N05 N06 2.77e-06
R06 N05 N06 4.55e+01
C07 N06 N07 2.32e-06
R07 N06 N07 5.86e+00
C08 N07 N08 2.36e-06
R08 N07 N08 1.02e+00
C09 N08 N09 1.38e-06
R09 N08 N09 2.30e-01
C10 N09 N10 9.11e-07
R10 N09 N10 5.13e-02
C11 N10 N11 1.17e-06
R11 N10 N11 1.28e-02
L12 N11 N12 9.99e-11
R12 N11 N12 2.02e-01
C13 N12 N13 8.84e-08
L13 N12 N13 2.38e-11
R13 N12 N13 6.42e-02
C14 N13 N14 1.93e-08
L14 N13 N14 4.69e-11
R14 N13 N14 1.10e-01
C15 N14 N15 1.37e-11
L15 N14 N15 1.11e-10
R15 N14 N15 8.90e+00
C16 N15 Port2 1.82e-12
L16 N15 Port2 1.60e-10
R16 N15 Port2 1.47e+01
.ENDS GCM21BR72A153KA01
