*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/6.80e-03[uF]/250[V]
* Murata P/N :GCM21AR72E682KX01
* Property : C = 6.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21AR72E682KX01 Port1 Port2
C01 Port1 N01 7.09e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 3.58e-10
R03 N02 N03 9.89e-02
C04 N03 N04 6.12e-07
R04 N03 N04 2.87e+03
C05 N04 N05 7.59e-07
R05 N04 N05 4.64e+02
C06 N05 N06 6.45e-07
R06 N05 N06 9.96e+01
C07 N06 N07 5.99e-07
R07 N06 N07 1.84e+01
C08 N07 N08 4.97e-07
R08 N07 N08 3.57e+00
C09 N08 N09 3.21e-07
R09 N08 N09 7.73e-01
C10 N09 N10 2.34e-07
R10 N09 N10 9.50e-02
L11 N10 N11 4.48e-11
R11 N10 N11 2.06e-01
L12 N11 N12 3.01e-11
R12 N11 N12 9.47e-02
C13 N12 N13 7.82e-08
L13 N12 N13 4.79e-12
R13 N12 N13 2.26e-02
C14 N13 N14 1.16e-08
L14 N13 N14 1.55e-11
R14 N13 N14 6.95e-02
C15 N14 Port2 2.08e-11
L15 N14 Port2 1.01e-10
R15 N14 Port2 5.16e+00
.ENDS GCM21AR72E682KX01
