*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/R(-55to125[deg])/2.20e-01[uF]/25[V]
* Murata P/N :GCM21BR11E224KA01
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR11E224KA01 Port1 Port2
C01 Port1 N01 2.22e-07
R01 Port1 N01 2.27e+09
L02 N01 N02 1.22e-10
R03 N02 N03 8.63e-03
C04 N03 N04 2.55e-05
R04 N03 N04 1.56e+02
C05 N04 N05 2.82e-05
R05 N04 N05 1.52e+01
C06 N05 N06 2.82e-05
R06 N05 N06 1.56e+00
C07 N06 N07 2.53e-05
R07 N06 N07 2.10e-01
C08 N07 N08 2.35e-05
R08 N07 N08 2.84e-02
C09 N08 N09 3.66e-05
R09 N08 N09 4.58e-03
L10 N09 N10 2.68e-11
R10 N09 N10 1.12e-01
L11 N10 N11 1.93e-10
R11 N10 N11 7.21e-02
C12 N11 N12 1.23e-06
L12 N11 N12 3.20e-11
R12 N11 N12 2.59e-02
C13 N12 N13 2.96e-07
L13 N12 N13 6.78e-11
R13 N12 N13 3.55e-02
C14 N13 N14 1.91e-11
L14 N13 N14 4.53e-11
R14 N13 N14 4.45e+00
C15 N14 Port2 2.49e-12
L15 N14 Port2 1.10e-10
R15 N14 Port2 1.83e+01
.ENDS GCM21BR11E224KA01
