*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/R(-55to125[deg])/1.00e-01[uF]/50[V]
* Murata P/N :GCM21BR11H104KA01
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR11H104KA01 Port1 Port2
C01 Port1 N01 1.02e-07
R01 Port1 N01 5.00e+09
L02 N01 N02 1.68e-10
R03 N02 N03 1.50e-02
C04 N03 N04 1.18e-05
R04 N03 N04 3.37e+02
C05 N04 N05 1.87e-05
R05 N04 N05 2.67e+01
C06 N05 N06 1.63e-05
R06 N05 N06 4.54e+00
C07 N06 N07 1.55e-05
R07 N06 N07 7.04e-01
C08 N07 N08 1.33e-05
R08 N07 N08 1.10e-01
C09 N08 N09 6.83e-06
R09 N08 N09 2.60e-02
L10 N09 N10 1.07e-10
R10 N09 N10 8.48e-02
L11 N10 N11 1.24e-11
R11 N10 N11 6.15e-02
C12 N11 N12 4.33e-07
L12 N11 N12 3.43e-11
R12 N11 N12 3.68e-02
C13 N12 N13 9.55e-08
L13 N12 N13 6.46e-11
R13 N12 N13 4.77e-02
C14 N13 N14 8.92e-12
L14 N13 N14 8.71e-11
R14 N13 N14 9.68e+00
C15 N14 Port2 3.01e-12
L15 N14 Port2 1.23e-10
R15 N14 Port2 2.06e+01
.ENDS GCM21BR11H104KA01
