*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/4.70e-02[uF]/100[V]
* Murata P/N :GCM21BR72A473KA01
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR72A473KA01 Port1 Port2
C01 Port1 N01 4.65e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.24e-10
R03 N02 N03 2.09e-02
C04 N03 N04 6.23e-06
R04 N03 N04 5.93e+02
C05 N04 N05 8.45e-06
R05 N04 N05 6.21e+01
C06 N05 N06 7.31e-06
R06 N05 N06 8.57e+00
C07 N06 N07 6.19e-06
R07 N06 N07 1.08e+00
C08 N07 N08 5.58e-06
R08 N07 N08 1.51e-01
C09 N08 N09 4.51e-06
R09 N08 N09 4.27e-02
C10 N09 N10 3.21e-06
R10 N09 N10 1.31e-02
L11 N10 N11 1.07e-10
R11 N10 N11 1.29e-01
C12 N11 N12 1.73e-07
L12 N11 N12 4.21e-11
R12 N11 N12 6.14e-02
C13 N12 N13 4.38e-08
L13 N12 N13 4.53e-11
R13 N12 N13 5.28e-02
C14 N13 N14 1.39e-11
L14 N13 N14 8.54e-11
R14 N13 N14 7.19e+00
C15 N14 Port2 2.51e-12
L15 N14 Port2 1.46e-10
R15 N14 Port2 2.70e+01
.ENDS GCM21BR72A473KA01
