*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.50e-02[uF]/250[V]
* Murata P/N :GCM21BR72E153KX03
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR72E153KX03 Port1 Port2
C01 Port1 N01 1.56e-08
R01 Port1 N01 6.67e+09
L02 N01 N02 2.98e-10
R03 N02 N03 6.37e-02
C04 N03 N04 1.68e-06
R04 N03 N04 1.23e+03
C05 N04 N05 1.84e-06
R05 N04 N05 2.88e+02
C06 N05 N06 1.64e-06
R06 N05 N06 6.22e+01
C07 N06 N07 1.51e-06
R07 N06 N07 1.36e+01
C08 N07 N08 1.10e-06
R08 N07 N08 2.89e+00
C09 N08 N09 1.47e-06
R09 N08 N09 7.06e-01
C10 N09 N10 5.98e-07
R10 N09 N10 2.78e-01
L11 N10 N11 6.05e-11
R11 N10 N11 1.43e-01
L12 N11 N12 3.41e-11
R12 N11 N12 4.37e-02
C13 N12 N13 3.46e-07
L13 N12 N13 3.73e-12
R13 N12 N13 9.18e-03
C14 N13 N14 4.28e-08
L14 N13 N14 1.71e-11
R14 N13 N14 4.02e-02
C15 N14 Port2 1.01e-11
L15 N14 Port2 2.35e-10
R15 N14 Port2 1.34e+01
.ENDS GCM21BR72E153KX03
