*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/2.20e-01[uF]/50[V]
* Murata P/N :GCM21BR71H224KA37
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BR71H224KA37 Port1 Port2
C01 Port1 N01 2.22e-07
R01 Port1 N01 2.27e+09
L02 N01 N02 1.52e-10
R03 N02 N03 8.39e-03
C04 N03 N04 2.58e-05
R04 N03 N04 1.54e+02
C05 N04 N05 3.81e-05
R05 N04 N05 1.04e+01
C06 N05 N06 3.20e-05
R06 N05 N06 1.65e+00
C07 N06 N07 3.13e-05
R07 N06 N07 1.66e-01
C08 N07 N08 2.62e-05
R08 N07 N08 3.09e-02
C09 N08 N09 2.08e-05
R09 N08 N09 8.39e-03
L10 N09 N10 1.85e-11
R10 N09 N10 5.83e-02
L11 N10 N11 1.47e-10
R11 N10 N11 5.48e-02
C12 N11 N12 9.10e-07
L12 N11 N12 3.57e-11
R12 N11 N12 3.27e-02
C13 N12 N13 2.59e-07
L13 N12 N13 5.28e-11
R13 N12 N13 3.29e-02
C14 N13 N14 1.69e-11
L14 N13 N14 5.63e-11
R14 N13 N14 6.25e+00
C15 N14 Port2 2.61e-12
L15 N14 Port2 1.28e-10
R15 N14 Port2 2.05e+01
.ENDS GCM21BR71H224KA37
