*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X8M(-55to150[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GCM21BM8EE106KE08
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BM8EE106KE08 Port1 Port2
C01 Port1 N01 7.34e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 7.35e-11
R03 N02 N03 2.91e-03
C04 N03 N04 4.22e-04
R04 N03 N04 6.10e+00
C05 N04 N05 3.51e-04
R05 N04 N05 8.98e-01
C06 N05 N06 3.44e-04
R06 N05 N06 1.03e-01
C07 N06 N07 2.68e-04
R07 N06 N07 1.40e-02
C08 N07 N08 3.60e-04
R08 N07 N08 1.70e-03
L09 N08 N09 7.92e-12
R09 N08 N09 5.09e-02
L10 N09 N10 3.99e-11
R10 N09 N10 3.82e-02
L11 N10 N11 2.62e-10
R11 N10 N11 1.73e-02
C12 N11 N12 1.88e-05
L12 N11 N12 7.60e-11
R12 N11 N12 6.40e-03
C13 N12 N13 9.91e-06
L13 N12 N13 6.53e-11
R13 N12 N13 6.17e-03
C14 N13 N14 6.92e-12
L14 N13 N14 8.72e-11
R14 N13 N14 1.51e+01
C15 N14 Port2 9.98e-13
L15 N14 Port2 1.36e-10
R15 N14 Port2 4.68e+02
.ENDS GCM21BM8EE106KE08
