*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/2.20e-01[uF]/16[V]
* Murata P/N :GCM219R71C224KA37
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM219R71C224KA37 Port1 Port2
C01 Port1 N01 2.13e-07
R01 Port1 N01 2.27e+09
L02 N01 N02 1.05e-10
R03 N02 N03 1.10e-02
C04 N03 N04 2.22e-05
R04 N03 N04 1.79e+02
C05 N04 N05 3.48e-05
R05 N04 N05 1.79e+01
C06 N05 N06 3.28e-05
R06 N05 N06 4.01e+00
C07 N06 N07 2.73e-05
R07 N06 N07 1.01e+00
C08 N07 N08 2.16e-05
R08 N07 N08 1.58e-01
C09 N08 N09 1.67e-05
R09 N08 N09 2.47e-02
L10 N09 N10 1.15e-10
R10 N09 N10 7.05e-02
L11 N10 N11 2.53e-11
R11 N10 N11 6.77e-02
C12 N11 N12 1.28e-06
L12 N11 N12 2.26e-11
R12 N11 N12 1.34e-02
C13 N12 N13 2.09e-07
L13 N12 N13 6.04e-11
R13 N12 N13 3.44e-02
C14 N13 N14 1.05e-11
L14 N13 N14 1.09e-10
R14 N13 N14 1.02e+01
C15 N14 Port2 2.01e-12
L15 N14 Port2 1.65e-10
R15 N14 Port2 2.30e+01
.ENDS GCM219R71C224KA37
