*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7S(-55to125[deg])/1.00e+00[uF]/100[V]
* Murata P/N :GCM21BC72A105ME35
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BC72A105ME35 Port1 Port2
C01 Port1 N01 9.39e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 2.34e-10
R03 N02 N03 5.88e-03
C04 N03 N04 1.40e-04
R04 N03 N04 4.00e+00
C05 N04 N05 1.10e-04
R05 N04 N05 8.75e-01
C06 N05 N06 1.11e-04
R06 N05 N06 1.41e-01
C07 N06 N07 1.01e-04
R07 N06 N07 2.35e-02
C08 N07 N08 7.32e-05
R08 N07 N08 6.12e-03
L09 N08 N09 1.35e-11
R09 N08 N09 8.56e-02
L10 N09 N10 1.89e-10
R10 N09 N10 3.87e-02
L11 N10 N11 1.83e-11
R11 N10 N11 3.51e-02
C12 N11 N12 2.97e-06
L12 N11 N12 5.53e-11
R12 N11 N12 1.43e-02
C13 N12 N13 1.39e-06
L13 N12 N13 5.49e-11
R13 N12 N13 1.53e-02
C14 N13 Port2 1.93e-11
L14 N13 Port2 6.74e-11
R14 N13 Port2 5.47e+00
.ENDS GCM21BC72A105ME35
