*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GCM219R71C105KA37
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM219R71C105KA37 Port1 Port2
C01 Port1 N01 9.77e-07
R01 Port1 N01 5.00e+08
L02 N01 N02 1.60e-10
R03 N02 N03 4.97e-03
C04 N03 N04 2.90e-05
R04 N03 N04 2.38e+02
C05 N04 N05 1.42e-04
R05 N04 N05 4.67e+00
C06 N05 N06 1.04e-04
R06 N05 N06 8.44e-01
C07 N06 N07 9.22e-05
R07 N06 N07 9.44e-02
C08 N07 N08 7.86e-05
R08 N07 N08 1.22e-02
C09 N08 N09 1.70e-04
R09 N08 N09 1.31e-03
L10 N09 N10 2.13e-11
R10 N09 N10 7.67e-02
L11 N10 N11 1.94e-10
R11 N10 N11 3.90e-02
C12 N11 N12 4.33e-06
L12 N11 N12 3.41e-11
R12 N11 N12 9.81e-03
C13 N12 N13 1.31e-06
L13 N12 N13 5.07e-11
R13 N12 N13 1.48e-02
C14 N13 N14 1.11e-11
L14 N13 N14 6.82e-11
R14 N13 N14 7.65e+00
C15 N14 Port2 5.83e-12
L15 N14 Port2 5.57e-11
R15 N14 Port2 1.68e+01
.ENDS GCM219R71C105KA37
