*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7S(-55to125[deg])/4.70e+00[uF]/35[V]
* Murata P/N :GCM21BC7YA475KE36
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM21BC7YA475KE36 Port1 Port2
C01 Port1 N01 3.50e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.84e-10
R03 N02 N03 3.54e-03
C04 N03 N04 2.26e-04
R04 N03 N04 1.20e+01
C05 N04 N05 2.20e-04
R05 N04 N05 1.69e+00
C06 N05 N06 2.05e-04
R06 N05 N06 2.43e-01
C07 N06 N07 1.78e-04
R07 N06 N07 3.71e-02
C08 N07 N08 1.19e-04
R08 N07 N08 7.36e-03
L09 N08 N09 1.52e-11
R09 N08 N09 8.41e-02
L10 N09 N10 2.42e-11
R10 N09 N10 2.24e-02
L11 N10 N11 2.63e-10
R11 N10 N11 2.21e-02
C12 N11 N12 7.53e-06
L12 N11 N12 8.35e-11
R12 N11 N12 1.19e-02
C13 N12 N13 6.60e-06
L13 N12 N13 4.41e-11
R13 N12 N13 8.62e-03
C14 N13 Port2 6.81e-12
L14 N13 Port2 6.51e-11
R14 N13 Port2 1.49e+01
.ENDS GCM21BC7YA475KE36
