*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :5750M(2220)/U2J(-55to125[deg])/1.00e-02[uF]/1000[V]
* Murata P/N :GCM55D7U3A103JX01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM55D7U3A103JX01 Port1 Port2
C01 Port1 N01 9.75e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 1.04e-11
R03 N02 N03 3.15e-03
L04 N03 N04 1.72e-10
R04 N03 N04 4.49e-01
L05 N04 N05 1.93e-11
R05 N04 N05 2.25e-03
C06 N05 N06 1.38e-08
L06 N05 N06 1.48e-10
R06 N05 N06 1.31e+00
C07 N06 N07 9.30e-09
L07 N06 N07 7.94e-11
R07 N06 N07 1.04e+00
C08 N07 N08 1.87e-08
L08 N07 N08 1.79e-11
R08 N07 N08 4.10e-01
C09 N08 N09 1.25e-08
L09 N08 N09 1.64e-11
R09 N08 N09 3.74e-01
C10 N09 Port2 3.80e-12
L10 N09 Port2 3.15e-10
R10 N09 Port2 1.86e+02
.ENDS GCM55D7U3A103JX01
