*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :5750M(2220)/U2J(-55to125[deg])/4.70e-02[uF]/630[V]
* Murata P/N :GCM55D7U2J473JX01
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM55D7U2J473JX01 Port1 Port2
C01 Port1 N01 4.64e-08
R01 Port1 N01 2.13e+10
L02 N01 N02 8.09e-12
R03 N02 N03 2.14e-03
L04 N03 N04 1.58e-10
R04 N03 N04 2.43e-01
L05 N04 N05 1.74e-11
R05 N04 N05 3.00e-04
C06 N05 N06 5.44e-08
L06 N05 N06 2.00e-10
R06 N05 N06 6.25e-01
C07 N06 N07 4.62e-08
L07 N06 N07 9.27e-11
R07 N06 N07 4.56e-01
C08 N07 N08 4.56e-08
L08 N07 N08 4.32e-11
R08 N07 N08 1.99e-01
C09 N08 N09 4.22e-08
L09 N08 N09 2.70e-11
R09 N08 N09 1.87e-01
C10 N09 N10 1.08e-10
L10 N09 N10 2.00e-11
R10 N09 N10 9.10e-01
C11 N10 Port2 4.25e-12
L11 N10 Port2 2.58e-10
R11 N10 Port2 2.31e+02
.ENDS GCM55D7U2J473JX01
