*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :5750M(2220)/U2J(-55to125[deg])/3.90e-02[uF]/630[V]
* Murata P/N :GCM55D7U2J393JX01
* Property : C = 3.90e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM55D7U2J393JX01 Port1 Port2
C01 Port1 N01 3.84e-08
R01 Port1 N01 2.56e+10
L02 N01 N02 1.71e-11
R03 N02 N03 2.62e-03
L04 N03 N04 1.64e-10
R04 N03 N04 1.96e-01
L05 N04 N05 2.76e-11
R05 N04 N05 7.37e-04
C06 N05 N06 6.22e-08
L06 N05 N06 1.27e-10
R06 N05 N06 5.86e-01
C07 N06 N07 3.72e-08
L07 N06 N07 7.78e-11
R07 N06 N07 4.65e-01
C08 N07 N08 7.77e-08
L08 N07 N08 1.64e-11
R08 N07 N08 1.17e-01
C09 N08 N09 4.32e-08
L09 N08 N09 1.78e-11
R09 N08 N09 1.08e-01
C10 N09 Port2 4.02e-12
L10 N09 Port2 3.85e-10
R10 N09 Port2 2.95e+02
.ENDS GCM55D7U2J393JX01
