*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/2.70e-04[uF]/100[V]
* Murata P/N :GRM2162C2A271JA01
* Property : C = 2.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2162C2A271JA01 Port1 Port2
C01 Port1 N01 2.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 5.08e-11
R03 N02 N03 6.90e-02
L04 N03 N04 5.69e-11
R04 N03 N04 1.90e+00
C05 N04 N05 1.04e-09
L05 N04 N05 1.98e-11
R05 N04 N05 9.94e-01
C06 N05 N06 3.04e-10
L06 N05 N06 2.35e-11
R06 N05 N06 1.31e+00
C07 N06 Port2 1.29e-12
L07 N06 Port2 3.02e-10
R07 N06 Port2 3.39e+02
.ENDS GRM2162C2A271JA01
