*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.50e-03[uF]/50[V]
* Murata P/N :GRM2165C1H152JA01
* Property : C = 1.50e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2165C1H152JA01 Port1 Port2
C01 Port1 N01 1.48e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.47e-10
R03 N02 N03 1.55e-02
L04 N03 N04 8.91e-11
R04 N03 N04 2.48e-02
C05 N04 N05 7.54e-09
L05 N04 N05 1.26e-11
R05 N04 N05 1.61e-01
C06 N05 N06 1.30e-09
L06 N05 N06 2.39e-11
R06 N05 N06 3.63e-01
C07 N06 N07 5.86e-12
L07 N06 N07 5.81e-11
R07 N06 N07 6.14e-01
C08 N07 Port2 9.19e-13
L08 N07 Port2 2.80e-10
R08 N07 Port2 1.00e+05
.ENDS GRM2165C1H152JA01
