*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/SL(-55to125[deg])/8.20e-02[uF]/10[V]
* Murata P/N :GRM21B1X1A823JA01
* Property : C = 8.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21B1X1A823JA01 Port1 Port2
C01 Port1 N01 8.39e-08
R01 Port1 N01 6.10e+09
L02 N01 N02 1.99e-10
R03 N02 N03 3.66e-03
L04 N03 N04 1.54e-10
R04 N03 N04 1.04e-01
L05 N04 N05 9.71e-11
R05 N04 N05 3.25e-03
C06 N05 N06 2.78e-07
L06 N05 N06 4.73e-11
R06 N05 N06 9.82e-02
C07 N06 N07 1.48e-07
L07 N06 N07 4.14e-11
R07 N06 N07 9.16e-02
C08 N07 Port2 1.66e-12
L08 N07 Port2 1.50e-10
R08 N07 Port2 4.52e+01
.ENDS GRM21B1X1A823JA01
