*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/2.20e-04[uF]/250[V]
* Murata P/N :GRM21A5C2E221FW01
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21A5C2E221FW01 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.38e-10
R03 N02 N03 7.95e-02
C04 N03 N04 1.06e-09
L04 N03 N04 1.65e-11
R04 N03 N04 9.37e-01
C05 N04 N05 2.18e-10
L05 N04 N05 2.88e-11
R05 N04 N05 2.00e+00
C06 N05 N06 1.05e-09
L06 N05 N06 2.91e-12
R06 N05 N06 2.71e-01
C07 N06 N07 4.85e-10
L07 N06 N07 3.45e-12
R07 N06 N07 4.25e-01
C08 N07 Port2 1.01e-12
L08 N07 Port2 3.15e-10
R08 N07 Port2 8.32e+01
.ENDS GRM21A5C2E221FW01
