*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/5.60e-03[uF]/100[V]
* Murata P/N :GRM2192C2A562JA01
* Property : C = 5.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2192C2A562JA01 Port1 Port2
C01 Port1 N01 5.54e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.19e-10
R03 N02 N03 6.08e-03
L04 N03 N04 1.80e-11
R04 N03 N04 7.53e-01
L05 N04 N05 8.50e-11
R05 N04 N05 2.64e-01
L06 N05 N06 1.04e-10
R06 N05 N06 1.16e-02
C07 N06 N07 2.35e-08
L07 N06 N07 2.79e-11
R07 N06 N07 3.06e-01
C08 N07 N08 8.88e-09
L08 N07 N08 2.99e-11
R08 N07 N08 4.04e-01
C09 N08 N09 8.22e-12
L09 N08 N09 4.00e-11
R09 N08 N09 1.43e+01
C10 N09 Port2 1.38e-12
L10 N09 Port2 2.18e-10
R10 N09 Port2 1.00e+05
.ENDS GRM2192C2A562JA01
