*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.80e-05[uF]/630[V]
* Murata P/N :GRM21A5C2J180FWA1
* Property : C = 1.80e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21A5C2J180FWA1 Port1 Port2
C01 Port1 N01 1.80e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.02e-10
R03 N02 N03 2.42e-01
C04 N03 N04 2.78e-06
R04 N03 N04 1.07e+02
C05 N04 N05 2.08e-10
L05 N04 N05 5.62e-12
R05 N04 N05 2.42e+00
C06 N05 N06 4.09e-12
L06 N05 N06 1.28e-10
R06 N05 N06 5.58e+01
C07 N06 Port2 9.28e-13
L07 N06 Port2 3.31e-10
R07 N06 Port2 9.61e+01
.ENDS GRM21A5C2J180FWA1
