*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/3.30e-03[uF]/50[V]
* Murata P/N :GRM2165C1H332JA01
* Property : C = 3.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2165C1H332JA01 Port1 Port2
C01 Port1 N01 3.25e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.32e-10
R03 N02 N03 1.20e-02
L04 N03 N04 7.89e-11
R04 N03 N04 4.72e-01
L05 N04 N05 6.29e-11
R05 N04 N05 1.11e-02
C06 N05 N06 1.43e-08
L06 N05 N06 2.65e-11
R06 N05 N06 2.73e-01
C07 N06 N07 4.19e-09
L07 N06 N07 3.80e-11
R07 N06 N07 4.18e-01
C08 N07 N08 2.40e-09
L08 N07 N08 2.34e-11
R08 N07 N08 1.70e-01
C09 N08 N09 3.85e-11
L09 N08 N09 1.22e-11
R09 N08 N09 3.46e-01
C10 N09 Port2 2.17e-12
L10 N09 Port2 1.12e-10
R10 N09 Port2 1.00e+05
.ENDS GRM2165C1H332JA01
