*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.00e-04[uF]/630[V]
* Murata P/N :GRM21A5C2J101JWA1
* Property : C = 1.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21A5C2J101JWA1 Port1 Port2
C01 Port1 N01 1.00e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.00e-10
R03 N02 N03 1.18e-01
C04 N03 N04 7.87e-08
R04 N03 N04 1.50e-01
C05 N04 N05 6.46e-10
L05 N04 N05 1.38e-11
R05 N04 N05 9.47e-01
C06 N05 N06 8.49e-11
L06 N05 N06 3.94e-11
R06 N05 N06 2.69e+00
C07 N06 N07 4.51e-11
L07 N06 N07 2.05e-11
R07 N06 N07 1.88e+00
C08 N07 Port2 1.19e-12
L08 N07 Port2 2.76e-10
R08 N07 Port2 1.43e+02
.ENDS GRM21A5C2J101JWA1
