*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/2.70e-03[uF]/100[V]
* Murata P/N :GRM2162C2A272JA01
* Property : C = 2.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2162C2A272JA01 Port1 Port2
C01 Port1 N01 2.68e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.05e-11
R03 N02 N03 6.76e-03
L04 N03 N04 6.96e-11
R04 N03 N04 2.67e-01
L05 N04 N05 5.71e-11
R05 N04 N05 1.36e-02
L06 N05 N06 1.54e-10
R06 N05 N06 5.13e-03
C07 N06 N07 1.62e-08
L07 N06 N07 1.73e-11
R07 N06 N07 2.45e-01
C08 N07 N08 3.46e-09
L08 N07 N08 3.31e-11
R08 N07 N08 4.98e-01
C09 N08 N09 1.09e-12
L09 N08 N09 3.04e-10
R09 N08 N09 1.00e+05
C10 N09 Port2 4.21e-12
L10 N09 Port2 7.26e-11
R10 N09 Port2 1.74e+01
.ENDS GRM2162C2A272JA01
