*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.20e-02[uF]/100[V]
* Murata P/N :GRM2165C2A123JA01
* Property : C = 1.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2165C2A123JA01 Port1 Port2
C01 Port1 N01 1.20e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.64e-10
R03 N02 N03 5.50e-03
L04 N03 N04 6.11e-11
R04 N03 N04 1.65e-01
L05 N04 N05 5.34e-11
R05 N04 N05 8.27e-03
L06 N05 N06 2.92e-10
R06 N05 N06 1.86e-03
C07 N06 N07 4.30e-08
L07 N06 N07 2.49e-11
R07 N06 N07 1.36e-01
C08 N07 N08 1.36e-08
L08 N07 N08 2.96e-11
R08 N07 N08 2.01e-01
C09 N08 N09 9.72e-09
L09 N08 N09 1.27e-11
R09 N08 N09 4.94e-02
C10 N09 Port2 1.86e-12
L10 N09 Port2 1.68e-10
R10 N09 Port2 8.12e+01
.ENDS GRM2165C2A123JA01
