*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/2.70e-02[uF]/50[V]
* Murata P/N :GRM2165C1H273GA01
* Property : C = 2.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2165C1H273GA01 Port1 Port2
C01 Port1 N01 2.68e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.53e-10
R03 N02 N03 3.12e-03
L04 N03 N04 9.78e-11
R04 N03 N04 1.52e-01
L05 N04 N05 7.62e-11
R05 N04 N05 3.71e-03
L06 N05 N06 3.96e-10
R06 N05 N06 1.95e-03
C07 N06 N07 8.90e-08
L07 N06 N07 3.08e-11
R07 N06 N07 1.16e-01
C08 N07 N08 3.27e-08
L08 N07 N08 3.48e-11
R08 N07 N08 1.65e-01
C09 N08 Port2 2.26e-12
L09 N08 Port2 1.38e-10
R09 N08 Port2 7.78e+01
.ENDS GRM2165C1H273GA01
