*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/1.20e-03[uF]/50[V]
* Murata P/N :GRM2162C1H122JA01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2162C1H122JA01 Port1 Port2
C01 Port1 N01 1.16e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.41e-10
R03 N02 N03 1.26e-02
L04 N03 N04 2.13e-11
R04 N03 N04 3.54e-01
L05 N04 N05 5.72e-11
R05 N04 N05 2.50e-02
L06 N05 N06 1.35e-10
R06 N05 N06 1.04e-02
C07 N06 N07 5.61e-09
L07 N06 N07 1.11e-11
R07 N06 N07 1.58e-01
C08 N07 N08 7.25e-10
L08 N07 N08 2.73e-11
R08 N07 N08 3.96e-01
C09 N08 Port2 1.45e-12
L09 N08 Port2 3.15e-10
R09 N08 Port2 2.99e+02
.ENDS GRM2162C1H122JA01
