*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/SL(-55to125[deg])/3.30e-02[uF]/10[V]
* Murata P/N :GRM2161X1A333JA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2161X1A333JA01 Port1 Port2
C01 Port1 N01 3.34e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 8.91e-11
R03 N02 N03 6.21e-03
L04 N03 N04 9.31e-12
R04 N03 N04 3.28e-01
L05 N04 N05 7.39e-11
R05 N04 N05 2.07e-01
L06 N05 N06 6.05e-11
R06 N05 N06 6.10e-03
C07 N06 N07 1.45e-07
L07 N06 N07 2.30e-11
R07 N06 N07 7.52e-02
C08 N07 N08 2.26e-08
L08 N07 N08 5.91e-11
R08 N07 N08 1.51e-01
C09 N08 N09 2.25e-08
L09 N08 N09 1.70e-11
R09 N08 N09 6.03e-02
C10 N09 N10 8.65e-12
L10 N09 N10 4.05e-11
R10 N09 N10 1.39e+01
C11 N10 Port2 2.13e-12
L11 N10 Port2 1.54e-10
R11 N10 Port2 1.00e+05
.ENDS GRM2161X1A333JA01
