*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/6.80e-03[uF]/250[V]
* Murata P/N :GRM21B5C2E682JWAA
* Property : C = 6.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21B5C2E682JWAA Port1 Port2
C01 Port1 N01 6.80e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.24e-10
R03 N02 N03 6.62e-03
C04 N03 N04 5.67e-07
R04 N03 N04 7.01e+00
L05 N04 N05 9.29e-11
R05 N04 N05 6.75e-01
L06 N05 N06 8.26e-11
R06 N05 N06 1.36e-02
C07 N06 N07 2.23e-08
L07 N06 N07 3.98e-11
R07 N06 N07 3.62e-01
C08 N07 N08 1.05e-08
L08 N07 N08 3.60e-11
R08 N07 N08 4.43e-01
C09 N08 Port2 6.09e-09
L09 N08 Port2 1.97e-11
R09 N08 Port2 1.24e-01
.ENDS GRM21B5C2E682JWAA
