*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/UJ(-25to85[deg])/2.20e-02[uF]/50[V]
* Murata P/N :GRM2193U1H223JA01
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2193U1H223JA01 Port1 Port2
C01 Port1 N01 2.10e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 6.11e-12
R03 N02 N03 5.50e-03
L04 N03 N04 2.04e-11
R04 N03 N04 4.41e-01
L05 N04 N05 1.68e-10
R05 N04 N05 1.54e-01
L06 N05 N06 2.05e-10
R06 N05 N06 2.56e-03
C07 N06 N07 1.43e-07
L07 N06 N07 1.77e-11
R07 N06 N07 1.04e-01
C08 N07 N08 4.31e-08
L08 N07 N08 2.29e-11
R08 N07 N08 1.36e-01
C09 N08 N09 9.75e-12
L09 N08 N09 3.60e-11
R09 N08 N09 1.58e+01
C10 N09 Port2 1.02e-12
L10 N09 Port2 3.16e-10
R10 N09 Port2 7.29e+02
.ENDS GRM2193U1H223JA01
