*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/2.70e-05[uF]/250[V]
* Murata P/N :GRM21A5C2E270GW01
* Property : C = 2.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21A5C2E270GW01 Port1 Port2
C01 Port1 N01 2.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.08e-10
R03 N02 N03 1.91e-01
C04 N03 N04 2.72e-10
L04 N03 N04 1.15e-11
R04 N03 N04 1.92e+00
C05 N04 N05 2.04e-11
L05 N04 N05 6.27e-11
R05 N04 N05 1.11e+01
C06 N05 Port2 9.59e-13
L06 N05 Port2 4.29e-10
R06 N05 Port2 1.72e+02
.ENDS GRM21A5C2E270GW01
