*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/CH(-55to125[deg])/8.20e-04[uF]/100[V]
* Murata P/N :GRM2162C2A821JA01
* Property : C = 8.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM2162C2A821JA01 Port1 Port2
C01 Port1 N01 8.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 4.73e-11
R03 N02 N03 3.39e-02
L04 N03 N04 4.55e-11
R04 N03 N04 5.50e-01
L05 N04 N05 1.26e-11
R05 N04 N05 2.01e-02
C06 N05 N06 3.69e-09
L06 N05 N06 1.61e-11
R06 N05 N06 4.31e-01
C07 N06 N07 6.49e-10
L07 N06 N07 3.03e-11
R07 N06 N07 6.62e-01
C08 N07 Port2 1.32e-12
L08 N07 Port2 3.27e-10
R08 N07 Port2 3.61e+02
.ENDS GRM2162C2A821JA01
