*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/C0G(-55to125[deg])/1.80e-02[uF]/100[V]
* Murata P/N :GRM21B5C2A183JA01
* Property : C = 1.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21B5C2A183JA01 Port1 Port2
C01 Port1 N01 1.79e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 4.81e-11
R03 N02 N03 3.17e-03
L04 N03 N04 1.02e-10
R04 N03 N04 1.98e+01
L05 N04 N05 9.41e-11
R05 N04 N05 1.71e-01
L06 N05 N06 5.48e-11
R06 N05 N06 5.11e-03
L07 N06 N07 1.08e-10
R07 N06 N07 2.19e-03
C08 N07 N08 5.60e-08
L08 N07 N08 4.59e-11
R08 N07 N08 2.70e-01
C09 N08 N09 2.24e-08
L09 N08 N09 4.83e-11
R09 N08 N09 2.65e-01
C10 N09 Port2 1.09e-12
L10 N09 Port2 2.15e-10
R10 N09 Port2 1.00e+05
.ENDS GRM21B5C2A183JA01
