*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/U2J(-55to125[deg])/6.80e-02[uF]/10[V]
* Murata P/N :GRM21B7U1A683JA01
* Property : C = 6.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21B7U1A683JA01 Port1 Port2
C01 Port1 N01 6.49e-08
R01 Port1 N01 7.35e+09
L02 N01 N02 4.57e-11
R03 N02 N03 4.60e-03
L04 N03 N04 1.95e-11
R04 N03 N04 4.22e-01
L05 N04 N05 8.75e-11
R05 N04 N05 1.16e-01
L06 N05 N06 9.66e-11
R06 N05 N06 6.89e-03
C07 N06 N07 2.34e-07
L07 N06 N07 4.00e-11
R07 N06 N07 8.18e-02
C08 N07 N08 8.67e-08
L08 N07 N08 4.56e-11
R08 N07 N08 8.56e-02
C09 N08 N09 5.26e-08
L09 N08 N09 2.40e-11
R09 N08 N09 3.99e-02
C10 N09 N10 1.13e-11
L10 N09 N10 3.11e-11
R10 N09 N10 1.37e+01
C11 N10 Port2 9.00e-13
L11 N10 Port2 3.50e-10
R11 N10 Port2 1.00e+05
.ENDS GRM21B7U1A683JA01
