*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0402M(01005)/B(-25to85[deg])/1.50e-03[uF]/6.3[V]
* Murata P/N :GRM022B30J152KE19
* Property : C = 1.50e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM022B30J152KE19 Port1 Port2
C01 Port1 N01 1.31e-09
R01 Port1 N01 2.00e+09
L02 N01 N02 1.55e-10
R03 N02 N03 1.96e-01
C04 N03 N04 4.11e-08
R04 N03 N04 4.97e+04
C05 N04 N05 3.96e-08
R05 N04 N05 5.20e+03
C06 N05 N06 3.45e-08
R06 N05 N06 5.98e+02
C07 N06 N07 2.64e-08
R07 N06 N07 8.13e+01
C08 N07 N08 2.28e-08
R08 N07 N08 1.19e+01
C09 N08 N09 2.37e-08
R09 N08 N09 2.06e+00
C10 N09 N10 1.45e-08
R10 N09 N10 7.38e-01
C11 N10 N11 1.07e-08
R11 N10 N11 1.21e-01
L12 N11 N12 2.94e-11
R12 N11 N12 5.26e-01
C13 N12 N13 1.56e-09
L13 N12 N13 7.06e-12
R13 N12 N13 7.47e-02
C14 N13 Port2 2.61e-11
L14 N13 Port2 1.09e-11
R14 N13 Port2 1.16e+00
.ENDS GRM022B30J152KE19
