*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/1.00e-04[uF]/50[V]
* Murata P/N :GCM1885C1H101JA16
* Property : C = 1.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H101JA16 Port1 Port2
C01 Port1 N01 1.00e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 3.15e-11
R03 N02 N03 1.20e-01
L04 N03 N04 1.71e-11
R04 N03 N04 8.03e-02
C05 N04 N05 1.14e-09
L05 N04 N05 7.24e-12
R05 N04 N05 2.77e-01
C06 N05 N06 1.01e-10
L06 N05 N06 2.88e-11
R06 N05 N06 1.50e+00
C07 N06 N07 1.61e-12
L07 N06 N07 1.77e-10
R07 N06 N07 4.25e+01
C08 N07 Port2 7.25e-13
L08 N07 Port2 3.51e-10
R08 N07 Port2 1.00e+05
.ENDS GCM1885C1H101JA16
