*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/4.70e-04[uF]/50[V]
* Murata P/N :GCM1885C1H471JA16
* Property : C = 4.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H471JA16 Port1 Port2
C01 Port1 N01 4.70e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 3.90e-11
R03 N02 N03 6.33e-02
L04 N03 N04 3.93e-11
R04 N03 N04 1.04e+00
C05 N04 N05 3.06e-09
L05 N04 N05 2.00e-11
R05 N04 N05 6.16e-01
C06 N05 N06 7.33e-10
L06 N05 N06 2.84e-11
R06 N05 N06 7.32e-01
C07 N06 N07 4.64e-10
L07 N06 N07 1.27e-11
R07 N06 N07 4.03e-01
C08 N07 N08 7.61e-12
L08 N07 N08 3.95e-11
R08 N07 N08 8.00e+00
C09 N08 Port2 8.13e-13
L09 N08 Port2 2.85e-10
R09 N08 Port2 1.00e+05
.ENDS GCM1885C1H471JA16
