*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/1.50e-03[uF]/100[V]
* Murata P/N :GCM1887U2A152JA16
* Property : C = 1.50e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U2A152JA16 Port1 Port2
C01 Port1 N01 1.50e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 7.79e-11
R03 N02 N03 1.95e-02
L04 N03 N04 6.14e-11
R04 N03 N04 5.40e-01
L05 N04 N05 3.73e-11
R05 N04 N05 2.13e-02
L06 N05 N06 4.36e-11
R06 N05 N06 9.15e-03
L07 N06 N07 8.24e-11
R07 N06 N07 9.16e-04
C08 N07 N08 1.92e-08
L08 N07 N08 9.52e-12
R08 N07 N08 2.13e-01
C09 N08 N09 3.15e-09
L09 N08 N09 2.66e-11
R09 N08 N09 4.42e-01
C10 N09 N10 1.82e-09
L10 N09 N10 1.52e-11
R10 N09 N10 1.44e-01
C11 N10 Port2 7.30e-13
L11 N10 Port2 3.36e-10
R11 N10 Port2 5.69e+02
.ENDS GCM1887U2A152JA16
