*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/3.90e-03[uF]/100[V]
* Murata P/N :GCM1887U2A392JA16
* Property : C = 3.90e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U2A392JA16 Port1 Port2
C01 Port1 N01 4.00e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 2.69e-10
R03 N02 N03 1.09e-02
L04 N03 N04 5.84e-11
R04 N03 N04 1.90e-01
L05 N04 N05 9.21e-12
R05 N04 N05 1.17e-01
L06 N05 N06 3.98e-11
R06 N05 N06 1.57e-02
L07 N06 N07 1.16e-10
R07 N06 N07 7.04e-03
L08 N07 N08 2.06e-10
R08 N07 N08 1.68e-03
C09 N08 N09 4.57e-08
L09 N08 N09 8.19e-12
R09 N08 N09 1.16e-01
C10 N09 N10 6.36e-09
L10 N09 N10 2.39e-11
R10 N09 N10 2.95e-01
C11 N10 Port2 1.99e-12
L11 N10 Port2 1.40e-10
R11 N10 Port2 1.05e+02
.ENDS GCM1887U2A392JA16
