*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/5.10e-03[uF]/50[V]
* Murata P/N :GCM1885C1H512JA16
* Property : C = 5.10e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H512JA16 Port1 Port2
C01 Port1 N01 5.17e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 4.32e-11
R03 N02 N03 4.24e-03
L04 N03 N04 6.45e-11
R04 N03 N04 2.67e-01
L05 N04 N05 8.26e-11
R05 N04 N05 1.71e-02
L06 N05 N06 8.35e-10
R06 N05 N06 6.44e-03
C07 N06 N07 3.96e-08
L07 N06 N07 1.36e-11
R07 N06 N07 1.02e-01
C08 N07 N08 8.05e-09
L08 N07 N08 2.79e-11
R08 N07 N08 2.59e-01
C09 N08 Port2 5.95e-13
L09 N08 Port2 3.84e-10
R09 N08 Port2 6.81e+02
.ENDS GCM1885C1H512JA16
