*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/2.20e-06[uF]/100[V]
* Murata P/N :GCM1885C2A2R2CA16
* Property : C = 2.20e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C2A2R2CA16 Port1 Port2
C01 Port1 N01 2.20e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 3.54e-10
R03 N02 N03 3.40e-01
C04 N03 Port2 2.12e-12
L04 N03 Port2 1.35e-10
R04 N03 Port2 8.65e+01
.ENDS GCM1885C2A2R2CA16
