*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CJ(-55to125[deg])/3.00e-06[uF]/100[V]
* Murata P/N :GCM1883C2A3R0CA01
* Property : C = 3.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1883C2A3R0CA01 Port1 Port2
C01 Port1 N01 3.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 4.40e-10
R03 N02 N03 1.70e-01
L04 N03 N04 1.65e-11
R04 N03 N04 3.18e-01
L05 N04 N05 3.15e-11
R05 N04 N05 1.41e-01
C06 N05 N06 1.08e-11
L06 N05 N06 2.79e-11
R06 N05 N06 5.51e+00
C07 N06 Port2 6.58e-12
L07 N06 Port2 4.50e-11
R07 N06 Port2 1.00e+05
.ENDS GCM1883C2A3R0CA01
