*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/1.00e-03[uF]/50[V]
* Murata P/N :GCM1887U1H102JA01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U1H102JA01 Port1 Port2
C01 Port1 N01 1.01e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.58e-10
R03 N02 N03 3.43e-02
L04 N03 N04 6.02e-11
R04 N03 N04 5.57e-01
L05 N04 N05 5.45e-11
R05 N04 N05 2.73e-02
L06 N05 N06 6.65e-11
R06 N05 N06 2.72e-03
L07 N06 N07 4.21e-11
R07 N06 N07 6.20e-04
C08 N07 N08 1.59e-08
L08 N07 N08 7.20e-12
R08 N07 N08 1.39e-01
C09 N08 N09 1.74e-09
L09 N08 N09 2.70e-11
R09 N08 N09 4.26e-01
C10 N09 Port2 8.00e-13
L10 N09 Port2 3.24e-10
R10 N09 Port2 3.12e+02
.ENDS GCM1887U1H102JA01
