*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/2.20e-04[uF]/50[V]
* Murata P/N :GCM1885C1H221JA16
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H221JA16 Port1 Port2
C01 Port1 N01 2.20e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 1.63e-10
R03 N02 N03 9.46e-02
L04 N03 N04 5.00e-11
R04 N03 N04 8.98e-01
L05 N04 N05 1.16e-11
R05 N04 N05 3.50e-02
C06 N05 N06 3.19e-09
L06 N05 N06 6.00e-12
R06 N05 N06 2.04e-01
C07 N06 N07 2.98e-10
L07 N06 N07 2.41e-11
R07 N06 N07 8.75e-01
C08 N07 N08 4.98e-12
L08 N07 N08 5.35e-11
R08 N07 N08 6.35e+00
C09 N08 Port2 7.56e-13
L09 N08 Port2 3.29e-10
R09 N08 Port2 1.00e+05
.ENDS GCM1885C1H221JA16
