*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/3.30e-03[uF]/50[V]
* Murata P/N :GCM1887U1H332JA16
* Property : C = 3.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U1H332JA16 Port1 Port2
C01 Port1 N01 3.24e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 2.67e-10
R03 N02 N03 1.29e-02
L04 N03 N04 4.46e-11
R04 N03 N04 3.36e-01
L05 N04 N05 4.45e-11
R05 N04 N05 1.98e-02
L06 N05 N06 1.29e-10
R06 N05 N06 6.51e-03
L07 N06 N07 7.38e-10
R07 N06 N07 2.02e-03
C08 N07 N08 3.10e-08
L08 N07 N08 9.12e-12
R08 N07 N08 9.77e-02
C09 N08 N09 5.14e-09
L09 N08 N09 2.19e-11
R09 N08 N09 2.58e-01
C10 N09 N10 3.04e-09
L10 N09 N10 1.04e-11
R10 N09 N10 9.83e-02
C11 N10 Port2 1.45e-12
L11 N10 Port2 1.75e-10
R11 N10 Port2 1.38e+02
.ENDS GCM1887U1H332JA16
