*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/1.20e-03[uF]/50[V]
* Murata P/N :GCM1887U1H122JA01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U1H122JA01 Port1 Port2
C01 Port1 N01 1.21e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.00e-10
R03 N02 N03 2.18e-02
L04 N03 N04 5.92e-11
R04 N03 N04 5.20e-01
L05 N04 N05 6.35e-11
R05 N04 N05 2.51e-02
L06 N05 N06 3.22e-10
R06 N05 N06 5.58e-03
L07 N06 N07 4.67e-11
R07 N06 N07 3.03e-03
C08 N07 N08 1.33e-08
L08 N07 N08 1.16e-11
R08 N07 N08 1.65e-01
C09 N08 N09 2.37e-09
L09 N08 N09 2.96e-11
R09 N08 N09 4.18e-01
C10 N09 N10 1.64e-09
L10 N09 N10 1.33e-11
R10 N09 N10 1.24e-01
C11 N10 Port2 6.24e-13
L11 N10 Port2 3.53e-10
R11 N10 Port2 2.74e+02
.ENDS GCM1887U1H122JA01
