*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/5.60e-05[uF]/100[V]
* Murata P/N :GCM1882C2A560JA01
* Property : C = 5.60e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1882C2A560JA01 Port1 Port2
C01 Port1 N01 5.60e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 3.43e-11
R03 N02 N03 9.36e-02
L04 N03 N04 3.95e-11
R04 N03 N04 1.81e+00
L05 N04 N05 4.96e-11
R05 N04 N05 1.67e-01
C06 N05 N06 5.34e-10
L06 N05 N06 1.15e-11
R06 N05 N06 7.29e-01
C07 N06 Port2 6.94e-13
L07 N06 Port2 5.05e-10
R07 N06 Port2 2.40e+02
.ENDS GCM1882C2A560JA01
