*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/4.00e-06[uF]/100[V]
* Murata P/N :GCM1885C2A4R0DA16
* Property : C = 4.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C2A4R0DA16 Port1 Port2
C01 Port1 N01 4.00e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 3.25e-10
R03 N02 N03 2.50e-01
L04 N03 N04 7.40e-12
R04 N03 N04 2.30e-01
C05 N04 N05 5.98e-12
L05 N04 N05 7.25e-11
R05 N04 N05 3.99e+01
C06 N05 Port2 3.97e-12
L06 N05 Port2 7.57e-11
R06 N05 Port2 6.85e+01
.ENDS GCM1885C2A4R0DA16
