*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/3.30e-03[uF]/50[V]
* Murata P/N :GCM1885C1H332JA16
* Property : C = 3.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H332JA16 Port1 Port2
C01 Port1 N01 3.31e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 5.56e-12
R03 N02 N03 1.44e-02
L04 N03 N04 6.68e-11
R04 N03 N04 3.80e-01
L05 N04 N05 4.26e-11
R05 N04 N05 1.03e-02
C06 N05 N06 2.49e-08
L06 N05 N06 1.62e-11
R06 N05 N06 2.44e-01
C07 N06 N07 5.06e-09
L07 N06 N07 3.86e-11
R07 N06 N07 4.21e-01
C08 N07 N08 3.78e-09
L08 N07 N08 1.70e-11
R08 N07 N08 1.15e-01
C09 N08 N09 3.45e-11
L09 N08 N09 8.69e-12
R09 N08 N09 9.69e-01
C10 N09 Port2 7.72e-13
L10 N09 Port2 3.15e-10
R10 N09 Port2 1.00e+05
.ENDS GCM1885C1H332JA16
