*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/3.60e-06[uF]/50[V]
* Murata P/N :GCM1885C1H3R6CA16
* Property : C = 3.60e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H3R6CA16 Port1 Port2
C01 Port1 N01 3.60e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 4.12e-10
R03 N02 N03 2.57e-01
L04 N03 N04 1.08e-11
R04 N03 N04 3.62e-01
C05 N04 Port2 5.98e-12
L05 N04 Port2 6.70e-11
R05 N04 Port2 3.53e+01
.ENDS GCM1885C1H3R6CA16
