*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/1.20e-03[uF]/100[V]
* Murata P/N :GCM1882C2A122JA01
* Property : C = 1.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1882C2A122JA01 Port1 Port2
C01 Port1 N01 1.18e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 9.17e-11
R03 N02 N03 1.20e-02
L04 N03 N04 5.39e-11
R04 N03 N04 4.53e-01
L05 N04 N05 8.88e-11
R05 N04 N05 2.07e-02
L06 N05 N06 1.19e-11
R06 N05 N06 1.38e-02
C07 N06 N07 1.77e-08
L07 N06 N07 7.31e-12
R07 N06 N07 1.71e-01
C08 N07 N08 1.65e-09
L08 N07 N08 3.31e-11
R08 N07 N08 6.01e-01
C09 N08 Port2 1.01e-12
L09 N08 Port2 3.58e-10
R09 N08 Port2 4.99e+02
.ENDS GCM1882C2A122JA01
