*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/4.30e-03[uF]/50[V]
* Murata P/N :GCM1885C1H432JA16
* Property : C = 4.30e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H432JA16 Port1 Port2
C01 Port1 N01 4.29e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 1.71e-10
R03 N02 N03 7.02e-03
L04 N03 N04 4.86e-11
R04 N03 N04 3.03e-01
L05 N04 N05 8.65e-11
R05 N04 N05 2.22e-02
L06 N05 N06 2.13e-10
R06 N05 N06 4.22e-03
C07 N06 N07 2.59e-08
L07 N06 N07 1.69e-11
R07 N06 N07 9.87e-02
C08 N07 N08 5.45e-09
L08 N07 N08 3.18e-11
R08 N07 N08 2.96e-01
C09 N08 N09 4.35e-09
L09 N08 N09 1.09e-11
R09 N08 N09 1.02e-01
C10 N09 Port2 7.25e-13
L10 N09 Port2 2.87e-10
R10 N09 Port2 3.77e+02
.ENDS GCM1885C1H432JA16
