*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/2.70e-06[uF]/50[V]
* Murata P/N :GCM1885C1H2R7WA16
* Property : C = 2.70e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H2R7WA16 Port1 Port2
C01 Port1 N01 2.70e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 4.14e-10
R03 N02 N03 3.08e-01
L04 N03 N04 3.05e-12
R04 N03 N04 1.03e-01
C05 N04 Port2 3.84e-12
L05 N04 Port2 7.85e-11
R05 N04 Port2 3.49e+01
.ENDS GCM1885C1H2R7WA16
