*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/3.30e-04[uF]/50[V]
* Murata P/N :GCM1882C1H331JA01
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1882C1H331JA01 Port1 Port2
C01 Port1 N01 3.30e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 9.00e-11
R03 N02 N03 7.68e-02
L04 N03 N04 1.49e-11
R04 N03 N04 3.22e-01
C05 N04 N05 2.76e-09
L05 N04 N05 1.31e-11
R05 N04 N05 3.72e-01
C06 N05 N06 4.29e-10
L06 N05 N06 3.33e-11
R06 N05 N06 9.57e-01
C07 N06 N07 1.51e-10
L07 N06 N07 2.20e-11
R07 N06 N07 4.79e-01
C08 N07 N08 4.83e-10
L08 N07 N08 2.06e-12
R08 N07 N08 4.85e-01
C09 N08 N09 2.99e-12
L09 N08 N09 1.07e-10
R09 N08 N09 3.37e+01
C10 N09 Port2 8.93e-13
L10 N09 Port2 2.78e-10
R10 N09 Port2 1.00e+05
.ENDS GCM1882C1H331JA01
