*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/1.00e-04[uF]/100[V]
* Murata P/N :GCM1885C2A101JA16
* Property : C = 1.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C2A101JA16 Port1 Port2
C01 Port1 N01 1.00e-10
R01 Port1 N01 1.00e+11
L02 N01 N02 1.09e-11
R03 N02 N03 8.99e-02
L04 N03 N04 4.29e-11
R04 N03 N04 1.57e-01
C05 N04 N05 1.03e-10
L05 N04 N05 2.90e-11
R05 N04 N05 1.37e+00
C06 N05 N06 3.48e-12
L06 N05 N06 9.43e-11
R06 N05 N06 1.62e+01
C07 N06 Port2 5.94e-13
L07 N06 Port2 4.38e-10
R07 N06 Port2 1.00e+05
.ENDS GCM1885C2A101JA16
