*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/U2J(-55to125[deg])/4.70e-03[uF]/100[V]
* Murata P/N :GCM1887U2A472JA01
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1887U2A472JA01 Port1 Port2
C01 Port1 N01 4.64e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.80e-10
R03 N02 N03 7.32e-03
L04 N03 N04 5.30e-11
R04 N03 N04 2.78e-01
L05 N04 N05 6.42e-12
R05 N04 N05 1.72e-01
L06 N05 N06 6.90e-11
R06 N05 N06 1.80e-02
L07 N06 N07 5.17e-10
R07 N06 N07 3.42e-03
L08 N07 N08 1.14e-10
R08 N07 N08 2.80e-03
C09 N08 N09 3.39e-08
L09 N08 N09 1.41e-11
R09 N08 N09 1.09e-01
C10 N09 N10 8.17e-09
L10 N09 N10 2.45e-11
R10 N09 N10 2.53e-01
C11 N10 N11 5.08e-09
L11 N10 N11 1.14e-11
R11 N10 N11 7.78e-02
C12 N11 Port2 1.74e-12
L12 N11 Port2 1.30e-10
R12 N11 Port2 9.99e+01
.ENDS GCM1887U2A472JA01
