*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/C0G(-55to125[deg])/5.60e-03[uF]/50[V]
* Murata P/N :GCM1885C1H562GA16
* Property : C = 5.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1885C1H562GA16 Port1 Port2
C01 Port1 N01 5.57e-09
R01 Port1 N01 1.00e+11
L02 N01 N02 1.22e-10
R03 N02 N03 6.49e-03
L04 N03 N04 4.83e-11
R04 N03 N04 2.60e-01
L05 N04 N05 6.48e-11
R05 N04 N05 2.78e-02
L06 N05 N06 1.05e-10
R06 N05 N06 5.27e-03
L07 N06 N07 6.07e-10
R07 N06 N07 2.91e-03
C08 N07 N08 4.04e-08
L08 N07 N08 1.46e-11
R08 N07 N08 1.13e-01
C09 N08 N09 9.87e-09
L09 N08 N09 2.63e-11
R09 N08 N09 2.28e-01
C10 N09 N10 4.83e-09
L10 N09 N10 1.52e-11
R10 N09 N10 7.93e-02
C11 N10 Port2 6.65e-13
L11 N10 Port2 2.94e-10
R11 N10 Port2 2.41e+02
.ENDS GCM1885C1H562GA16
