*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/1.00e-03[uF]/50[V]
* Murata P/N :GCM1882C1H102JA01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1882C1H102JA01 Port1 Port2
C01 Port1 N01 1.00e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.05e-10
R03 N02 N03 1.97e-02
L04 N03 N04 6.73e-11
R04 N03 N04 5.39e-01
L05 N04 N05 7.18e-11
R05 N04 N05 1.80e-02
C06 N05 N06 5.83e-09
L06 N05 N06 2.40e-11
R06 N05 N06 5.42e-01
C07 N06 N07 2.45e-09
L07 N06 N07 2.16e-11
R07 N06 N07 5.68e-01
C08 N07 N08 1.40e-09
L08 N07 N08 1.29e-11
R08 N07 N08 2.60e-01
C09 N08 N09 2.09e-11
L09 N08 N09 1.67e-11
R09 N08 N09 4.40e+00
C10 N09 Port2 1.12e-12
L10 N09 Port2 2.07e-10
R10 N09 Port2 1.00e+05
.ENDS GCM1882C1H102JA01
