*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/CH(-55to125[deg])/3.60e-03[uF]/80[V]
* Murata P/N :GCM1882C1K362GA01
* Property : C = 3.60e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1882C1K362GA01 Port1 Port2
C01 Port1 N01 3.60e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.59e-10
R03 N02 N03 7.21e-03
L04 N03 N04 4.40e-11
R04 N03 N04 2.07e-01
L05 N04 N05 1.06e-11
R05 N04 N05 1.58e-01
L06 N05 N06 6.18e-11
R06 N05 N06 3.01e-02
L07 N06 N07 1.06e-10
R07 N06 N07 3.89e-03
L08 N07 N08 8.25e-11
R08 N07 N08 1.76e-03
C09 N08 N09 1.29e-08
L09 N08 N09 1.79e-11
R09 N08 N09 2.47e-01
C10 N09 N10 9.91e-09
L10 N09 N10 7.69e-12
R10 N09 N10 8.18e-02
C11 N10 Port2 4.06e-12
L11 N10 Port2 7.67e-11
R11 N10 Port2 4.46e+01
.ENDS GCM1882C1K362GA01
