*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/2.70e-05[uF]/50[V]
* Murata P/N :GCM1555G1H270GA16
* Property : C = 2.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H270GA16 Port1 Port2
C01 Port1 N01 2.70e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 1.90e-10
R03 N02 N03 1.79e-01
L04 N03 N04 1.50e-10
R04 N03 N04 4.90e+01
L05 N04 N05 2.23e-12
R05 N04 N05 3.02e-02
C06 N05 N06 1.96e-10
L06 N05 N06 1.05e-11
R06 N05 N06 1.36e+00
C07 N06 Port2 6.83e-11
L07 N06 Port2 9.82e-12
R07 N06 Port2 1.16e+00
.ENDS GCM1555G1H270GA16
