*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/6.30e-06[uF]/50[V]
* Murata P/N :GCM1555G1H6R3CA16
* Property : C = 6.30e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H6R3CA16 Port1 Port2
C01 Port1 N01 6.30e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 3.15e-10
R03 N02 N03 2.36e-01
L04 N03 N04 2.33e-11
R04 N03 N04 3.74e-01
C05 N04 Port2 1.98e-11
L05 N04 Port2 2.60e-11
R05 N04 Port2 8.09e+00
.ENDS GCM1555G1H6R3CA16
