*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/4.70e-05[uF]/50[V]
* Murata P/N :GCM1555G1H470FA16
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H470FA16 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+11
L02 N01 N02 2.37e-10
R03 N02 N03 1.36e-01
C04 N03 N04 4.87e-10
L04 N03 N04 7.94e-12
R04 N03 N04 8.27e-01
C05 N04 N05 8.49e-11
L05 N04 N05 1.46e-11
R05 N04 N05 1.58e+00
C06 N05 N06 1.97e-10
L06 N05 N06 2.23e-12
R06 N05 N06 2.62e-01
C07 N06 Port2 2.25e-12
L07 N06 Port2 6.73e-11
R07 N06 Port2 9.67e+00
.ENDS GCM1555G1H470FA16
