*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/3.90e-04[uF]/50[V]
* Murata P/N :GCM1552C1H391JA01
* Property : C = 3.90e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1552C1H391JA01 Port1 Port2
C01 Port1 N01 3.90e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.58e-10
R03 N02 N03 7.50e-02
L04 N03 N04 4.37e-11
R04 N03 N04 9.15e-01
C05 N04 N05 2.35e-12
L05 N04 N05 1.20e-10
C06 N05 N06 1.15e-11
L06 N05 N06 2.97e-11
R06 N05 N06 4.87e+00
C07 N06 N07 9.05e-10
L07 N06 N07 4.83e-12
R07 N06 N07 1.95e-01
C08 N07 N08 6.96e-10
L08 N07 N08 1.97e-11
R08 N07 N08 5.90e-01
C09 N08 Port2 3.22e-09
L09 N08 Port2 9.50e-12
R09 N08 Port2 2.46e-01
.ENDS GCM1552C1H391JA01
