*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN20NG00
* Property : L = 20[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN20NG00 port1 port2
C1 port1 port2 2.26e-14
L2 port1 1 2.43e-8
R2 1 port2 1.90e-1
R3 port1 port2 4.28e+4
L4 port1 2 1.52e-7
R4 2 port2 7.82
L5 port1 3 4.53e-7
R5 3 port2 327
L6 port1 4 1.05e-6
R6 4 port2 6.79e+3
L7 port1 5 5.22e-7
C7 5 6 4.80e-16
R7 6 port2 3.56e+3
L8 port1 7 5.44e-8
C8 7 8 1.56e-15
R8 8 port2 148
.ENDS LQW15AN20NG00
*----------------------------------------------------------------------
