*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN6N6D0Z
* Property : L = 6.6[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN6N6D0Z port1 port2
C1 port1 port2 2.66e-14
L2 port1 1 6.50e-9
R2 1 port2 6.00e-2
R3 port1 port2 1.43e+4
L4 port1 2 7.83e-8
R4 2 port2 23.8
L5 port1 3 2.66e-7
R5 3 port2 970
.ENDS LQW15AN6N6D0Z
*----------------------------------------------------------------------
