*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN11NJ0Z
* Property : L = 11[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN11NJ0Z port1 port2
C1 port1 port2 1.98e-14
L2 port1 1 1.26e-8
R2 1 port2 1.00e-1
R3 port1 port2 2.05e+4
L4 port1 2 7.72e-8
R4 2 port2 4.32
L5 port1 3 2.50e-7
R5 3 port2 165
L6 port1 4 6.07e-7
R6 4 port2 3.74e+3
L7 port1 5 6.27e-8
C7 5 6 2.13e-15
R7 6 port2 105
.ENDS LQW15AN11NJ0Z
*----------------------------------------------------------------------
