*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN23NG0Z
* Property : L = 23[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN23NG0Z port1 port2
C1 port1 port2 1.90e-14
L2 port1 1 2.68e-8
R2 1 port2 2.10e-1
R3 port1 port2 4.48e+4
L4 port1 2 2.30e-7
R4 2 port2 11.3
L5 port1 3 5.07e-7
R5 3 port2 333
L6 port1 4 1.22e-6
R6 4 port2 7.05e+3
L7 port1 5 1.00e-7
C7 5 6 2.37e-15
R7 6 port2 174
L8 port1 7 2.27e-8
C8 7 8 5.84e-15
R8 8 port2 44.0
.ENDS LQW15AN23NG0Z
*----------------------------------------------------------------------
