*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN33NG0Z
* Property : L = 33[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN33NG0Z port1 port2
C1 port1 port2 1.92e-14
L2 port1 1 3.87e-8
R2 1 port2 4.50e-1
R3 port1 port2 8.45e+4
L4 port1 2 2.47e-7
R4 2 port2 10.1
L5 port1 3 7.16e-7
R5 3 port2 475
L6 port1 4 1.60e-6
R6 4 port2 1.02e+4
L7 port1 5 9.71e-6
C7 5 6 3.89e-17
R7 6 port2 3.60e+4
L8 port1 7 8.37e-8
C8 7 8 1.89e-15
R8 8 port2 200
L9 port1 9 4.41e-7
C9 9 10 1.67e-16
R9 10 port2 8.95e+3
.ENDS LQW15AN33NG0Z
*----------------------------------------------------------------------
