*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN2N4D0Z
* Property : L = 2.4[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN2N4D0Z port1 port2
C1 port1 port2 1.56e-15
L2 port1 1 2.49e-9
R2 1 port2 3.00e-2
R3 port1 port2 6.97e+3
L4 port1 2 1.89e-8
R4 2 port2 7.01e-1
L5 port1 3 3.85e-8
R5 3 port2 26.0
L6 port1 4 1.65e-7
R6 4 port2 747
.ENDS LQW15AN2N4D0Z
*----------------------------------------------------------------------
