*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8L(-55to150[deg])/2.20e-04[uF]/50[V]
* Murata P/N :GCM155L81H221KA37
* Property : C = 2.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155L81H221KA37 Port1 Port2
C01 Port1 N01 2.25e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.50e-10
R03 N02 N03 5.20e-01
C04 N03 N04 1.93e-08
R04 N03 N04 7.87e+04
C05 N04 N05 3.78e-08
R05 N04 N05 4.04e+03
C06 N05 N06 3.85e-08
R06 N05 N06 4.97e+02
C07 N06 N07 2.66e-08
R07 N06 N07 6.83e+01
C08 N07 N08 1.67e-08
R08 N07 N08 1.11e+01
C09 N08 N09 1.22e-08
R09 N08 N09 2.01e+00
C10 N09 N10 2.44e-09
R10 N09 N10 1.00e+00
C11 N10 N11 1.26e-09
R11 N10 N11 5.06e-01
C12 N11 N12 6.96e-11
L12 N11 N12 4.33e-11
R12 N11 N12 7.96e-01
C13 N12 Port2 1.66e-12
L13 N12 Port2 1.79e-10
R13 N12 Port2 1.99e+01
.ENDS GCM155L81H221KA37
