*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/R(-55to125[deg])/3.30e-02[uF]/16[V]
* Murata P/N :GCM155R11C333KA01
* Property : C = 3.30e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM155R11C333KA01 Port1 Port2
C01 Port1 N01 3.33e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.60e-10
R03 N02 N03 2.93e-02
C04 N03 N04 3.39e-06
R04 N03 N04 1.09e+03
C05 N04 N05 7.67e-06
R05 N04 N05 8.85e+01
C06 N05 N06 4.20e-06
R06 N05 N06 2.67e+01
C07 N06 N07 3.43e-06
R07 N06 N07 2.93e+00
C08 N07 N08 3.06e-06
R08 N07 N08 3.02e-01
C09 N08 N09 1.64e-06
R09 N08 N09 6.35e-02
L10 N09 N10 1.27e-11
R10 N09 N10 3.10e-01
L11 N10 N11 6.35e-11
R11 N10 N11 1.29e-01
C12 N11 N12 1.72e-07
L12 N11 N12 1.26e-11
R12 N11 N12 1.57e-02
C13 N12 N13 3.57e-08
L13 N12 N13 2.86e-11
R13 N12 N13 3.62e-02
C14 N13 Port2 2.06e-12
L14 N13 Port2 1.21e-10
R14 N13 Port2 2.54e+01
.ENDS GCM155R11C333KA01
