*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/7.00e-06[uF]/50[V]
* Murata P/N :GCM1555C1H7R0BA16
* Property : C = 7.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555C1H7R0BA16 Port1 Port2
C01 Port1 N01 7.00e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 2.78e-10
R03 N02 N03 2.23e-01
L04 N03 N04 1.27e-11
R04 N03 N04 3.06e-01
C05 N04 N05 1.93e-11
L05 N04 N05 3.08e-11
R05 N04 N05 9.54e+00
C06 N05 Port2 1.53e-11
L06 N05 Port2 1.98e-11
R06 N05 Port2 8.81e+00
.ENDS GCM1555C1H7R0BA16
