*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G(-55to125[deg])/8.20e-06[uF]/50[V]
* Murata P/N :GCM1555C1H8R2CA16
* Property : C = 8.20e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555C1H8R2CA16 Port1 Port2
C01 Port1 N01 8.20e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 2.94e-10
R03 N02 N03 2.19e-01
L04 N03 N04 1.58e-11
R04 N03 N04 3.85e-01
C05 N04 N05 2.90e-11
L05 N04 N05 2.41e-11
R05 N04 N05 6.91e+00
C06 N05 Port2 2.82e-11
L06 N05 Port2 1.06e-11
R06 N05 Port2 2.36e+00
.ENDS GCM1555C1H8R2CA16
