*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/R(-55to125[deg])/1.50e-01[uF]/25[V]
* Murata P/N :GRM21BR11E154KA01
* Property : C = 1.50e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR11E154KA01 Port1 Port2
C01 Port1 N01 1.49e-07
R01 Port1 N01 3.33e+09
L02 N01 N02 2.16e-10
R03 N02 N03 1.36e-02
C04 N03 N04 1.98e-05
R04 N03 N04 2.01e+02
C05 N04 N05 3.78e-05
R05 N04 N05 1.91e+01
C06 N05 N06 2.60e-05
R06 N05 N06 4.70e+00
C07 N06 N07 2.69e-05
R07 N06 N07 7.11e-01
C08 N07 N08 2.02e-05
R08 N07 N08 1.22e-01
C09 N08 N09 9.76e-06
R09 N08 N09 2.24e-02
L10 N09 N10 1.41e-10
R10 N09 N10 6.41e-02
L11 N10 N11 8.96e-12
R11 N10 N11 2.99e-02
C12 N11 N12 9.52e-07
L12 N11 N12 2.55e-11
R12 N11 N12 1.77e-02
C13 N12 N13 2.56e-07
L13 N12 N13 3.19e-11
R13 N12 N13 2.07e-02
C14 N13 N14 7.73e-12
L14 N13 N14 1.42e-10
R14 N13 N14 1.07e+01
C15 N14 Port2 4.83e-12
L15 N14 Port2 6.46e-11
R15 N14 Port2 2.55e+01
.ENDS GRM21BR11E154KA01
