*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/2.20e-01[uF]/50[V]
* Murata P/N :GRM21BR71H224KA01
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR71H224KA01 Port1 Port2
C01 Port1 N01 2.26e-07
R01 Port1 N01 2.27e+09
L02 N01 N02 1.70e-10
R03 N02 N03 8.20e-03
C04 N03 N04 3.10e-05
R04 N03 N04 1.79e+02
C05 N04 N05 2.92e-05
R05 N04 N05 3.41e+01
C06 N05 N06 2.42e-05
R06 N05 N06 3.82e+00
C07 N06 N07 2.76e-05
R07 N06 N07 3.99e-01
C08 N07 N08 2.24e-05
R08 N07 N08 5.48e-02
C09 N08 N09 1.94e-05
R09 N08 N09 1.01e-02
L10 N09 N10 2.41e-11
R10 N09 N10 7.60e-02
L11 N10 N11 1.94e-10
R11 N10 N11 6.32e-02
C12 N11 N12 9.62e-07
L12 N11 N12 3.89e-11
R12 N11 N12 3.26e-02
C13 N12 N13 3.40e-07
L13 N12 N13 5.16e-11
R13 N12 N13 3.57e-02
C14 N13 N14 1.21e-11
L14 N13 N14 6.76e-11
R14 N13 N14 7.28e+00
C15 N14 Port2 5.28e-12
L15 N14 Port2 6.92e-11
R15 N14 Port2 1.53e+01
.ENDS GRM21BR71H224KA01
