*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7S(-55to125[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GRM21BC71C106KE11
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BC71C106KE11 Port1 Port2
C01 Port1 N01 7.48e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 1.37e-10
R03 N02 N03 2.78e-03
C04 N03 N04 3.44e-04
R04 N03 N04 1.05e+01
C05 N04 N05 5.73e-04
R05 N04 N05 1.17e+00
C06 N05 N06 4.17e-04
R06 N05 N06 2.51e-01
C07 N06 N07 3.55e-04
R07 N06 N07 3.95e-02
C08 N07 N08 2.62e-04
R08 N07 N08 6.48e-03
L09 N08 N09 9.20e-12
R09 N08 N09 4.27e-02
L10 N09 N10 4.13e-11
R10 N09 N10 2.24e-02
L11 N10 N11 2.26e-10
R11 N10 N11 1.42e-02
C12 N11 N12 2.30e-05
L12 N11 N12 6.46e-11
R12 N11 N12 5.50e-03
C13 N12 N13 9.35e-06
L13 N12 N13 7.51e-11
R13 N12 N13 6.55e-03
C14 N13 N14 9.88e-12
L14 N13 N14 7.13e-11
R14 N13 N14 1.50e+01
C15 N14 Port2 2.98e-12
L15 N14 Port2 8.17e-11
R15 N14 Port2 1.99e+01
.ENDS GRM21BC71C106KE11
