*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/4.70e-03[uF]/50[V]
* Murata P/N :GRM216R71H472KA01
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM216R71H472KA01 Port1 Port2
C01 Port1 N01 4.78e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.43e-10
R03 N02 N03 7.96e-02
C04 N03 N04 5.63e-07
R04 N03 N04 3.63e+03
C05 N04 N05 7.89e-07
R05 N04 N05 2.40e+02
C06 N05 N06 6.64e-07
R06 N05 N06 3.09e+01
C07 N06 N07 4.95e-07
R07 N06 N07 3.41e+00
C08 N07 N08 4.58e-07
R08 N07 N08 4.11e-01
C09 N08 N09 4.50e-07
R09 N08 N09 1.38e-01
C10 N09 N10 8.76e-08
R10 N09 N10 8.56e-02
L11 N10 N11 4.82e-11
R11 N10 N11 2.27e-01
C12 N11 N12 2.41e-08
L12 N11 N12 1.20e-11
R12 N11 N12 6.75e-02
C13 N12 N13 3.03e-09
L13 N12 N13 3.09e-11
R13 N12 N13 1.72e-01
C14 N13 N14 1.15e-11
L14 N13 N14 8.07e-11
R14 N13 N14 9.89e+00
C15 N14 Port2 2.33e-12
L15 N14 Port2 1.39e-10
R15 N14 Port2 2.31e+01
.ENDS GRM216R71H472KA01
