*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.00e-02[uF]/100[V]
* Murata P/N :GRM21BR72A103KA01
* Property : C = 1.00e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR72A103KA01 Port1 Port2
C01 Port1 N01 1.01e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.26e-10
R03 N02 N03 5.40e-02
C04 N03 N04 1.21e-06
R04 N03 N04 2.88e+03
C05 N04 N05 2.01e-06
R05 N04 N05 1.99e+02
C06 N05 N06 1.58e-06
R06 N05 N06 3.97e+01
C07 N06 N07 2.75e-06
R07 N06 N07 4.35e+00
C08 N07 N08 1.25e-06
R08 N07 N08 1.87e+00
C09 N08 N09 8.88e-07
R09 N08 N09 3.44e-01
C10 N09 N10 3.86e-07
R10 N09 N10 8.11e-02
L11 N10 N11 3.36e-11
R11 N10 N11 1.36e-01
L12 N11 N12 1.12e-12
R12 N11 N12 9.27e-03
C13 N12 N13 2.80e-08
L13 N12 N13 1.70e-11
R13 N12 N13 4.67e-02
C14 N13 N14 3.28e-08
L14 N13 N14 3.20e-12
R14 N13 N14 2.15e-02
C15 N14 N15 1.00e-11
L15 N14 N15 9.90e-11
R15 N14 N15 9.80e+00
C16 N15 Port2 2.81e-12
L16 N15 Port2 1.39e-10
R16 N15 Port2 2.44e+01
.ENDS GRM21BR72A103KA01
