*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X5R(-55to85[deg])/4.70e-01[uF]/16[V]
* Murata P/N :GRM21BR61C474KA01
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR61C474KA01 Port1 Port2
C01 Port1 N01 4.65e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 2.35e-10
R03 N02 N03 5.70e-03
C04 N03 N04 1.11e-04
R04 N03 N04 2.48e+01
C05 N04 N05 9.89e-05
R05 N04 N05 8.41e+00
C06 N05 N06 9.49e-05
R06 N05 N06 1.65e+00
C07 N06 N07 9.10e-05
R07 N06 N07 3.68e-01
C08 N07 N08 7.14e-05
R08 N07 N08 8.86e-02
C09 N08 N09 4.69e-05
R09 N08 N09 1.75e-02
L10 N09 N10 1.35e-11
R10 N09 N10 5.79e-02
L11 N10 N11 1.18e-10
R11 N10 N11 2.82e-02
L12 N11 N12 1.06e-10
R12 N11 N12 2.78e-02
C13 N12 N13 2.32e-06
L13 N12 N13 3.53e-11
R13 N12 N13 2.70e-02
C14 N13 N14 7.90e-07
L14 N13 N14 5.02e-11
R14 N13 N14 2.63e-02
C15 N14 Port2 9.96e-12
L15 N14 Port2 8.98e-11
R15 N14 Port2 7.97e+00
.ENDS GRM21BR61C474KA01
