*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/B(-25to85[deg])/4.70e+00[uF]/50[V]
* Murata P/N :GRM21BB31H475ME51
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BB31H475ME51 Port1 Port2
C01 Port1 N01 3.52e-06
R01 Port1 N01 1.06e+07
L02 N01 N02 1.04e-10
R03 N02 N03 3.69e-03
C04 N03 N04 5.83e-05
R04 N03 N04 9.53e+01
C05 N04 N05 1.34e-04
R05 N04 N05 4.21e+00
C06 N05 N06 1.10e-04
R06 N05 N06 4.75e-01
C07 N06 N07 9.23e-05
R07 N06 N07 5.65e-02
C08 N07 N08 7.70e-05
R08 N07 N08 6.73e-03
L09 N08 N09 7.86e-12
R09 N08 N09 4.04e-02
L10 N09 N10 2.45e-11
R10 N09 N10 2.55e-02
L11 N10 N11 2.68e-10
R11 N10 N11 2.22e-02
C12 N11 N12 1.02e-05
L12 N11 N12 5.22e-11
R12 N11 N12 5.91e-03
C13 N12 N13 6.29e-06
L13 N12 N13 4.32e-11
R13 N12 N13 6.03e-03
C14 N13 N14 1.50e-11
L14 N13 N14 5.47e-11
R14 N13 N14 9.30e+00
C15 N14 Port2 1.96e-12
L15 N14 Port2 1.18e-10
R15 N14 Port2 2.13e+01
.ENDS GRM21BB31H475ME51
