*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7T(-55to125[deg])/1.00e+00[uF]/16[V]
* Murata P/N :GRM216D71C105MA12
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM216D71C105MA12 Port1 Port2
C01 Port1 N01 7.71e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.99e-10
R03 N02 N03 9.65e-03
C04 N03 N04 2.49e-05
R04 N03 N04 1.75e+02
C05 N04 N05 2.30e-05
R05 N04 N05 2.19e+01
C06 N05 N06 1.84e-05
R06 N05 N06 2.83e+00
C07 N06 N07 1.63e-05
R07 N06 N07 3.38e-01
C08 N07 N08 1.21e-05
R08 N07 N08 5.11e-02
C09 N08 N09 1.63e-05
R09 N08 N09 5.55e-03
L10 N09 N10 1.60e-11
R10 N09 N10 7.06e-02
L11 N10 N11 9.40e-11
R11 N10 N11 5.16e-02
C12 N11 N12 3.38e-06
L12 N11 N12 1.63e-11
R12 N11 N12 5.34e-03
C13 N12 N13 3.20e-07
L13 N12 N13 6.33e-11
R13 N12 N13 1.74e-02
C14 N13 N14 1.06e-11
L14 N13 N14 7.17e-11
R14 N13 N14 1.02e+01
C15 N14 Port2 1.12e-11
L15 N14 Port2 3.27e-11
R15 N14 Port2 7.12e+00
.ENDS GRM216D71C105MA12
