*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X6S(-55to105[deg])/2.20e+01[uF]/6.3[V]
* Murata P/N :GRM21BC80J226ME51
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BC80J226ME51 Port1 Port2
C01 Port1 N01 1.41e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 1.44e-10
R03 N02 N03 2.43e-03
C04 N03 N04 2.83e-04
R04 N03 N04 2.01e+01
C05 N04 N05 3.85e-04
R05 N04 N05 1.39e+00
C06 N05 N06 3.52e-04
R06 N05 N06 1.52e-01
C07 N06 N07 2.64e-04
R07 N06 N07 1.93e-02
C08 N07 N08 3.46e-04
R08 N07 N08 1.96e-03
L09 N08 N09 1.53e-11
R09 N08 N09 8.38e-02
L10 N09 N10 4.59e-11
R10 N09 N10 2.50e-02
L11 N10 N11 3.75e-10
R11 N10 N11 1.39e-02
C12 N11 N12 3.43e-05
L12 N11 N12 7.23e-11
R12 N11 N12 3.39e-03
C13 N12 N13 7.50e-05
L13 N12 N13 1.79e-11
R13 N12 N13 2.21e-03
C14 N13 N14 1.45e-11
L14 N13 N14 5.81e-11
R14 N13 N14 7.85e+00
C15 N14 Port2 8.35e-12
L15 N14 Port2 3.97e-11
R15 N14 Port2 5.40e+00
.ENDS GRM21BC80J226ME51
