*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/6.80e-01[uF]/25[V]
* Murata P/N :GRM219R71E684KA88
* Property : C = 6.80e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM219R71E684KA88 Port1 Port2
C01 Port1 N01 6.15e-07
R01 Port1 N01 7.35e+08
L02 N01 N02 1.64e-10
R03 N02 N03 6.73e-03
C04 N03 N04 7.44e-05
R04 N03 N04 5.34e+01
C05 N04 N05 1.24e-04
R05 N04 N05 6.28e+00
C06 N05 N06 8.68e-05
R06 N05 N06 1.41e+00
C07 N06 N07 8.78e-05
R07 N06 N07 2.18e-01
C08 N07 N08 6.26e-05
R08 N07 N08 2.86e-02
C09 N08 N09 6.01e-05
R09 N08 N09 5.79e-03
L10 N09 N10 1.48e-10
R10 N09 N10 4.35e-02
L11 N10 N11 9.95e-12
R11 N10 N11 3.23e-02
C12 N11 N12 3.26e-06
L12 N11 N12 2.47e-11
R12 N11 N12 9.33e-03
C13 N12 N13 6.47e-07
L13 N12 N13 5.28e-11
R13 N12 N13 1.75e-02
C14 N13 N14 1.30e-11
L14 N13 N14 6.67e-11
R14 N13 N14 8.02e+00
C15 N14 Port2 2.55e-12
L15 N14 Port2 1.43e-10
R15 N14 Port2 1.67e+01
.ENDS GRM219R71E684KA88
