*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/B(-25to85[deg])/2.20e+01[uF]/10[V]
* Murata P/N :GRM219B31A226MEA0
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM219B31A226MEA0 Port1 Port2
C01 Port1 N01 1.62e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 1.66e-10
R03 N02 N03 2.06e-03
C04 N03 N04 6.32e-04
R04 N03 N04 7.69e+00
C05 N04 N05 8.11e-04
R05 N04 N05 7.63e-01
C06 N05 N06 1.14e-03
R06 N05 N06 6.07e-02
C07 N06 N07 1.17e-03
R07 N06 N07 4.25e-03
L08 N07 N08 1.54e-11
R08 N07 N08 7.88e-02
L09 N08 N09 6.00e-11
R09 N08 N09 3.09e-02
L10 N09 N10 3.49e-10
R10 N09 N10 1.21e-02
C11 N10 N11 9.34e-05
L11 N10 N11 3.73e-11
R11 N10 N11 1.89e-03
C12 N11 N12 3.07e-05
L12 N11 N12 6.20e-11
R12 N11 N12 3.24e-03
C13 N12 N13 1.60e-11
L13 N12 N13 5.23e-11
R13 N12 N13 6.07e+00
C14 N13 Port2 1.04e-11
L14 N13 Port2 2.94e-11
R14 N13 Port2 9.32e+00
.ENDS GRM219B31A226MEA0
