*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.50e-02[uF]/100[V]
* Murata P/N :GRM21BR72A153KA01
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR72A153KA01 Port1 Port2
C01 Port1 N01 1.51e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.69e-10
R03 N02 N03 3.79e-02
C04 N03 N04 1.83e-06
R04 N03 N04 2.02e+03
C05 N04 N05 3.88e-06
R05 N04 N05 2.16e+02
C06 N05 N06 2.37e-06
R06 N05 N06 6.38e+01
C07 N06 N07 2.07e-06
R07 N06 N07 9.23e+00
C08 N07 N08 1.66e-06
R08 N07 N08 1.28e+00
C09 N08 N09 1.47e-06
R09 N08 N09 2.14e-01
C10 N09 N10 1.16e-06
R10 N09 N10 6.45e-02
C11 N10 N11 4.89e-07
R11 N10 N11 2.25e-02
L12 N11 N12 1.03e-10
R12 N11 N12 1.53e-01
C13 N12 N13 9.59e-08
L13 N12 N13 2.19e-11
R13 N12 N13 5.38e-02
C14 N13 N14 1.67e-08
L14 N13 N14 5.33e-11
R14 N13 N14 1.04e-01
C15 N14 N15 1.21e-11
L15 N14 N15 1.33e-10
R15 N14 N15 9.88e+00
C16 N15 Port2 1.91e-12
L16 N15 Port2 1.79e-10
R16 N15 Port2 1.86e+01
.ENDS GRM21BR72A153KA01
