*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7S(-55to125[deg])/1.00e+00[uF]/100[V]
* Murata P/N :GRM21BC72A105KE01
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BC72A105KE01 Port1 Port2
C01 Port1 N01 9.82e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.66e-10
R03 N02 N03 5.53e-03
C04 N03 N04 1.26e-04
R04 N03 N04 1.83e+01
C05 N04 N05 1.04e-04
R05 N04 N05 3.42e+00
C06 N05 N06 9.29e-05
R06 N05 N06 6.37e-01
C07 N06 N07 1.02e-04
R07 N06 N07 8.81e-02
C08 N07 N08 7.34e-05
R08 N07 N08 1.78e-02
C09 N08 N09 8.17e-05
R09 N08 N09 2.84e-03
L10 N09 N10 1.43e-11
R10 N09 N10 5.47e-02
L11 N10 N11 2.26e-10
R11 N10 N11 3.59e-02
L12 N11 N12 1.77e-11
R12 N11 N12 2.03e-02
C13 N12 N13 3.02e-06
L13 N12 N13 5.59e-11
R13 N12 N13 1.53e-02
C14 N13 N14 1.62e-06
L14 N13 N14 4.80e-11
R14 N13 N14 1.33e-02
C15 N14 N15 1.20e-11
L15 N14 N15 8.39e-11
R15 N14 N15 6.83e+00
C16 N15 Port2 7.24e-12
L16 N15 Port2 4.44e-11
R16 N15 Port2 1.30e+01
.ENDS GRM21BC72A105KE01
