*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/2.20e+00[uF]/25[V]
* Murata P/N :GRM21BR71E225KA73
* Property : C = 2.20e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR71E225KA73 Port1 Port2
C01 Port1 N01 1.85e-06
R01 Port1 N01 2.27e+07
L02 N01 N02 1.41e-10
R03 N02 N03 4.83e-03
C04 N03 N04 1.77e-05
R04 N03 N04 3.86e+02
C05 N04 N05 5.67e-05
R05 N04 N05 8.49e+00
C06 N05 N06 4.92e-05
R06 N05 N06 9.87e-01
C07 N06 N07 3.91e-05
R07 N06 N07 1.23e-01
C08 N07 N08 2.92e-05
R08 N07 N08 1.64e-02
L09 N08 N09 7.30e-12
R09 N08 N09 4.41e-02
L10 N09 N10 2.22e-11
R10 N09 N10 3.12e-02
L11 N10 N11 2.40e-10
R11 N10 N11 3.08e-02
C12 N11 N12 5.46e-06
L12 N11 N12 4.73e-11
R12 N11 N12 1.20e-02
C13 N12 N13 2.78e-06
L13 N12 N13 4.65e-11
R13 N12 N13 1.18e-02
C14 N13 N14 1.08e-11
L14 N13 N14 6.86e-11
R14 N13 N14 8.28e+00
C15 N14 Port2 5.99e-12
L15 N14 Port2 4.94e-11
R15 N14 Port2 7.29e+00
.ENDS GRM21BR71E225KA73
