*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.00e-03[uF]/250[V]
* Murata P/N :GRM21AR72E102KW01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21AR72E102KW01 Port1 Port2
C01 Port1 N01 1.02e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.98e-10
R03 N02 N03 3.23e-01
C04 N03 N04 1.02e-07
R04 N03 N04 2.19e+04
C05 N04 N05 1.42e-07
R05 N04 N05 2.70e+03
C06 N05 N06 1.24e-07
R06 N05 N06 6.22e+02
C07 N06 N07 1.17e-07
R07 N06 N07 1.24e+02
C08 N07 N08 9.82e-08
R08 N07 N08 2.61e+01
C09 N08 N09 7.13e-08
R09 N08 N09 5.51e+00
C10 N09 N10 5.47e-08
R10 N09 N10 1.17e+00
C11 N10 N11 1.75e-08
R11 N10 N11 3.44e-01
L12 N11 N12 4.11e-11
R12 N11 N12 5.53e-01
C13 N12 N13 1.40e-09
L13 N12 N13 1.17e-11
R13 N12 N13 1.03e-01
C14 N13 Port2 1.04e-11
L14 N13 Port2 2.19e-10
R14 N13 Port2 1.15e+01
.ENDS GRM21AR72E102KW01
