*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/1.00e-01[uF]/50[V]
* Murata P/N :GRM21BR71H104MA01
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR71H104MA01 Port1 Port2
C01 Port1 N01 9.67e-08
R01 Port1 N01 5.00e+09
L02 N01 N02 7.66e-11
R03 N02 N03 1.45e-02
C04 N03 N04 1.59e-05
R04 N03 N04 2.50e+02
C05 N04 N05 2.80e-05
R05 N04 N05 2.22e+01
C06 N05 N06 1.82e-05
R06 N05 N06 7.71e+00
C07 N06 N07 1.87e-05
R07 N06 N07 1.01e+00
C08 N07 N08 4.13e-05
R08 N07 N08 1.93e-01
C09 N08 N09 2.21e-05
R09 N08 N09 7.70e-02
C10 N09 N10 1.37e-05
R10 N09 N10 3.92e-02
C11 N10 N11 7.58e-06
R11 N10 N11 1.26e-02
L12 N11 N12 4.51e-11
R12 N11 N12 2.65e-01
L13 N12 N13 1.20e-10
R13 N12 N13 8.93e-02
C14 N13 N14 4.91e-07
L14 N13 N14 2.99e-11
R14 N13 N14 3.39e-02
C15 N14 N15 9.88e-08
L15 N14 N15 6.61e-11
R15 N14 N15 4.82e-02
C16 N15 N16 1.67e-11
L16 N15 N16 5.76e-11
R16 N15 N16 5.64e+00
C17 N16 N17 3.41e-12
L17 N16 N17 1.11e-10
R17 N16 N17 1.35e+01
C18 N17 Port2 1.95e-12
L18 N17 Port2 9.64e-11
R18 N17 Port2 1.00e+05
.ENDS GRM21BR71H104MA01
