*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/B(-25to85[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GRM219B31C106KA73
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM219B31C106KA73 Port1 Port2
C01 Port1 N01 5.83e-06
R01 Port1 N01 5.00e+06
L02 N01 N02 1.02e-10
R03 N02 N03 3.34e-03
C04 N03 N04 9.36e-05
R04 N03 N04 4.50e+01
C05 N04 N05 1.59e-04
R05 N04 N05 2.39e+00
C06 N05 N06 1.55e-04
R06 N05 N06 2.51e-01
C07 N06 N07 1.21e-04
R07 N06 N07 3.22e-02
C08 N07 N08 1.18e-04
R08 N07 N08 3.32e-03
L09 N08 N09 1.24e-11
R09 N08 N09 8.21e-02
L10 N09 N10 3.68e-11
R10 N09 N10 3.42e-02
L11 N10 N11 2.44e-10
R11 N10 N11 1.82e-02
C12 N11 N12 1.47e-05
L12 N11 N12 5.57e-11
R12 N11 N12 4.17e-03
C13 N12 N13 7.47e-06
L13 N12 N13 6.06e-11
R13 N12 N13 4.89e-03
C14 N13 N14 1.06e-11
L14 N13 N14 6.40e-11
R14 N13 N14 9.84e+00
C15 N14 Port2 2.73e-12
L15 N14 Port2 1.03e-10
R15 N14 Port2 2.71e+01
.ENDS GRM219B31C106KA73
