*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/6.80e-02[uF]/100[V]
* Murata P/N :GRM21BR72A683MAC4
* Property : C = 6.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR72A683MAC4 Port1 Port2
C01 Port1 N01 7.16e-08
R01 Port1 N01 7.35e+09
L02 N01 N02 1.43e-10
R03 N02 N03 1.98e-02
C04 N03 N04 1.18e-05
R04 N03 N04 2.91e+02
C05 N04 N05 1.79e-05
R05 N04 N05 3.75e+01
C06 N05 N06 1.22e-05
R06 N05 N06 7.84e+00
C07 N06 N07 1.03e-05
R07 N06 N07 1.13e+00
C08 N07 N08 7.52e-06
R08 N07 N08 1.64e-01
C09 N08 N09 4.26e-06
R09 N08 N09 2.56e-02
L10 N09 N10 9.41e-11
R10 N09 N10 9.83e-02
L11 N10 N11 4.48e-12
R11 N10 N11 9.60e-02
C12 N11 N12 3.56e-07
L12 N11 N12 2.62e-11
R12 N11 N12 2.48e-02
C13 N12 N13 6.80e-08
L13 N12 N13 4.76e-11
R13 N12 N13 4.17e-02
C14 N13 N14 9.87e-12
L14 N13 N14 1.41e-10
R14 N13 N14 1.41e+01
C15 N14 Port2 2.32e-12
L15 N14 Port2 1.64e-10
R15 N14 Port2 2.55e+01
.ENDS GRM21BR72A683MAC4
