*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :2012M(0805)/X7R(-55to125[deg])/4.70e-01[uF]/50[V]
* Murata P/N :GRM21BR71H474MA88
* Property : C = 4.70e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM21BR71H474MA88 Port1 Port2
C01 Port1 N01 4.74e-07
R01 Port1 N01 1.06e+09
L02 N01 N02 1.57e-10
R03 N02 N03 6.95e-03
C04 N03 N04 6.41e-05
R04 N03 N04 7.09e+01
C05 N04 N05 8.14e-05
R05 N04 N05 1.00e+01
C06 N05 N06 7.17e-05
R06 N05 N06 2.23e+00
C07 N06 N07 5.31e-05
R07 N06 N07 3.16e-01
C08 N07 N08 7.78e-05
R08 N07 N08 3.46e-02
C09 N08 N09 3.75e-05
R09 N08 N09 1.46e-02
C10 N09 N10 1.17e-04
R10 N09 N10 7.75e-04
L11 N10 N11 1.36e-10
R11 N10 N11 4.20e-02
L12 N11 N12 1.25e-11
R12 N11 N12 2.94e-02
C13 N12 N13 1.65e-06
L13 N12 N13 4.45e-11
R13 N12 N13 2.43e-02
C14 N13 N14 5.80e-07
L14 N13 N14 5.43e-11
R14 N13 N14 2.44e-02
C15 N14 N15 1.36e-11
L15 N14 N15 7.11e-11
R15 N14 N15 9.55e+00
C16 N15 Port2 2.23e-12
L16 N15 Port2 1.57e-10
R16 N15 Port2 2.57e+01
.ENDS GRM21BR71H474MA88
