*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN2N2C80
* Property : L = 2.2[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN2N2C80 port1 port2
C1 port1 port2 9.08e-15
L2 port1 1 1.97e-9
R2 1 port2 1.80e-2
R3 port1 port2 1.42e+4
L4 port1 2 2.46e-5
R4 2 port2 39.5
L5 port1 3 7.13e-8
R5 3 port2 175
.ENDS LQW15AN2N2C80
*----------------------------------------------------------------------
