*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN2N9D80
* Property : L = 2.9[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN2N9D80 port1 port2
C1 port1 port2 3.79e-14
L2 port1 1 2.72e-9
R2 1 port2 3.90e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.35e-7
R4 2 port2 58.4
L5 port1 3 8.58e-8
R5 3 port2 284
.ENDS LQW15AN2N9D80
*----------------------------------------------------------------------
