*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN6N0D80
* Property : L = 6[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN6N0D80 port1 port2
C1 port1 port2 4.39e-14
L2 port1 1 6.11e-9
R2 1 port2 4.60e-2
R3 port1 port2 1.42e+4
L4 port1 2 1.14e-7
R4 2 port2 28.3
L5 port1 3 2.34e-7
R5 3 port2 662
.ENDS LQW15AN6N0D80
*----------------------------------------------------------------------
