*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN6N3G80
* Property : L = 6.3[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN6N3G80 port1 port2
C1 port1 port2 4.60e-14
L2 port1 1 6.40e-9
R2 1 port2 4.70e-2
R3 port1 port2 1.42e+4
L4 port1 2 7.37e-8
R4 2 port2 17.8
L5 port1 3 2.40e-7
R5 3 port2 678
.ENDS LQW15AN6N3G80
*----------------------------------------------------------------------
