*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW15AN68NG80
* Property : L = 68[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW15AN68NG80 port1 port2
C1 port1 port2 2.52e-14
L2 port1 1 6.92e-8
R2 1 port2 9.40e-1
R3 port1 port2 1.42e+4
L4 port1 2 2.18e-6
R4 2 port2 235
L5 port1 3 2.06e-6
R5 3 port2 1.66e+3
L6 port1 4 2.28e-6
C6 4 5 3.64e-16
R6 5 port2 7.03e+3
L7 port1 6 2.02e-6
C7 6 7 1.65e-16
R7 7 port2 6.32e+3
L8 port1 8 1.73e-7
C8 8 9 6.22e-16
R8 9 port2 960
.ENDS LQW15AN68NG80
*----------------------------------------------------------------------
