*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X8G(-55to150[deg])/1.00e-06[uF]/50[V]
* Murata P/N :GCM1555G1H1R0BA16
* Property : C = 1.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-20[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555G1H1R0BA16 Port1 Port2
C01 Port1 N01 1.00e-12
R01 Port1 N01 1.00e+11
L02 N01 N02 4.76e-10
R03 N02 N03 2.04e-01
L04 N03 N04 2.12e-10
R04 N03 N04 4.51e-01
L05 N04 Port2 3.90e-11
R05 N04 Port2 4.24e-01
.ENDS GCM1555G1H1R0BA16
