*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/1.00e-04[uF]/50[V]
* Murata P/N :GCM1552C1H101JA01
* Property : C = 1.00e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1552C1H101JA01 Port1 Port2
C01 Port1 N01 1.00e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 2.65e-10
R03 N02 N03 7.87e-02
L04 N03 N04 1.32e-11
R04 N03 N04 6.83e-02
L05 N04 N05 1.76e-11
R05 N04 N05 2.48e-02
C06 N05 N06 1.08e-09
L06 N05 N06 6.64e-12
R06 N05 N06 4.45e-01
C07 N06 N07 1.58e-10
L07 N06 N07 1.89e-11
R07 N06 N07 1.24e+00
C08 N07 N08 2.89e-11
L08 N07 N08 2.30e-11
R08 N07 N08 1.17e+00
C09 N08 Port2 8.66e-12
L09 N08 Port2 2.98e-11
R09 N08 Port2 1.00e+05
.ENDS GCM1552C1H101JA01
