*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/CH(-55to125[deg])/1.20e-04[uF]/50[V]
* Murata P/N :GCM1552C1H121JA01
* Property : C = 1.20e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1552C1H121JA01 Port1 Port2
C01 Port1 N01 1.20e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 1.45e-10
R03 N02 N03 1.20e-01
C04 N03 N04 2.74e-12
L04 N03 N04 1.03e-10
C05 N04 N05 2.68e-12
L05 N04 N05 7.26e-11
R05 N04 N05 4.39e+00
C06 N05 N06 2.15e-10
L06 N05 N06 1.74e-11
R06 N05 N06 1.16e+00
C07 N06 Port2 8.89e-10
L07 N06 Port2 9.86e-12
R07 N06 Port2 5.69e-01
.ENDS GCM1552C1H121JA01
