*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/3.90e-03[uF]/630[V]
* Murata P/N :GRM31C7U2J392JW32
* Property : C = 3.90e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C7U2J392JW32 Port1 Port2
C01 Port1 N01 3.96e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.21e-10
R03 N02 N03 8.36e-03
L04 N03 N04 1.75e-10
R04 N03 N04 5.18e-01
L05 N04 N05 5.51e-11
R05 N04 N05 1.24e-02
C06 N05 N06 1.06e-08
L06 N05 N06 7.86e-11
R06 N05 N06 8.18e-01
C07 N06 N07 7.75e-09
L07 N06 N07 4.39e-11
R07 N06 N07 7.59e-01
C08 N07 Port2 8.35e-13
L08 N07 Port2 4.87e-10
R08 N07 Port2 8.06e+01
.ENDS GRM31C7U2J392JW32
