*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/1.50e-04[uF]/630[V]
* Murata P/N :GRM31A7U2J151JW31
* Property : C = 1.50e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A7U2J151JW31 Port1 Port2
C01 Port1 N01 1.50e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 7.52e-12
R03 N02 N03 1.19e-01
C04 N03 N04 5.42e-10
L04 N03 N04 2.48e-11
R04 N03 N04 8.12e-01
C05 N04 N05 8.61e-11
L05 N04 N05 4.82e-11
R05 N04 N05 2.38e+00
C06 N05 N06 2.46e-11
L06 N05 N06 3.97e-11
R06 N05 N06 3.76e+00
C07 N06 Port2 8.80e-13
L07 N06 Port2 7.05e-10
R07 N06 Port2 6.68e+02
.ENDS GRM31A7U2J151JW31
