*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/3.60e-02[uF]/100[V]
* Murata P/N :GRM3192C2A363JA01
* Property : C = 3.60e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM3192C2A363JA01 Port1 Port2
C01 Port1 N01 3.63e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 1.50e-10
R03 N02 N03 4.35e-03
L04 N03 N04 1.29e-11
R04 N03 N04 1.75e-01
L05 N04 N05 9.67e-11
R05 N04 N05 1.55e-01
L06 N05 N06 4.45e-11
R06 N05 N06 4.64e-03
L07 N06 N07 2.42e-10
R07 N06 N07 2.30e-03
C08 N07 N08 9.36e-08
L08 N07 N08 6.24e-11
R08 N07 N08 1.47e-01
C09 N08 N09 3.88e-08
L09 N08 N09 6.08e-11
R09 N08 N09 1.97e-01
C10 N09 N10 2.94e-08
L10 N09 N10 2.45e-11
R10 N09 N10 6.00e-02
C11 N10 Port2 1.23e-12
L11 N10 Port2 2.98e-10
R11 N10 Port2 4.04e+02
.ENDS GRM3192C2A363JA01
