*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.80e-03[uF]/630[V]
* Murata P/N :GRM31A5C2J182GWA1
* Property : C = 1.80e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A5C2J182GWA1 Port1 Port2
C01 Port1 N01 1.80e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.18e-13
R03 N02 N03 1.21e-02
C04 N03 N04 2.79e-08
R04 N03 N04 2.26e+02
L05 N04 N05 9.44e-11
R05 N04 N05 2.71e-02
C06 N05 N06 6.37e-09
L06 N05 N06 3.97e-11
R06 N05 N06 6.66e-01
C07 N06 N07 1.95e-09
L07 N06 N07 4.93e-11
R07 N06 N07 9.22e-01
C08 N07 N08 4.59e-10
L08 N07 N08 5.11e-11
R08 N07 N08 3.98e-01
C09 N08 N09 2.64e-10
L09 N08 N09 2.38e-11
R09 N08 N09 3.31e-01
C10 N09 N10 6.01e-12
L10 N09 N10 1.21e-10
R10 N09 N10 3.76e+01
C11 N10 Port2 8.77e-13
L11 N10 Port2 5.21e-10
R11 N10 Port2 4.42e+02
.ENDS GRM31A5C2J182GWA1
