*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/4.70e-05[uF]/2000[V]
* Murata P/N :GRM31A7U3D470JW31
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A7U3D470JW31 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 2.29e-11
R03 N02 N03 1.30e-01
C04 N03 N04 1.44e-10
L04 N03 N04 2.90e-11
R04 N03 N04 2.46e+00
C05 N04 N05 8.42e-12
L05 N04 N05 1.45e-10
R05 N04 N05 2.02e+01
C06 N05 Port2 1.12e-12
L06 N05 Port2 6.21e-10
R06 N05 Port2 5.52e+02
.ENDS GRM31A7U3D470JW31
