*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/1.00e-01[uF]/50[V]
* Murata P/N :GRM31C2C1H104JA01
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C2C1H104JA01 Port1 Port2
C01 Port1 N01 9.75e-08
R01 Port1 N01 5.00e+09
L02 N01 N02 2.30e-11
R03 N02 N03 3.57e-03
L04 N03 N04 1.82e-11
R04 N03 N04 2.43e-01
L05 N04 N05 1.73e-10
R05 N04 N05 1.28e-01
L06 N05 N06 4.95e-11
R06 N05 N06 1.20e-02
C07 N06 N07 2.06e-07
L07 N06 N07 1.26e-10
R07 N06 N07 1.90e-01
C08 N07 N08 1.87e-07
L08 N07 N08 6.53e-11
R08 N07 N08 1.78e-01
C09 N08 N09 5.49e-07
L09 N08 N09 1.18e-11
R09 N08 N09 5.07e-02
C10 N09 N10 1.38e-07
L10 N09 N10 2.98e-11
R10 N09 N10 5.85e-02
C11 N10 N11 1.35e-07
L11 N10 N11 1.70e-11
R11 N10 N11 3.93e-02
C12 N11 Port2 8.47e-13
L12 N11 Port2 4.01e-10
R12 N11 Port2 5.01e+02
.ENDS GRM31C2C1H104JA01
