*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/8.20e-02[uF]/50[V]
* Murata P/N :GRM31C2C1H823JA01
* Property : C = 8.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C2C1H823JA01 Port1 Port2
C01 Port1 N01 8.17e-08
R01 Port1 N01 6.10e+09
L02 N01 N02 1.60e-10
R03 N02 N03 3.14e-03
L04 N03 N04 1.92e-10
R04 N03 N04 1.47e-01
L05 N04 N05 1.69e-10
R05 N04 N05 2.87e-03
C06 N05 N06 2.23e-07
L06 N05 N06 9.69e-11
R06 N05 N06 2.18e-01
C07 N06 N07 1.26e-07
L07 N06 N07 8.03e-11
R07 N06 N07 1.95e-01
C08 N07 N08 2.26e-07
L08 N07 N08 2.31e-11
R08 N07 N08 6.90e-02
C09 N08 N09 1.30e-07
L09 N08 N09 2.61e-11
R09 N08 N09 8.41e-02
C10 N09 Port2 1.33e-12
L10 N09 Port2 2.96e-10
R10 N09 Port2 2.00e+02
.ENDS GRM31C2C1H823JA01
