*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/4.70e-05[uF]/630[V]
* Murata P/N :GRM31A7U2J470JW31
* Property : C = 4.70e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A7U2J470JW31 Port1 Port2
C01 Port1 N01 4.70e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 4.79e-11
R03 N02 N03 1.59e-01
C04 N03 N04 1.61e-10
L04 N03 N04 2.47e-11
R04 N03 N04 2.10e+00
C05 N04 N05 1.12e-11
L05 N04 N05 1.10e-10
R05 N04 N05 1.47e+01
C06 N05 Port2 9.74e-13
L06 N05 Port2 6.17e-10
R06 N05 Port2 4.15e+02
.ENDS GRM31A7U2J470JW31
