*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.00e-03[uF]/630[V]
* Murata P/N :GRM31B5C2J102GW01
* Property : C = 1.00e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31B5C2J102GW01 Port1 Port2
C01 Port1 N01 1.02e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 1.00e-11
R03 N02 N03 1.72e-02
L04 N03 N04 8.83e-11
R04 N03 N04 3.08e-02
C05 N04 N05 3.45e-09
L05 N04 N05 4.63e-11
R05 N04 N05 1.14e+00
C06 N05 N06 1.05e-09
L06 N05 N06 5.67e-11
R06 N05 N06 1.50e+00
C07 N06 N07 3.50e-09
L07 N06 N07 7.92e-12
R07 N06 N07 2.68e-01
C08 N07 N08 1.56e-09
L08 N07 N08 1.07e-11
R08 N07 N08 4.65e-01
C09 N08 N09 5.85e-11
L09 N08 N09 5.41e-11
R09 N08 N09 7.64e-01
C10 N09 Port2 9.15e-13
L10 N09 Port2 6.18e-10
R10 N09 Port2 6.58e+02
.ENDS GRM31B5C2J102GW01
