*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.20e-05[uF]/1000[V]
* Murata P/N :GRM31A5C3A220JW01
* Property : C = 2.20e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A5C3A220JW01 Port1 Port2
C01 Port1 N01 2.20e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 1.72e-10
R03 N02 N03 1.62e-01
C04 N03 N04 2.02e-09
L04 N03 N04 1.38e-12
R04 N03 N04 2.55e-01
C05 N04 N05 5.09e-11
L05 N04 N05 3.42e-11
R05 N04 N05 7.11e+00
C06 N05 N06 2.47e-12
L06 N05 N06 2.34e-10
R06 N05 N06 9.28e+01
C07 N06 Port2 1.00e-12
L07 N06 Port2 3.42e-10
R07 N06 Port2 4.27e+02
.ENDS GRM31A5C3A220JW01
