*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/4.70e-04[uF]/1000[V]
* Murata P/N :GRM31B7U3A471JW31
* Property : C = 4.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31B7U3A471JW31 Port1 Port2
C01 Port1 N01 4.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 4.88e-11
R03 N02 N03 4.46e-02
C04 N03 N04 1.22e-09
L04 N03 N04 7.10e-11
R04 N03 N04 1.95e+00
C05 N04 N05 5.91e-10
L05 N04 N05 6.20e-11
R05 N04 N05 2.07e+00
C06 N05 N06 1.28e-09
L06 N05 N06 1.36e-11
R06 N05 N06 4.87e-01
C07 N06 N07 6.39e-10
L07 N06 N07 1.60e-11
R07 N06 N07 6.95e-01
C08 N07 N08 7.05e-10
L08 N07 N08 7.38e-12
R08 N07 N08 2.26e-01
C09 N08 Port2 6.88e-13
L09 N08 Port2 5.79e-10
R09 N08 Port2 7.84e+01
.ENDS GRM31B7U3A471JW31
