*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/8.20e-03[uF]/50[V]
* Murata P/N :GRM3192C1H822JA01
* Property : C = 8.20e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM3192C1H822JA01 Port1 Port2
C01 Port1 N01 8.12e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 3.13e-11
R03 N02 N03 6.88e-03
L04 N03 N04 1.86e-11
R04 N03 N04 4.97e-01
L05 N04 N05 1.15e-10
R05 N04 N05 2.75e-01
L06 N05 N06 4.32e-11
R06 N05 N06 7.17e-03
L07 N06 N07 1.41e-10
R07 N06 N07 4.97e-03
C08 N07 N08 4.69e-08
L08 N07 N08 3.20e-11
R08 N07 N08 2.02e-01
C09 N08 N09 1.14e-08
L09 N08 N09 4.74e-11
R09 N08 N09 3.22e-01
C10 N09 Port2 7.65e-13
L10 N09 Port2 5.61e-10
R10 N09 Port2 6.42e+02
.ENDS GRM3192C1H822JA01
