*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/SL(-55to125[deg])/6.80e-02[uF]/100[V]
* Murata P/N :GRM31C1X2A683JA01
* Property : C = 6.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C1X2A683JA01 Port1 Port2
C01 Port1 N01 6.49e-08
R01 Port1 N01 7.35e+09
L02 N01 N02 5.26e-12
R03 N02 N03 7.60e-03
L04 N03 N04 9.46e-11
R04 N03 N04 1.79e-01
L05 N04 N05 7.04e-11
R05 N04 N05 5.20e-03
C06 N05 N06 2.74e-07
L06 N05 N06 5.49e-11
R06 N05 N06 9.35e-02
C07 N06 N07 7.45e-08
L07 N06 N07 8.29e-11
R07 N06 N07 1.10e-01
C08 N07 N08 1.94e-08
L08 N07 N08 8.10e-11
R08 N07 N08 6.31e-02
C09 N08 Port2 9.10e-13
L09 N08 Port2 7.41e-10
R09 N08 Port2 7.96e+02
.ENDS GRM31C1X2A683JA01
