*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/3.30e-04[uF]/1000[V]
* Murata P/N :GRM31A5C3A331JWA1
* Property : C = 3.30e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A5C3A331JWA1 Port1 Port2
C01 Port1 N01 3.30e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 3.24e-10
R03 N02 N03 3.75e-03
C04 N03 N04 2.61e-09
R04 N03 N04 1.56e+03
L05 N04 N05 1.49e-10
R05 N04 N05 5.46e-02
C06 N05 N06 1.25e-09
L06 N05 N06 3.41e-11
R06 N05 N06 1.23e+00
C07 N06 N07 2.76e-10
L07 N06 N07 5.65e-11
R07 N06 N07 2.00e+00
C08 N07 N08 9.86e-11
L08 N07 N08 4.02e-11
R08 N07 N08 1.05e+00
C09 N08 N09 1.64e-11
L09 N08 N09 4.46e-11
R09 N08 N09 3.40e+00
C10 N09 Port2 1.46e-12
L10 N09 Port2 3.31e-10
R10 N09 Port2 3.35e+02
.ENDS GRM31A5C3A331JWA1
