*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/1.00e-01[uF]/100[V]
* Murata P/N :GRM31C7U2A104JA01
* Property : C = 1.00e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C7U2A104JA01 Port1 Port2
C01 Port1 N01 9.77e-08
R01 Port1 N01 5.00e+09
L02 N01 N02 5.00e-11
R03 N02 N03 3.84e-03
L04 N03 N04 9.36e-12
R04 N03 N04 1.44e-01
L05 N04 N05 2.30e-10
R05 N04 N05 1.35e-01
L06 N05 N06 5.62e-11
R06 N05 N06 1.09e-03
C07 N06 N07 2.96e-07
L07 N06 N07 8.91e-11
R07 N06 N07 1.79e-01
C08 N07 N08 1.26e-07
L08 N07 N08 9.76e-11
R08 N07 N08 1.33e-01
C09 N08 N09 4.42e-07
L09 N08 N09 1.36e-11
R09 N08 N09 4.14e-02
C10 N09 N10 2.50e-07
L10 N09 N10 1.56e-11
R10 N09 N10 4.73e-02
C11 N10 Port2 9.52e-13
L11 N10 Port2 5.09e-10
R11 N10 Port2 4.22e+02
.ENDS GRM31C7U2A104JA01
