*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.50e-02[uF]/250[V]
* Murata P/N :GRM31C5C2E153FWA3
* Property : C = 1.50e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-1000[MHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C5C2E153FWA3 Port1 Port2
C01 Port1 N01 1.50e-08
R01 Port1 N01 6.67e+09
L02 N01 N02 6.33e-14
R03 N02 N03 7.32e-03
C04 N03 N04 6.71e-07
R04 N03 N04 2.40e+01
L05 N04 N05 6.00e-11
R05 N04 N05 2.78e-03
C06 N05 N06 5.96e-08
L06 N05 N06 5.74e-11
R06 N05 N06 2.98e-01
C07 N06 N07 3.08e-08
L07 N06 N07 4.83e-11
R07 N06 N07 3.08e-01
C08 N07 N08 2.35e-09
L08 N07 N08 1.32e-10
R08 N07 N08 1.41e-01
C09 N08 N09 1.24e-11
L09 N08 N09 7.24e-11
R09 N08 N09 4.83e-01
C10 N09 Port2 8.26e-13
L10 N09 Port2 7.02e-10
R10 N09 Port2 8.74e+02
.ENDS GRM31C5C2E153FWA3
