*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/1.80e-02[uF]/50[V]
* Murata P/N :GRM3192C1H183JA01
* Property : C = 1.80e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM3192C1H183JA01 Port1 Port2
C01 Port1 N01 1.79e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 4.80e-11
R03 N02 N03 6.37e-03
L04 N03 N04 2.84e-11
R04 N03 N04 1.10e+00
L05 N04 N05 1.02e-10
R05 N04 N05 1.81e-01
L06 N05 N06 5.19e-11
R06 N05 N06 7.68e-03
L07 N06 N07 1.82e-10
R07 N06 N07 2.92e-03
C08 N07 N08 8.59e-08
L08 N07 N08 2.99e-11
R08 N07 N08 1.57e-01
C09 N08 N09 1.76e-08
L09 N08 N09 5.80e-11
R09 N08 N09 2.35e-01
C10 N09 Port2 8.46e-13
L10 N09 Port2 4.64e-10
R10 N09 Port2 1.18e+03
.ENDS GRM3192C1H183JA01
