*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/4.70e-02[uF]/50[V]
* Murata P/N :GRM3195C1H473JA05
* Property : C = 4.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM3195C1H473JA05 Port1 Port2
C01 Port1 N01 4.66e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 3.55e-11
R03 N02 N03 3.75e-03
L04 N03 N04 2.04e-11
R04 N03 N04 3.92e-01
L05 N04 N05 1.01e-10
R05 N04 N05 1.26e-01
L06 N05 N06 3.13e-11
R06 N05 N06 5.47e-03
L07 N06 N07 1.31e-10
R07 N06 N07 2.02e-03
L08 N07 N08 4.60e-10
R08 N07 N08 1.07e-03
C09 N08 N09 1.44e-07
L09 N08 N09 5.15e-11
R09 N08 N09 1.32e-01
C10 N09 N10 4.45e-08
L10 N09 N10 6.59e-11
R10 N09 N10 1.76e-01
C11 N10 N11 1.61e-07
L11 N10 N11 8.24e-12
R11 N10 N11 2.64e-02
C12 N11 N12 5.08e-08
L12 N11 N12 1.55e-11
R12 N11 N12 5.32e-02
C13 N12 Port2 9.70e-13
L13 N12 Port2 4.14e-10
R13 N12 Port2 1.03e+03
.ENDS GRM3195C1H473JA05
