*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/1.00e-05[uF]/630[V]
* Murata P/N :GRM31A5C2J100GW01
* Property : C = 1.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A5C2J100GW01 Port1 Port2
C01 Port1 N01 1.00e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 4.98e-11
R03 N02 N03 2.60e-01
C04 N03 N04 5.21e-10
L04 N03 N04 5.10e-12
R04 N03 N04 3.43e-01
C05 N04 Port2 7.65e-13
L05 N04 Port2 7.53e-10
R05 N04 Port2 1.02e+03
.ENDS GRM31A5C2J100GW01
