*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/5.10e-02[uF]/100[V]
* Murata P/N :GRM31M2C2A513JA01
* Property : C = 5.10e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31M2C2A513JA01 Port1 Port2
C01 Port1 N01 5.16e-08
R01 Port1 N01 9.80e+09
L02 N01 N02 4.36e-11
R03 N02 N03 2.52e-03
L04 N03 N04 1.19e-10
R04 N03 N04 1.11e-01
L05 N04 N05 1.75e-11
R05 N04 N05 8.71e-02
L06 N05 N06 8.16e-11
R06 N05 N06 3.69e-03
L07 N06 N07 5.78e-10
R07 N06 N07 1.69e-03
C08 N07 N08 1.52e-07
L08 N07 N08 6.85e-11
R08 N07 N08 1.45e-01
C09 N08 N09 6.18e-08
L09 N08 N09 7.15e-11
R09 N08 N09 2.07e-01
C10 N09 N10 2.53e-08
L10 N09 N10 5.60e-11
R10 N09 N10 6.91e-02
C11 N10 Port2 9.94e-13
L11 N10 Port2 4.40e-10
R11 N10 Port2 6.45e+02
.ENDS GRM31M2C2A513JA01
