*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.70e-02[uF]/100[V]
* Murata P/N :GRM3195C2A273JA01
* Property : C = 2.70e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM3195C2A273JA01 Port1 Port2
C01 Port1 N01 2.66e-08
R01 Port1 N01 1.00e+10
L02 N01 N02 8.87e-12
R03 N02 N03 5.35e-03
L04 N03 N04 1.21e-10
R04 N03 N04 1.54e-01
L05 N04 N05 1.31e-11
R05 N04 N05 1.26e-01
L06 N05 N06 2.75e-11
R06 N05 N06 3.77e-03
L07 N06 N07 2.00e-10
R07 N06 N07 3.26e-03
C08 N07 N08 8.34e-08
L08 N07 N08 4.63e-11
R08 N07 N08 1.55e-01
C09 N08 N09 3.09e-08
L09 N08 N09 4.96e-11
R09 N08 N09 2.13e-01
C10 N09 N10 2.42e-08
L10 N09 N10 1.78e-11
R10 N09 N10 3.61e-02
C11 N10 Port2 7.54e-13
L11 N10 Port2 4.86e-10
R11 N10 Port2 7.08e+02
.ENDS GRM3195C2A273JA01
