*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/4.70e-03[uF]/630[V]
* Murata P/N :GRM31C7U2J472JW32
* Property : C = 4.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C7U2J472JW32 Port1 Port2
C01 Port1 N01 4.73e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 2.75e-10
R03 N02 N03 6.52e-03
L04 N03 N04 2.08e-10
R04 N03 N04 4.95e-01
L05 N04 N05 5.13e-11
R05 N04 N05 7.98e-03
C06 N05 N06 1.39e-08
L06 N05 N06 8.00e-11
R06 N05 N06 1.04e+00
C07 N06 N07 8.63e-09
L07 N06 N07 5.43e-11
R07 N06 N07 7.33e-01
C08 N07 N08 1.70e-08
L08 N07 N08 1.39e-11
R08 N07 N08 2.31e-01
C09 N08 N09 1.21e-08
L09 N08 N09 1.25e-11
R09 N08 N09 2.15e-01
C10 N09 Port2 1.56e-12
L10 N09 Port2 2.31e-10
R10 N09 Port2 1.62e+02
.ENDS GRM31C7U2J472JW32
