*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/CH(-55to125[deg])/1.20e-01[uF]/16[V]
* Murata P/N :GRM31C2C1C124JA01
* Property : C = 1.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C2C1C124JA01 Port1 Port2
C01 Port1 N01 1.21e-07
R01 Port1 N01 4.17e+09
L02 N01 N02 1.42e-10
R03 N02 N03 2.28e-03
L04 N03 N04 2.23e-10
R04 N03 N04 1.01e-01
L05 N04 N05 7.52e-11
R05 N04 N05 1.64e-03
L06 N05 N06 5.12e-10
R06 N05 N06 1.31e-03
C07 N06 N07 4.00e-07
L07 N06 N07 7.83e-11
R07 N06 N07 1.35e-01
C08 N07 N08 2.02e-07
L08 N07 N08 7.30e-11
R08 N07 N08 1.33e-01
C09 N08 N09 8.00e-07
L09 N08 N09 9.31e-12
R09 N08 N09 3.22e-02
C10 N09 N10 3.30e-07
L10 N09 N10 1.48e-11
R10 N09 N10 5.04e-02
C11 N10 Port2 8.28e-13
L11 N10 Port2 4.20e-10
R11 N10 Port2 2.00e+02
.ENDS GRM31C2C1C124JA01
