*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/2.70e-04[uF]/1000[V]
* Murata P/N :GRM31A5C3A271FWA1
* Property : C = 2.70e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31A5C3A271FWA1 Port1 Port2
C01 Port1 N01 2.70e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 4.54e-11
R03 N02 N03 1.51e-02
L04 N03 N04 1.07e-10
R04 N03 N04 5.71e-02
C05 N04 N05 1.02e-09
L05 N04 N05 3.05e-11
R05 N04 N05 1.22e+00
C06 N05 N06 2.18e-10
L06 N05 N06 4.81e-11
R06 N05 N06 1.89e+00
C07 N06 N07 8.20e-11
L07 N06 N07 3.45e-11
R07 N06 N07 1.04e+00
C08 N07 N08 4.42e-11
L08 N07 N08 2.25e-11
R08 N07 N08 3.73e+00
C09 N08 Port2 9.18e-13
L09 N08 Port2 6.06e-10
R09 N08 Port2 5.26e+02
.ENDS GRM31A5C3A271FWA1
