*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/2.20e-02[uF]/250[V]
* Murata P/N :GRM31C7U2E223JW32
* Property : C = 2.20e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C7U2E223JW32 Port1 Port2
C01 Port1 N01 2.20e-08
R01 Port1 N01 4.55e+09
L02 N01 N02 1.29e-10
R03 N02 N03 5.55e-03
C04 N03 N04 6.21e-06
R04 N03 N04 4.06e-01
L05 N04 N05 1.41e-10
R05 N04 N05 1.94e-01
L06 N05 N06 1.02e-10
R06 N05 N06 6.87e-03
C07 N06 N07 1.09e-07
L07 N06 N07 4.98e-11
R07 N06 N07 2.09e-01
C08 N07 N08 3.00e-08
L08 N07 N08 7.89e-11
R08 N07 N08 2.82e-01
C09 N08 N09 1.12e-07
L09 N08 N09 1.06e-11
R09 N08 N09 5.75e-02
C10 N09 N10 4.54e-08
L10 N09 N10 1.65e-11
R10 N09 N10 9.55e-02
C11 N10 N11 3.78e-08
L11 N10 N11 1.04e-11
R11 N10 N11 5.25e-02
C12 N11 N12 1.02e-11
L12 N11 N12 6.71e-11
R12 N11 N12 2.63e+01
C13 N12 Port2 1.50e-12
L13 N12 Port2 2.73e-10
R13 N12 Port2 2.14e+02
.ENDS GRM31C7U2E223JW32
