*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/U2J(-55to125[deg])/2.70e-03[uF]/630[V]
* Murata P/N :GRM31B7U2J272JW31
* Property : C = 2.70e-03[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31B7U2J272JW31 Port1 Port2
C01 Port1 N01 2.74e-09
R01 Port1 N01 1.00e+10
L02 N01 N02 4.40e-11
R03 N02 N03 8.16e-03
L04 N03 N04 1.75e-10
R04 N03 N04 6.36e-01
L05 N04 N05 6.27e-11
R05 N04 N05 1.26e-02
C06 N05 N06 8.42e-09
L06 N05 N06 6.14e-11
R06 N05 N06 7.73e-01
C07 N06 N07 4.31e-09
L07 N06 N07 4.89e-11
R07 N06 N07 7.50e-01
C08 N07 Port2 8.27e-13
L08 N07 Port2 4.84e-10
R08 N07 Port2 4.92e+02
.ENDS GRM31B7U2J272JW31
