*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/C0G(-55to125[deg])/5.60e-02[uF]/100[V]
* Murata P/N :GRM31C5C2A563JA01
* Property : C = 5.60e-02[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1000[kHz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31C5C2A563JA01 Port1 Port2
C01 Port1 N01 5.61e-08
R01 Port1 N01 8.93e+09
L02 N01 N02 1.36e-11
R03 N02 N03 3.44e-03
L04 N03 N04 1.80e-10
R04 N03 N04 1.28e-01
L05 N04 N05 5.96e-12
R05 N04 N05 3.29e-02
L06 N05 N06 1.87e-10
R06 N05 N06 3.16e-03
C07 N06 N07 2.37e-07
L07 N06 N07 5.87e-11
R07 N06 N07 2.12e-01
C08 N07 N08 8.93e-08
L08 N07 N08 7.01e-11
R08 N07 N08 1.92e-01
C09 N08 N09 1.47e-07
L09 N08 N09 2.12e-11
R09 N08 N09 6.26e-02
C10 N09 N10 1.14e-07
L10 N09 N10 1.69e-11
R10 N09 N10 7.16e-02
C11 N10 Port2 9.39e-13
L11 N10 Port2 5.29e-10
R11 N10 Port2 7.76e+02
.ENDS GRM31C5C2A563JA01
