*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/2.90e-06[uF]/25[V]
* Murata P/N :GRM0115C1E2R9BE01
* Property : C = 2.90e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E2R9BE01 Port1 Port2
C01 Port1 N01 2.90e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.10e-10
R03 N02 N03 1.82e-01
L04 N03 N04 3.08e-11
R04 N03 N04 4.13e-01
C05 N04 N05 3.27e-11
L05 N04 N05 9.35e-13
R05 N04 N05 1.48e+00
C06 N05 Port2 9.38e-12
L06 N05 Port2 1.52e-12
R06 N05 Port2 4.59e+00
.ENDS GRM0115C1E2R9BE01
