*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/9.60e-06[uF]/16[V]
* Murata P/N :GRM0115C1C9R6DE01
* Property : C = 9.60e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C9R6DE01 Port1 Port2
C01 Port1 N01 9.60e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.02e-10
R03 N02 N03 1.20e-01
L04 N03 N04 2.09e-12
R04 N03 N04 3.62e-01
L05 N04 N05 1.55e-11
R05 N04 N05 2.41e-01
C06 N05 N06 4.50e-10
L06 N05 N06 9.83e-13
R06 N05 N06 9.66e-02
C07 N06 N07 1.05e-10
L07 N06 N07 1.17e-12
R07 N06 N07 5.90e-01
C08 N07 N08 1.93e-11
L08 N07 N08 2.72e-12
R08 N07 N08 3.15e+00
C09 N08 Port2 1.79e-10
L09 N08 Port2 1.59e-13
R09 N08 Port2 3.06e-01
.ENDS GRM0115C1C9R6DE01
