*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/9.20e-06[uF]/16[V]
* Murata P/N :GRM0115C1C9R2CE01
* Property : C = 9.20e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C9R2CE01 Port1 Port2
C01 Port1 N01 9.20e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.03e-10
R03 N02 N03 1.23e-01
L04 N03 N04 1.41e-11
R04 N03 N04 2.24e-01
C05 N04 N05 1.99e-10
L05 N04 N05 2.04e-12
R05 N04 N05 1.76e-01
C06 N05 N06 1.21e-10
L06 N05 N06 9.66e-13
R06 N05 N06 4.43e-01
C07 N06 Port2 1.48e-11
L07 N06 Port2 3.26e-12
R07 N06 Port2 3.53e+00
.ENDS GRM0115C1C9R2CE01
