*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/1.20e-05[uF]/16[V]
* Murata P/N :GRM0115C1C120GE01
* Property : C = 1.20e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C120GE01 Port1 Port2
C01 Port1 N01 1.20e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 9.44e-11
R03 N02 N03 1.15e-01
C04 N03 N04 1.98e-10
L04 N03 N04 9.99e-12
R04 N03 N04 1.80e-01
C05 N04 N05 1.15e-10
L05 N04 N05 3.51e-12
R05 N04 N05 3.45e-01
C06 N05 N06 7.12e-11
L06 N05 N06 2.35e-12
R06 N05 N06 8.01e-01
C07 N06 N07 2.09e-11
L07 N06 N07 3.46e-12
R07 N06 N07 2.21e+00
C08 N07 Port2 1.16e-11
L08 N07 Port2 2.41e-12
R08 N07 Port2 2.11e+00
.ENDS GRM0115C1C120GE01
