*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/2.20e-06[uF]/25[V]
* Murata P/N :GRM0115C1E2R2CE11
* Property : C = 2.20e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E2R2CE11 Port1 Port2
C01 Port1 N01 2.20e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.12e-10
R03 N02 N03 2.42e-01
L04 N03 N04 1.69e-11
R04 N03 N04 3.93e-01
C05 N04 N05 4.25e-11
L05 N04 N05 6.59e-13
R05 N04 N05 7.83e-01
C06 N05 Port2 2.60e-11
L06 N05 Port2 4.95e-13
R06 N05 Port2 1.96e+00
.ENDS GRM0115C1E2R2CE11
