*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/2.00e-06[uF]/25[V]
* Murata P/N :GRM0115C1E2R0BE11
* Property : C = 2.00e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E2R0BE11 Port1 Port2
C01 Port1 N01 2.00e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.16e-10
R03 N02 N03 2.73e-01
L04 N03 N04 1.71e-11
R04 N03 N04 3.59e-01
C05 N04 N05 6.73e-11
L05 N04 N05 4.39e-13
R05 N04 N05 7.87e-01
C06 N05 Port2 3.35e-11
L06 N05 Port2 4.02e-13
R06 N05 Port2 1.55e+00
.ENDS GRM0115C1E2R0BE11
