*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/8.00e-07[uF]/16[V]
* Murata P/N :GRM0115C1CR80BE11
* Property : C = 8.00e-07[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1CR80BE11 Port1 Port2
C01 Port1 N01 8.00e-13
R01 Port1 N01 1.00e+10
L02 N01 N02 1.13e-10
R03 N02 N03 6.60e-01
L04 N03 N04 1.09e-12
R04 N03 N04 3.62e-02
C05 N04 Port2 9.96e-11
L05 N04 Port2 3.01e-13
R05 N04 Port2 5.50e-01
.ENDS GRM0115C1CR80BE11
