*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/2.00e-05[uF]/25[V]
* Murata P/N :GRM0115C1E200JE01
* Property : C = 2.00e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E200JE01 Port1 Port2
C01 Port1 N01 2.00e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 8.86e-11
R03 N02 N03 1.03e-01
C04 N03 N04 1.64e-10
L04 N03 N04 9.37e-12
R04 N03 N04 1.88e-01
C05 N04 N05 1.80e-10
L05 N04 N05 2.36e-12
R05 N04 N05 2.87e-01
C06 N05 N06 1.91e-10
L06 N05 N06 1.40e-12
R06 N05 N06 3.22e-01
C07 N06 N07 2.78e-11
L07 N06 N07 4.38e-12
R07 N06 N07 1.51e+00
C08 N07 N08 1.49e-10
L08 N07 N08 4.06e-13
R08 N07 N08 3.97e-01
C09 N08 Port2 1.94e-11
L09 N08 Port2 1.55e-12
R09 N08 Port2 1.26e+00
.ENDS GRM0115C1E200JE01
