*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/4.10e-06[uF]/16[V]
* Murata P/N :GRM0115C1C4R1WE01
* Property : C = 4.10e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C4R1WE01 Port1 Port2
C01 Port1 N01 4.10e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.02e-10
R03 N02 N03 1.64e-01
L04 N03 N04 4.40e-12
R04 N03 N04 8.78e-01
C05 N04 N05 9.03e-11
L05 N04 N05 5.47e-12
R05 N04 N05 3.00e-01
C06 N05 N06 5.68e-11
L06 N05 N06 9.33e-13
R06 N05 N06 1.24e+00
C07 N06 Port2 7.72e-12
L07 N06 Port2 2.98e-12
R07 N06 Port2 6.95e+00
.ENDS GRM0115C1C4R1WE01
