*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/4.30e-05[uF]/25[V]
* Murata P/N :GRM0115C1E430GE01
* Property : C = 4.30e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E430GE01 Port1 Port2
C01 Port1 N01 4.30e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 7.35e-11
R03 N02 N03 9.75e-02
C04 N03 Port2 9.68e-13
L04 N03 Port2 3.66e-11
R04 N03 Port2 3.13e+00
.ENDS GRM0115C1E430GE01
