*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/3.70e-06[uF]/25[V]
* Murata P/N :GRM0115C1E3R7WE01
* Property : C = 3.70e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E3R7WE01 Port1 Port2
C01 Port1 N01 3.70e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 9.52e-11
R03 N02 N03 1.70e-01
L04 N03 N04 1.34e-11
R04 N03 N04 8.91e+00
C05 N04 N05 6.16e-11
L05 N04 N05 7.16e-12
R05 N04 N05 3.46e-01
C06 N05 N06 6.92e-11
L06 N05 N06 6.30e-13
R06 N05 N06 1.24e+00
C07 N06 Port2 6.43e-12
L07 N06 Port2 2.95e-12
R07 N06 Port2 5.77e+00
.ENDS GRM0115C1E3R7WE01
