*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/1.80e-04[uF]/25[V]
* Murata P/N :GRM0115C1E181GE01
* Property : C = 1.80e-04[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E181GE01 Port1 Port2
C01 Port1 N01 1.80e-10
R01 Port1 N01 1.00e+10
L02 N01 N02 8.04e-11
R03 N02 N03 7.26e-02
L04 N03 N04 2.12e-11
R04 N03 N04 5.43e-01
C05 N04 Port2 4.27e-10
L05 N04 Port2 6.09e-12
R05 N04 Port2 1.72e-01
.ENDS GRM0115C1E181GE01
