*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/3.30e-05[uF]/16[V]
* Murata P/N :GRM0115C1C330JE01
* Property : C = 3.30e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-9[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C330JE01 Port1 Port2
C01 Port1 N01 3.30e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 8.80e-11
R03 N02 N03 9.91e-02
C04 N03 Port2 1.42e-12
L04 N03 Port2 2.72e-11
R04 N03 Port2 1.69e+00
.ENDS GRM0115C1C330JE01
