*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/8.30e-06[uF]/25[V]
* Murata P/N :GRM0115C1E8R3BE01
* Property : C = 8.30e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1E8R3BE01 Port1 Port2
C01 Port1 N01 8.30e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.04e-10
R03 N02 N03 1.26e-01
L04 N03 N04 2.33e-12
R04 N03 N04 2.91e-01
L05 N04 N05 1.28e-11
R05 N04 N05 1.96e-01
C06 N05 N06 2.77e-10
L06 N05 N06 1.45e-12
R06 N05 N06 1.28e-01
C07 N06 N07 1.36e-10
L07 N06 N07 7.82e-13
R07 N06 N07 4.62e-01
C08 N07 Port2 1.68e-11
L08 N07 Port2 2.56e-12
R08 N07 Port2 3.82e+00
.ENDS GRM0115C1E8R3BE01
