*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/7.30e-06[uF]/16[V]
* Murata P/N :GRM0115C1C7R3DE01
* Property : C = 7.30e-06[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C7R3DE01 Port1 Port2
C01 Port1 N01 7.30e-12
R01 Port1 N01 1.00e+10
L02 N01 N02 1.03e-10
R03 N02 N03 1.27e-01
L04 N03 N04 2.69e-12
R04 N03 N04 2.22e-01
L05 N04 N05 1.19e-11
R05 N04 N05 1.42e-01
C06 N05 N06 2.15e-10
L06 N05 N06 2.13e-12
R06 N05 N06 1.65e-01
C07 N06 N07 1.36e-10
L07 N06 N07 6.47e-13
R07 N06 N07 4.56e-01
C08 N07 Port2 1.31e-11
L08 N07 Port2 2.93e-12
R08 N07 Port2 4.44e+00
.ENDS GRM0115C1C7R3DE01
