*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0201M(008004)/C0G(-55to125[deg])/1.80e-05[uF]/16[V]
* Murata P/N :GRM0115C1C180GE01
* Property : C = 1.80e-05[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[MHz]-30[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0115C1C180GE01 Port1 Port2
C01 Port1 N01 1.80e-11
R01 Port1 N01 1.00e+10
L02 N01 N02 9.11e-11
R03 N02 N03 1.06e-01
C04 N03 N04 2.26e-10
L04 N03 N04 8.10e-12
R04 N03 N04 1.83e-01
C05 N04 N05 1.68e-10
L05 N04 N05 2.56e-12
R05 N04 N05 2.75e-01
C06 N05 N06 1.58e-10
L06 N05 N06 1.51e-12
R06 N05 N06 3.72e-01
C07 N06 N07 2.72e-11
L07 N06 N07 4.10e-12
R07 N06 N07 1.55e+00
C08 N07 Port2 1.80e-11
L08 N07 Port2 1.80e-12
R08 N07 Port2 1.12e+00
.ENDS GRM0115C1C180GE01
