*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/4.70e+01[uF]/6.3[V]
* Murata P/N :GCM32ER70J476ME19
* Property : C = 4.70e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32ER70J476ME19 Port1 Port2
C01 Port1 N01 3.12e-05
R01 Port1 N01 1.06e+06
L02 N01 N02 1.05e-10
R03 N02 N03 1.25e-03
C04 N03 N04 9.61e-04
R04 N03 N04 1.41e+00
C05 N04 N05 1.11e-03
R05 N04 N05 1.35e-01
C06 N05 N06 1.01e-03
R06 N05 N06 1.72e-02
C07 N06 N07 7.40e-04
R07 N06 N07 2.30e-03
L08 N07 N08 1.73e-11
R08 N07 N08 2.33e-02
L09 N08 N09 4.69e-11
R09 N08 N09 1.36e-02
L10 N09 N10 4.35e-10
R10 N09 N10 1.05e-02
C11 N10 N11 7.35e-05
L11 N10 N11 1.36e-10
R11 N10 N11 4.81e-03
C12 N11 N12 3.32e-05
L12 N11 N12 1.34e-10
R12 N11 N12 4.32e-03
C13 N12 N13 2.95e-11
L13 N12 N13 7.86e-11
R13 N12 N13 1.04e+01
C14 N13 N14 6.37e-12
L14 N13 N14 1.57e-10
R14 N13 N14 2.80e+01
C15 N14 Port2 5.47e-12
L15 N14 Port2 1.23e-10
R15 N14 Port2 2.53e+01
.ENDS GCM32ER70J476ME19
