*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/R(-55to125[deg])/1.00e+00[uF]/50[V]
* Murata P/N :GCM32ER11H105KA01
* Property : C = 1.00e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32ER11H105KA01 Port1 Port2
C01 Port1 N01 9.80e-07
R01 Port1 N01 5.00e+08
L02 N01 N02 1.14e-10
R03 N02 N03 5.01e-03
C04 N03 N04 1.62e-04
R04 N03 N04 3.28e+01
C05 N04 N05 1.81e-04
R05 N04 N05 3.68e+00
C06 N05 N06 1.40e-04
R06 N05 N06 5.99e-01
C07 N06 N07 1.09e-04
R07 N06 N07 9.45e-02
C08 N07 N08 2.77e-04
R08 N07 N08 7.21e-03
C09 N08 N09 9.91e-05
R09 N08 N09 7.06e-03
L10 N09 N10 1.91e-10
R10 N09 N10 3.78e-02
C11 N10 N11 2.07e-06
L11 N10 N11 8.97e-11
R11 N10 N11 3.08e-02
C12 N11 N12 1.14e-06
L12 N11 N12 6.69e-11
R12 N11 N12 2.34e-02
C13 N12 N13 1.38e-11
L13 N12 N13 1.53e-10
R13 N12 N13 1.28e+01
C14 N13 Port2 3.03e-12
L14 N13 Port2 2.44e-10
R14 N13 Port2 3.18e+01
.ENDS GCM32ER11H105KA01
