*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/4.70e+00[uF]/50[V]
* Murata P/N :GCM32ER71H475KA55
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32ER71H475KA55 Port1 Port2
C01 Port1 N01 4.65e-06
R01 Port1 N01 1.06e+08
L02 N01 N02 6.77e-11
R03 N02 N03 2.39e-03
C04 N03 N04 5.09e-04
R04 N03 N04 8.57e+00
C05 N04 N05 4.91e-04
R05 N04 N05 8.82e-01
C06 N05 N06 4.96e-04
R06 N05 N06 9.56e-02
C07 N06 N07 5.27e-04
R07 N06 N07 1.44e-02
C08 N07 N08 4.12e-04
R08 N07 N08 2.83e-03
L09 N08 N09 2.48e-11
R09 N08 N09 3.14e-02
L10 N09 N10 2.70e-10
R10 N09 N10 2.55e-02
C11 N10 N11 7.86e-06
L11 N10 N11 1.39e-10
R11 N10 N11 1.84e-02
C12 N11 N12 4.61e-06
L12 N11 N12 9.79e-11
R12 N11 N12 1.25e-02
C13 N12 N13 3.03e-11
L13 N12 N13 7.16e-11
R13 N12 N13 3.84e+00
C14 N13 Port2 2.22e-12
L14 N13 Port2 2.30e-10
R14 N13 Port2 7.88e+01
.ENDS GCM32ER71H475KA55
