*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/1.00e+01[uF]/25[V]
* Murata P/N :GCM32ER71E106KA42
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32ER71E106KA42 Port1 Port2
C01 Port1 N01 9.93e-06
R01 Port1 N01 5.00e+07
L02 N01 N02 5.11e-11
R03 N02 N03 1.54e-03
C04 N03 N04 1.06e-03
R04 N03 N04 4.65e+00
C05 N04 N05 1.29e-03
R05 N04 N05 3.70e-01
C06 N05 N06 1.07e-03
R06 N05 N06 4.86e-02
C07 N06 N07 1.48e-03
R07 N06 N07 4.18e-03
C08 N07 N08 2.17e-03
R08 N07 N08 1.03e-03
L09 N08 N09 2.82e-11
R09 N08 N09 3.31e-02
L10 N09 N10 3.55e-10
R10 N09 N10 2.03e-02
C11 N10 N11 1.94e-05
L11 N10 N11 1.46e-10
R11 N10 N11 1.50e-02
C12 N11 N12 1.10e-05
L12 N11 N12 1.13e-10
R12 N11 N12 1.05e-02
C13 N12 N13 3.28e-11
L13 N12 N13 4.84e-11
R13 N12 N13 5.31e+00
C14 N13 Port2 1.94e-12
L14 N13 Port2 2.24e-10
R14 N13 Port2 1.08e+02
.ENDS GCM32ER71E106KA42
