*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/1.00e+01[uF]/16[V]
* Murata P/N :GCM32DR71C106KA37
* Property : C = 1.00e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32DR71C106KA37 Port1 Port2
C01 Port1 N01 9.50e-06
R01 Port1 N01 5.00e+07
L02 N01 N02 2.02e-10
R03 N02 N03 1.64e-03
C04 N03 N04 2.57e-03
R04 N03 N04 2.07e+00
C05 N04 N05 1.76e-03
R05 N04 N05 4.57e-01
C06 N05 N06 1.21e-03
R06 N05 N06 9.18e-02
C07 N06 N07 1.48e-03
R07 N06 N07 1.13e-02
C08 N07 N08 1.22e-03
R08 N07 N08 1.64e-03
L09 N08 N09 1.21e-11
R09 N08 N09 3.30e-02
L10 N09 N10 2.71e-11
R10 N09 N10 2.10e-02
L11 N10 N11 3.59e-10
R11 N10 N11 1.82e-02
C12 N11 N12 1.62e-05
L12 N11 N12 1.55e-10
R12 N11 N12 1.22e-02
C13 N12 N13 1.21e-05
L13 N12 N13 9.04e-11
R13 N12 N13 1.01e-02
C14 N13 Port2 3.89e-12
L14 N13 Port2 1.03e-10
R14 N13 Port2 1.48e+01
.ENDS GCM32DR71C106KA37
