*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/4.70e+00[uF]/25[V]
* Murata P/N :GCM32DR71E475KA55
* Property : C = 4.70e+00[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32DR71E475KA55 Port1 Port2
C01 Port1 N01 4.58e-06
R01 Port1 N01 1.06e+08
L02 N01 N02 1.06e-10
R03 N02 N03 2.17e-03
C04 N03 N04 7.19e-04
R04 N03 N04 7.05e+00
C05 N04 N05 1.29e-03
R05 N04 N05 6.51e-01
C06 N05 N06 7.30e-04
R06 N05 N06 2.30e-01
C07 N06 N07 6.67e-04
R07 N06 N07 4.08e-02
C08 N07 N08 7.04e-04
R08 N07 N08 6.08e-03
C09 N08 N09 7.18e-04
R09 N08 N09 1.32e-03
L10 N09 N10 2.69e-11
R10 N09 N10 3.37e-02
L11 N10 N11 3.23e-10
R11 N10 N11 2.34e-02
C12 N11 N12 9.07e-06
L12 N11 N12 1.23e-10
R12 N11 N12 1.75e-02
C13 N12 N13 5.83e-06
L13 N12 N13 8.21e-11
R13 N12 N13 1.30e-02
C14 N13 N14 1.50e-11
L14 N13 N14 4.59e-11
R14 N13 N14 3.84e+00
C15 N14 Port2 2.21e-12
L15 N14 Port2 1.59e-10
R15 N14 Port2 4.64e+01
.ENDS GCM32DR71E475KA55
