*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R(-55to125[deg])/2.20e-01[uF]/250[V]
* Murata P/N :GCM32DR72E224KX01
* Property : C = 2.20e-01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-3[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32DR72E224KX01 Port1 Port2
C01 Port1 N01 2.25e-07
R01 Port1 N01 4.55e+08
L02 N01 N02 3.14e-10
R03 N02 N03 9.66e-03
C04 N03 N04 1.92e-05
R04 N03 N04 9.97e+01
C05 N04 N05 2.29e-05
R05 N04 N05 1.80e+01
C06 N05 N06 1.90e-05
R06 N05 N06 3.96e+00
C07 N06 N07 1.61e-05
R07 N06 N07 7.89e-01
C08 N07 N08 1.70e-05
R08 N07 N08 1.10e-01
C09 N08 N09 1.38e-05
R09 N08 N09 1.54e-02
L10 N09 N10 1.75e-11
R10 N09 N10 1.67e-01
L11 N10 N11 1.76e-10
R11 N10 N11 8.25e-02
C12 N11 N12 6.56e-07
L12 N11 N12 5.37e-11
R12 N11 N12 4.62e-02
C13 N12 N13 1.72e-07
L13 N12 N13 7.79e-11
R13 N12 N13 4.50e-02
C14 N13 Port2 1.53e-11
L14 N13 Port2 1.52e-10
R14 N13 Port2 7.16e+00
.ENDS GCM32DR72E224KX01
