*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/R(-55to125[deg])/2.20e+01[uF]/10[V]
* Murata P/N :GCM32ER11A226ME11
* Property : C = 2.20e+01[uF]
* Data Generated on Apr 08, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM32ER11A226ME11 Port1 Port2
C01 Port1 N01 2.19e-05
R01 Port1 N01 2.27e+06
L02 N01 N02 1.43e-10
R03 N02 N03 1.32e-03
C04 N03 N04 3.37e-03
R04 N03 N04 1.47e+00
C05 N04 N05 2.98e-03
R05 N04 N05 2.14e-01
C06 N05 N06 2.22e-03
R06 N05 N06 3.71e-02
C07 N06 N07 3.52e-03
R07 N06 N07 2.68e-03
C08 N07 N08 6.58e-03
R08 N07 N08 4.99e-04
L09 N08 N09 2.43e-11
R09 N08 N09 3.81e-02
L10 N09 N10 4.68e-10
R10 N09 N10 1.36e-02
L11 N10 N11 2.93e-11
R11 N10 N11 8.08e-03
C12 N11 N12 4.11e-05
L12 N11 N12 1.83e-10
R12 N11 N12 8.49e-03
C13 N12 N13 3.13e-05
L13 N12 N13 1.04e-10
R13 N12 N13 5.99e-03
C14 N13 N14 1.24e-11
L14 N13 N14 5.60e-11
R14 N13 N14 5.52e+00
C15 N14 Port2 3.86e-12
L15 N14 Port2 8.88e-11
R15 N14 Port2 2.88e+01
.ENDS GCM32ER11A226ME11
